export type MerchItem = {
  id: string;
  name: string;
  nameEn: string;
  maker: string;
  year: string;
  spec: string;
  image: string;
  imageAlt: string;
  body: string;
  sourceUrl?: string;
  sourceLabel?: string;
  verifiedAt?: string;
};

export type MerchGroup = {
  id: string;
  kicker: string;
  title: string;
  titleEn: string;
  intro: string;
  items: MerchItem[];
};

export const MERCH: MerchGroup[] = [
  {
    id: "figures",
    kicker: "01",
    title: "可动人偶",
    titleEn: "Action Figures",
    intro:
      "收录官方授权的 1/6 收藏级可动人偶、7 寸量产可动人偶及流行文化潮玩，注重角色头雕还原、战衣剪裁与可动把玩体验。",
    items: [
      {
        id: "inart",
        name: "INART 1/6 蝙蝠侠珍藏人偶",
        nameEn: "The Batman 1/6 Collectible Figure",
        maker: "INART · Queen Studios",
        year: "2023",
        spec: "1/6 比例 · 常规版 / 植发豪华版",
        image: "/media/merch/inart.jpg",
        imageAlt: "INART 1/6 蝙蝠侠全身官方产品展示图",
        body: "Queen Studios 旗下高端可动厂牌 INART 出品。配备独立可动眼球系统与多款替换表情，豪华版特别附带手工植发头雕。战衣严格按照电影多层结构剪裁制作，细致还原防弹护甲与布料质感。",
        sourceUrl: "https://queenstudios.shop/products/batman-1-6-collectible-figure",
        sourceLabel: "Queen Studios / INART 产品页",
        verifiedAt: "2026.08.24",
      },
      {
        id: "hottoys",
        name: "Hot Toys 蝙蝠侠与蝙蝠信号灯套装",
        nameEn: "Batman and Bat-Signal Set",
        maker: "Hot Toys",
        year: "2022",
        spec: "1/6 比例 · MMS641 豪华套装",
        image: "/media/merch/hottoys.jpg",
        imageAlt: "Hot Toys 1/6 蝙蝠侠站在点亮的蝙蝠信号灯旁",
        body: "Hot Toys 推出的 1/6 比例人偶套装。配备全新开发的面罩头雕与可替换下半脸造型，豪华版特别附带可通电发光的 1/6 蝙蝠信号灯地台，以及抓钩枪、战术飞镖等武器配件。",
      },
      {
        id: "mcfarlane-bruce",
        name: "麦克法兰 7 寸未戴面罩布鲁斯·韦恩",
        nameEn: "Bruce Wayne Unmasked (DC Multiverse)",
        maker: "McFarlane Toys",
        year: "2022",
        spec: "7 寸比例可动人偶",
        image: "/media/merch/mcfarlane-bruce.jpg",
        imageAlt: "McFarlane 7 寸未戴面罩布鲁斯人偶包装与配件",
        body: "麦克法兰 DC Multiverse 系列推出的便装造型布鲁斯·韦恩。还原了布鲁斯身穿飞行员夹克、背负双肩包、眼部留有深黑眼妆的侦查形象，拥有 22 处可动关节。",
      },
      {
        id: "mcfarlane-cast",
        name: "麦克法兰 7 寸核心角色阵容",
        nameEn: "Penguin / Catwoman / Bruce Set",
        maker: "McFarlane Toys",
        year: "2022",
        spec: "7 寸系列头雕与人偶",
        image: "/media/merch/mcfarlane-cast.jpg",
        imageAlt: "McFarlane 企鹅人、猫女与布鲁斯头雕特写展示",
        body: "麦克法兰为电影打造的量产可动产品线，涵盖企鹅人、猫女、谜语人及战衣版蝙蝠侠，具备出色的性价比与丰富的把玩配件。",
      },
      {
        id: "funko",
        name: "Funko Pop! 电影全套乙烯玩偶",
        nameEn: "Pop! Movies · The Batman Series",
        maker: "Funko",
        year: "2022",
        spec: "乙烯公仔 · 包含常规款与 Rides 战车款",
        image: "/media/merch/funko.jpg",
        imageAlt: "Funko 官方公布的《新蝙蝠侠》全套 Pop! 玩偶",
        body: "Funko 官方授权系列，以经典 Q 版大头造型重塑了蝙蝠侠、猫女、企鹅人、谜语人以及驾驶蝙蝠战车的 Pop! Rides 系列，是流传广泛的流行文化收藏品。",
      },
    ],
  },
  {
    id: "props",
    kicker: "02",
    title: "1:1 电影道具复刻",
    titleEn: "1:1 Prop Replicas",
    intro:
      "基于华纳兄弟制片团队的原始数字模型与道具原件扫描数据，采用实心合金压铸打造的 1:1 比例道具复刻，具备极高的陈列与收藏价值。",
    items: [
      {
        id: "fe-batarang",
        name: "Factory Entertainment 1:1 金属蝙蝠飞镖",
        nameEn: "The Batman Batarang Limited Edition Prop Replica",
        maker: "Factory Entertainment · 华纳官方授权",
        year: "2022",
        spec: "1:1 比例 · 实心压铸金属 · 钢琴烤漆亚克力展示盒",
        image: "/media/merch/fe-batarang.jpg",
        imageAlt: "Factory Entertainment 1:1 蝙蝠飞镖金属复刻道具与展示盒",
        body: "根据《新蝙蝠侠》制片组提供的原始数字资产打造。全尺寸纯金属铸造，表面施以手工战损与做旧效果，还原大银幕质感；附带专属编号金属铭牌与展示盒。",
        sourceUrl:
          "https://factoryent.com/products/the-batman-batarang-limited-edition-prop-replica",
        sourceLabel: "Factory Entertainment 产品页",
        verifiedAt: "2026.08.24",
      },
      {
        id: "paragon-glyph",
        name: "Paragon FX 1:1 胸甲可拆卸金属蝙蝠徽标",
        nameEn: "The Batman 2022 Bat Glyph 1:1 Metal Prop Replica",
        maker: "Paragon FX Group · 华纳官方授权",
        year: "2022",
        spec: "1:1 全尺寸 · 纯金属实心铸造 · 全球限量 750 件",
        image: "/media/merch/paragon-glyph.jpg",
        imageAlt: "Paragon FX 1:1 金属蝙蝠徽标双面与展开形态",
        body: "由 Paragon 依据电影道具原件 STL 文件 1:1 打造。全金属实心结构，忠实还原了胸甲徽记表面的细微机械纹理，并可按电影设定拆卸展开为双刃折叠战术刀。",
        sourceUrl: "https://paragonfxgroup.com/products/thebatman2022",
        sourceLabel: "Paragon FX 产品页",
        verifiedAt: "2026.08.24",
      },
      {
        id: "fe-grapnel",
        name: "Factory Entertainment 1:1 战术抓钩发射器",
        nameEn: "The Batman Grapple Launcher 1:1 Life-Size Prop Replica",
        maker: "Factory Entertainment · 华纳官方授权",
        year: "2022",
        spec: "1:1 比例 · 全金属铸造 · 全球限量 1500 件",
        image: "/media/merch/fe-grapnel.jpg",
        imageAlt: "Factory Entertainment 1:1 战术抓钩枪实物展示",
        body: "全尺寸 1:1 电影实体道具复刻，尺寸约 10×21×5 厘米。采用实心合金精密压铸，细致呈现了钢缆线轴、握把机械制动结构与战损涂装，配有展示盒与独立编号收藏证书。",
        sourceUrl:
          "https://factoryent.com/products/the-batman-grapple-launcher-limited-edition-prop-replica",
        sourceLabel: "Factory Entertainment 产品页",
        verifiedAt: "2026.08.24",
      },
    ],
  },
  {
    id: "statues",
    kicker: "03",
    title: "高端雕像",
    titleEn: "Statues",
    intro:
      "收录 1:1 等身硅胶胸像与博物馆级宝丽石全身像，以恢弘体量还原战衣金属光泽、布料纹理与哥谭滴水兽地台。",
    items: [
      {
        id: "infinity-bust",
        name: "Infinity Studio 1:1 蝙蝠侠等身胸像",
        nameEn: "The Batman Life-Size Bust",
        maker: "Infinity Studio · 开天工作室 × Penguin Toys",
        year: "2022",
        spec: "1:1 等身 · 高约 93 cm · 全球限量 500 尊",
        image: "/media/merch/infinity-bust.jpg",
        imageAlt: "Infinity Studio 《新蝙蝠侠》1:1 等身胸像，滴水兽地台",
        body: "由开天工作室（Infinity Studio）与 Penguin Toys 联合打造。采用铂金硅胶头雕与医用级硅胶皮肤，战衣使用真皮与定制织物。全高约 93 厘米，地台按电影视觉做成哥谭滴水兽建筑，滴水兽可磁吸拆卸单独展示。全球限量 500 尊。",
        sourceUrl:
          "https://www.sideshow.com/collectibles/dc-comics-batman-infinity-studio-infinity-studio-910677",
        sourceLabel: "Sideshow 产品页",
        verifiedAt: "2026.08.24",
      },
      {
        id: "p1s",
        name: "Prime 1 Studio 1/3 博物馆级电影版蝙蝠侠",
        nameEn: "Museum Masterline × Blitzway",
        maker: "Prime 1 Studio × Blitzway",
        year: "2023",
        spec: "1/3 比例 · 高约 79 cm · 高级宝丽石树脂",
        image: "/media/merch/p1s.jpg",
        imageAlt: "Prime 1 Studio 与 Blitzway 合作的 1/3 蝙蝠侠全身雕像",
        body: "由 Prime 1 Studio 与 Blitzway 联手打造。全高约 79 厘米，细致还原了皮革纹理、硬质防弹板与金属磨损细节，准确再现帕丁森在电影中的冷峻神态。",
      },
      {
        id: "p1s-sae",
        name: "Prime 1 Studio 特殊艺术限定版雕像",
        nameEn: "Special Art Edition Deluxe",
        maker: "Prime 1 Studio",
        year: "2022",
        spec: "1/3 比例 · 高约 88 cm · 限量发行",
        image: "/media/merch/p1s-sae.jpg",
        imageAlt: "Prime 1 Studio 特殊艺术版红雨灯光效果全身雕像",
        body: "以传奇漫画家吉姆·李（Jim Lee）为 DC FanDome 创作的概念插画为灵感，结合电影实拍装甲细节，地台融合了哥谭标志性滴水兽雕塑与红雨氛围灯效。",
      },
    ],
  },
  {
    id: "vehicles",
    kicker: "04",
    title: "车模与遥控载具",
    titleEn: "Vehicles",
    intro:
      "涵盖合金车模、遥控车与 1/6 收藏级载具，重现美式改装肌肉车底盘、外露涡轮引擎与全钢防滚架细节。",
    items: [
      {
        id: "hotwheels-rc",
        name: "Hot Wheels R/C 1:10 电影蝙蝠战车",
        nameEn: "The Batman The Original Batmobile (HCD19)",
        maker: "Hot Wheels R/C · 美泰（Mattel）",
        year: "2022",
        spec: "1:10 比例遥控车 · 后驱 · 车灯与尾喷可发光",
        image: "/media/merch/hotwheels-rc.jpg",
        imageAlt: "Hot Wheels R/C 与《新蝙蝠侠》联名 1:10 遥控战车及手柄",
        body: "美泰风火轮推出的全功能遥控电影战车（货号 HCD19）。1:10 比例，手枪式遥控手柄，后驱带悬挂系统，最高时速约 16 公里；前大灯与尾喷口可通电发光，驾驶舱可放入约 6 寸人偶。",
        sourceUrl:
          "https://creations.mattel.com/products/hot-wheels-rc-the-batman-the-original-batmobile-hcd19",
        sourceLabel: "Mattel Creations 产品页 HCD19",
        verifiedAt: "2026.08.24",
      },
      {
        id: "jazzinc-clean",
        name: "Jazzinc 1/6 电影蝙蝠战车（普通版）",
        nameEn: "1/6 Batmobile from The Batman (2022) — Clean Version",
        maker: "Jazzinc Dioramas",
        year: "2022",
        spec: "1/6 比例 · 约 905 × 431 × 247 mm · 约 14 kg",
        image: "/media/merch/jazzinc-clean.jpg",
        imageAlt: "Jazzinc Dioramas 1/6 电影蝙蝠战车普通版侧前方",
        body: "荷兰 Jazzinc 依据电影实车图纸打造的 1/6 收藏级战车，适配 Hot Toys、INART 等 12 寸人偶。全车包含钢架结构与上千个零件，V8 引擎、仪表台与轮胎花纹按比例精准还原，配备灯光地台、车灯照明、排气烟雾与引擎音效系统。",
        sourceUrl:
          "https://jazzincdioramas.com/vehicles/16-scale-batmobile-from-the-batman-2022-clean-version",
        sourceLabel: "Jazzinc 普通版产品页",
        verifiedAt: "2026.08.24",
      },
      {
        id: "jazzinc-weathered",
        name: "Jazzinc 1/6 电影蝙蝠战车（战损版）",
        nameEn: "1/6 Batmobile from The Batman (2022) — Weathered Version",
        maker: "Jazzinc Dioramas",
        year: "2022",
        spec: "1/6 比例 · 战损涂装 · 电子声光烟雾功能",
        image: "/media/merch/jazzinc-weathered.jpg",
        imageAlt: "Jazzinc Dioramas 1/6 电影蝙蝠战车战损版，泥污与擦痕涂装",
        body: "与普通版同比例及同电子功能配置（含灯光、烟雾、音效与遥控），涂装重点还原企鹅人追逐战后的重度战损状态：车身布满泥泞溅痕、撞击刮痕与积尘。",
        sourceUrl: "https://jazzincdioramas.com/vehicles/batmobile2022weathered",
        sourceLabel: "Jazzinc 战损版产品页",
        verifiedAt: "2026.08.24",
      },
      {
        id: "hotwheels",
        name: "风火轮 1:50 电影蝙蝠战车合金车模",
        nameEn: "Hot Wheels 1:50 Batman Series Batmobile",
        maker: "Hot Wheels · 美泰（Mattel）",
        year: "2022",
        spec: "1:50 比例合金车模",
        image: "/media/merch/hotwheels.jpg",
        imageAlt: "风火轮 1:50 蝙蝠战车合金模型细节",
        body: "美泰风火轮推出的中比例合金收藏车模。车身采用全金属压铸工艺，细致刻画了车头冲撞保险杠、外露后置引擎与双排气管细节。",
      },
      {
        id: "jada-32",
        name: "Jada 1:32 合金蝙蝠战车",
        nameEn: "Jada Toys 1:32 Die-Cast Batmobile",
        maker: "Jada Toys · Hollywood Rides",
        year: "2022",
        spec: "1:32 比例合金模型",
        image: "/media/merch/jada-box.jpg",
        imageAlt: "Jada 1:32 合金战车包装盒与车身展示",
        body: "采用开门设计与真实橡胶轮胎，包装印有电影红黑标志性视觉，是大众市场最受欢迎的桌上展示车模之一。",
      },
      {
        id: "jada-18",
        name: "Jada 1:18 大比例合金战车带人偶",
        nameEn: "Jada Toys 1:18 Batmobile with Figure",
        maker: "Jada Toys",
        year: "2022",
        spec: "1:18 比例 · 车灯可亮 · 附金属蝙蝠侠人偶",
        image: "/media/merch/jada-18.jpg",
        imageAlt: "Jada 1:18 战车车灯点亮状态与金属人偶",
        body: "大比例合金战车模型，车头大灯与尾部引擎支持 LED 通电发光，座舱内部精细还原了仪表台与防滚架，随盒附赠同比例压铸金属蝙蝠侠人偶。",
      },
    ],
  },
  {
    id: "lego",
    kicker: "05",
    title: "乐高套组",
    titleEn: "LEGO Sets",
    intro:
      "收录乐高在 2022 年电影上映前后推出的超级英雄（DC Super Heroes）与机械组（Technic）套组，以及 2026 年 DC 蝙蝠侠二十周年传奇蝙蝠车系列。",
    items: [
      {
        id: "lego-76181",
        name: "乐高 76181 蝙蝠战车：企鹅人追逐战",
        nameEn: "Batmobile: The Penguin Chase",
        maker: "LEGO · 乐高 DC 超级英雄系列",
        year: "2022",
        spec: "392 颗粒 · 附 2 枚迷你人仔",
        image: "/media/merch/lego-76181.jpg",
        imageAlt: "乐高 76181 蝙蝠战车与企鹅人人仔包装盒",
        body: "迷你人仔比例的电影版战车，还原美式肌肉车底盘、外露后置引擎与后扰流板。附带蝙蝠侠与企鹅人两枚人仔，重现冰山俱乐部外的公路追逐场景。",
      },
      {
        id: "lego-76179",
        name: "乐高 76179 蝙蝠侠与瑟琳娜摩托追逐",
        nameEn: "Batman & Selina Kyle Motorcycle Pursuit",
        maker: "LEGO · 乐高 DC 超级英雄系列",
        year: "2022",
        spec: "149 颗粒 · 附 2 枚迷你人仔与双摩托",
        image: "/media/merch/lego-76179.jpg",
        imageAlt: "乐高 76179 蝙蝠侠与猫女双机车套组",
        body: "双车场景套组，包含蝙蝠侠与瑟琳娜·凯尔两枚人仔及各自专属机车，对应影片中的雨夜巡行，可停放于 76183 蝙蝠洞内。",
      },
      {
        id: "lego-76183",
        name: "乐高 76183 蝙蝠洞：谜语人对决",
        nameEn: "Batcave: The Riddler Face-off",
        maker: "LEGO · 乐高 DC 超级英雄系列",
        year: "2022",
        spec: "581 颗粒 · 附 6 枚迷你人仔",
        image: "/media/merch/lego-76183.jpg",
        imageAlt: "乐高 76183 蝙蝠洞地下站台场景与六枚人仔",
        body: "该系列最大的场景套组。主体为韦恩塔地底废弃火车站改建的蝙蝠洞，可停放 76181 战车与 76179 摩托。包含蝙蝠侠、瑟琳娜、谜语人、流浪者布鲁斯、阿尔弗雷德与戈登共六枚人仔。",
      },
      {
        id: "lego-30455",
        name: "乐高 30455 蝙蝠战车（微型拼砌包）",
        nameEn: "Batmobile Polybag",
        maker: "LEGO · 乐高 DC 超级英雄系列",
        year: "2022",
        spec: "68 颗粒 · 拼砌袋装",
        image: "/media/merch/lego-30455.jpg",
        imageAlt: "乐高 30455 微型袋装战车",
        body: "电影宣传期间推出的微型拼砌包战车，共 68 个零件，适合作为小比例桌面摆件或快速拼搭体验。",
      },
      {
        id: "lego-42127",
        name: "乐高机械组 42127 电影版蝙蝠战车",
        nameEn: "THE BATMAN - BATMOBILE (Technic)",
        maker: "LEGO · 乐高机械组 Technic",
        year: "2022",
        spec: "1360 颗粒 · 发光积木 · 差速器与独立悬挂",
        image: "/media/merch/lego-42127.jpg",
        imageAlt: "乐高机械组 42127 大比例战车与发光效果",
        body: "机械组（Technic）大比例电影战车，由 1360 个零件构成。配备可动 V8 引擎活塞、后轮差速器、前轮转向与双发光积木（黄色前灯与红色后引擎喷火）。",
      },
      {
        id: "lego-76332",
        name: "乐高 76332 电影版蝙蝠战车",
        nameEn: "The Batman Batmobile (20th Anniversary)",
        maker: "LEGO · 乐高 DC 系列",
        year: "2026",
        spec: "经典复刻系列 · 附纪念金币与专属铭牌",
        image: "/media/merch/lego-76332.jpg",
        imageAlt: "乐高 76332 2022 电影版战车",
        body: "乐高 DC 蝙蝠侠二十周年「传奇蝙蝠车」系列中的 2022 电影版。车顶可拆卸，驾驶舱可放入佩戴布质披风的蝙蝠侠人仔，附带专属展示铭牌与纪念金币。",
      },
    ],
  },
  {
    id: "lifestyle",
    kicker: "06",
    title: "腕表、电竞与潮流跨界",
    titleEn: "Lifestyle & Collabs",
    intro:
      "收录华纳官方与瑞士高端独立制表、时尚腕表、专业电竞外设及运动品牌推出的跨界限定收藏品。",
    items: [
      {
        id: "kross-studio",
        name: "Kross Studio × The Batman 陀飞轮收藏套装",
        nameEn: "The Batman Tourbillon Collector Set",
        maker: "Kross Studio · 瑞士高级独立制表",
        year: "2022",
        spec: "45mm 钛金属 DLC 黑化 · 中央陀飞轮 · 限量 10 套",
        image: "/media/merch/kross-studio.jpg",
        imageAlt: "Kross Studio 陀飞轮腕表与信号灯表盒雕塑",
        body: "瑞士独立制表品牌 Kross Studio 与华纳联合推出的高级制表套装。腕表采用 45 毫米 5 级钛金属 DLC 黑化表壳，中央陀飞轮框架巧妙融入蝙蝠徽格栅设计，搭载 KS 7'000 手动上链机芯，具备 5 天动力储存；随表附带全尺寸可通电发光的蝙蝠信号灯铝合金表盒雕塑。",
        sourceUrl: "https://kross-studio.com/the-batman-collector-set",
        sourceLabel: "Kross Studio 产品页",
        verifiedAt: "2026.08.24",
      },
      {
        id: "police-batman",
        name: "Police × The Batman 联名限量腕表",
        nameEn: "Police x The Batman Limited Edition Watches",
        maker: "Police Lifestyle · 意大利时尚腕表",
        year: "2022",
        spec: "多款限量设计 · 多时区机芯 · 专属蝙蝠徽表盒",
        image: "/media/merch/police-batman.jpg",
        imageAlt: "Police 联名四款电影腕表实物展示",
        body: "意大利时尚腕表品牌 Police 推出的四款电影联名表款，分别对应蝙蝠侠、Vengeance、哥谭市与猫女主题。表壳采用棱角分明的装甲几何切面与红黑配色，配备多时区显示功能与蝙蝠徽造型表盒。",
      },
      {
        id: "fossil-batman",
        name: "Fossil × The Batman 胶囊自动机械表",
        nameEn: "Fossil x The Batman Capsule Collection Watch",
        maker: "Fossil · 限量自动机械表",
        year: "2022",
        spec: "42mm 黑电镀不锈钢 · 自动机械机芯 · 四条快拆表带",
        image: "/media/merch/fossil-batman.jpg",
        imageAlt: "Fossil 自动机械表与收纳盒及可替换表带",
        body: "Fossil 推出的限量版自动机械腕表（型号 LE1142SET）。42 毫米黑离子电镀不锈钢表壳，半镂空表盘饰有蝙蝠徽记，透底后盖可观赏红色自动陀；随附四条快拆战术表带及抽屉式陈列收纳盒。",
      },
      {
        id: "secretlab-batman",
        name: "Secretlab TITAN Evo 2022 联名电竞椅",
        nameEn: "Secretlab TITAN Evo 2022 The Batman Edition",
        maker: "Secretlab · 圣临电竞",
        year: "2022",
        spec: "TITAN Evo 旗舰人体工学 · 磁吸可拆卸蝙蝠徽",
        image: "/media/merch/secretlab-batman.jpg",
        imageAlt: "Secretlab TITAN Evo 2022 电影联名椅",
        body: "Secretlab 推出的 TITAN Evo 电影联名人体工学电竞椅。靠背磁吸附带有可拆卸的电影版蝙蝠徽金属件，椅身皮革采用战衣同款编织压纹与暗红滚边缝线。",
      },
      {
        id: "puma-batman",
        name: "PUMA × The Batman 运动鞋与机能服饰",
        nameEn: "PUMA x The Batman Collection",
        maker: "PUMA · 彪马",
        year: "2022",
        spec: "Suede / RS-X / Mayze 等联名鞋款及服饰",
        image: "/media/merch/puma-batman.jpg",
        imageAlt: "PUMA 联名 Suede Classic 等鞋款与服装",
        body: "PUMA 与电影联名推出的运动鞋服系列。涵盖 Suede Classic（后跟饰有蝙蝠群压纹）、RS-X 及 Mayze 等经典鞋型，整体设计采用电影标志性的黑红暗黑机能配色。",
      },
    ],
  },
  {
    id: "print",
    kicker: "07",
    title: "出版书籍",
    titleEn: "Books & Comics",
    intro:
      "收录官方艺术设定集、前传小说以及主演保罗·达诺亲笔编剧的衍生漫画，作为深入了解电影世界观与视觉设计的实体文献。",
    items: [
      {
        id: "artbook",
        name: "《新蝙蝠侠》官方艺术设定集",
        nameEn: "The Art of The Batman",
        maker: "Abrams Books · 詹姆斯·菲尔德 著",
        year: "2022",
        spec: "精装大开本 · 全彩印刷",
        image: "/media/merch/artbook.jpg",
        imageAlt: "《The Art of The Batman》精装设定集封面",
        body: "导演马特·里夫斯亲笔作序。全书收录数百张前期概念设计图、分镜头脚本、服装道具分解图与主创专访，详细记录了新哥谭视觉构建的全过程。",
      },
      {
        id: "novel",
        name: "官方前传小说《蝙蝠侠之前》",
        nameEn: "Before the Batman: An Original Movie Novel",
        maker: "Random House · 大卫·卢曼 著",
        year: "2022",
        spec: "平装单行本 · 附彩插海报",
        image: "/media/merch/novel.jpg",
        imageAlt: "前传小说 Before the Batman 官方封面",
        body: "官方授权前传衍生读物，重点讲述布鲁斯·韦恩早年改装肌肉战车、接受体能训练，以及爱德华·纳什顿在孤儿院萌生仇恨的起源故事。",
      },
      {
        id: "riddler-book",
        name: "官方前传漫画《谜语人元年》",
        nameEn: "The Riddler: Year One",
        maker: "DC Black Label · 保罗·达诺 编剧",
        year: "2022–2023",
        spec: "6 期限定漫画单行本",
        image: "/media/merch/riddler-book.jpg",
        imageAlt: "《The Riddler: Year One》漫画封面",
        body: "由电影谜语人饰演者保罗·达诺亲自编剧、DC Black Label 出版的成人向限定漫画，以司法会计视角展现了「新生」基金贪腐黑幕与谜语人的黑化历程。",
      },
    ],
  },
  {
    id: "media",
    kicker: "08",
    title: "影音与原声",
    titleEn: "Home Video & Soundtrack",
    intro:
      "包含 4K UHD 超高清蓝光光碟、标准蓝光碟片，以及迈克尔·吉亚奇诺创作的原声大碟与限量黑胶唱片。",
    items: [
      {
        id: "uhd",
        name: "《新蝙蝠侠》4K Ultra HD 收藏版",
        nameEn: "The Batman 4K Ultra HD + Blu-ray",
        maker: "Warner Bros. Home Entertainment",
        year: "2022",
        spec: "4K UHD + 蓝光双碟 · 杜比视界 / 杜比全景声",
        image: "/media/merch/uhd.jpg",
        imageAlt: "《新蝙蝠侠》4K Ultra HD 官方包装封面",
        body: "搭载原生 4K 超高清画质、杜比视界（Dolby Vision）HDR 及杜比全景声音轨，准确还原摄影师格雷格·弗雷泽（Greig Fraser）标志性的高反差光影与雨夜质感，附带两小时幕后花絮。",
      },
      {
        id: "bluray",
        name: "《新蝙蝠侠》蓝光标准版",
        nameEn: "The Batman Blu-ray Edition",
        maker: "Warner Bros. Home Entertainment",
        year: "2022",
        spec: "1080P 全高清蓝光碟",
        image: "/media/merch/bluray.jpg",
        imageAlt: "《新蝙蝠侠》蓝光标准版封面",
        body: "面向大众影迷的标准蓝光光盘，收录电影正片、主创访谈以及阿卡姆疯人院删减片段等收录内容。",
      },
      {
        id: "ost",
        name: "电影官方原声大碟 (OST)",
        nameEn: "Original Motion Picture Soundtrack",
        maker: "WaterTower Music · 迈克尔·吉亚奇诺 作曲",
        year: "2022",
        spec: "数字流媒体 / 双 CD / 限量黑胶唱片",
        image: "/media/merch/ost.jpg",
        imageAlt: "电影官方原声大碟封面",
        body: "奥斯卡获奖作曲家迈克尔·吉亚奇诺（Michael Giacchino）操刀配乐。以厚重低沉的四音符铜管旋律与阴郁弦乐交织，塑造出极具辨识度的新一代蝙蝠侠音乐主题。",
      },
    ],
  },
  {
    id: "posters",
    kicker: "09",
    title: "艺术海报与丝网印",
    titleEn: "Official Posters & Prints",
    intro:
      "收录影院限定实体印刷海报、Mondo 限量艺术丝网版画及收藏级挂画（均为实体纸质印品，非数字宣发物料）。",
    items: [
      {
        id: "poster-mondo",
        name: "Mondo 官方授权限量丝网海报",
        nameEn: "The Batman Screenprinted Poster by Mondo",
        maker: "Mondo · 弗朗切斯科·弗兰卡维拉 绘",
        year: "2022",
        spec: "24×36 英寸 · 手工丝网印刷 · 限时预售",
        image: "/media/merch/poster-mondo.jpg",
        imageAlt: "Mondo 官方丝网印刷海报，红黑主色调",
        body: "插画师弗朗切斯科·弗兰卡维拉（Francesco Francavilla）受 Mondo 邀请绘制。以红黑双色勾勒出雨夜中喷射尾焰的蝙蝠战车与义警身影，呈现复古新黑色漫画质感。",
      },
      {
        id: "poster-mondo-var",
        name: "Mondo 限量变体版丝网海报",
        nameEn: "The Batman Variant Screenprint",
        maker: "Mondo · 弗朗切斯科·弗兰卡维拉 绘",
        year: "2022",
        spec: "24×36 英寸 · 限量 325 张",
        image: "/media/merch/poster-mondo-var.jpg",
        imageAlt: "Mondo 变体版海报，红雨与蝙蝠头套特写",
        body: "限量变体版本，全球限量印制 325 张。画面采用特写构图，聚焦于暴雨中蝙蝠侠头套与红光映照下的侧脸，是备受推崇的收藏级纸质版画。",
      },
      {
        id: "poster-imax",
        name: "IMAX 官方专属限定海报",
        nameEn: "IMAX Exclusive Poster Art",
        maker: "IMAX · 比尔·辛凯维奇 绘",
        year: "2022",
        spec: "IMAX 专属影院特制实体印刷品",
        image: "/media/merch/poster-imax.jpg",
        imageAlt: "比尔·辛凯维奇绘制的 IMAX 艺术海报",
        body: "由知名漫画艺术家比尔·辛凯维奇（Bill Sienkiewicz）绘制。以红色蝙蝠轮廓为基底，融合了谜语人、猫女、企鹅人与戈登等主要角色的拼贴画风，极具视觉张力。",
      },
      {
        id: "poster-dolby",
        name: "杜比影院 (Dolby Cinema) 专属海报",
        nameEn: "Dolby Cinema Exclusive Poster",
        maker: "Dolby Cinema",
        year: "2022",
        spec: "杜比影院专享收藏海报",
        image: "/media/merch/poster-dolby.jpg",
        imageAlt: "杜比影院专属海报，蝙蝠灯光芒下的背影",
        body: "杜比影院实体宣传海报。蝙蝠侠背对镜头伫立在夜雨中，身后探照灯射出强光打在夜空，画面融入了杜比标志性的「D」字母外框设计。",
      },
      {
        id: "poster-wall",
        name: "「揭开真相」经典公映海报挂画",
        nameEn: "Unmask the Truth 24×36 Poster",
        maker: "Trends International",
        year: "2022",
        spec: "24×36 英寸标准挂画",
        image: "/media/merch/poster-wall.jpg",
        imageAlt: "装裱在画框中的「揭开真相」官方海报",
        body: "公映期间流传广泛的官方主视觉海报：红字问号与密电符号涂鸦覆盖在蝙蝠侠面庞之上，呼应全片侦探解谜的核心叙事。",
      },
      {
        id: "poster-rays",
        name: "「破晓微光」官方艺术挂画",
        nameEn: "Rays of Light Art Print",
        maker: "Trends International / Pyramid",
        year: "2022",
        spec: "24×36 英寸胶印挂画",
        image: "/media/merch/poster-rays.jpg",
        imageAlt: "蝙蝠侠伫立于束光之下的艺术挂画",
        body: "经典零售海报版本，蝙蝠侠伫立在一束垂直顶光之中，红黑渐变背景彰显出孤独守护者的沉稳气质。",
      },
    ],
  },
];

export const MERCH_TEASERS = [MERCH[0].items[0], MERCH[1].items[0], MERCH[2].items[0]];
