export type MerchCover = {
  id: string;
  title: string;
  issue: string;
  coverArtist: string;
  releaseDate: string;
  iso: string;
  image: string;
  imageAlt: string;
  variantType: "movie" | "cinema-exclusive" | "film-inspiration";
};

export type MerchItem = {
  id: string;
  name: string;
  nameEn: string;
  maker: string;
  year: string;
  spec: string;
  image: string;
  imageAlt: string;
  body: string;
  sourceUrl?: string;
  sourceLabel?: string;
  sourceTier?: "official" | "press" | "set" | "archive";
  verifiedAt?: string;
  covers?: MerchCover[];
};

export type MerchGroup = {
  id: string;
  kicker: string;
  title: string;
  titleEn: string;
  intro: string;
  items: MerchItem[];
};

export const THE_BATMAN_MOVIE_VARIANTS: MerchCover[] = [
  {
    id: "movie-variant-batman-121",
    title: "Batman #121",
    issue: "#121",
    coverArtist: "Lee Bermejo",
    releaseDate: "2022.03.01",
    iso: "2022-03-01",
    image: "/media/merch/comics/the-batman-variants/batman-121-bermejo.jpg",
    imageAlt:
      "Lee Bermejo 为 Batman #121 绘制的《新蝙蝠侠》电影变体封面：雨夜石像鬼旁的电影版蝙蝠侠",
    variantType: "movie",
  },
  {
    id: "movie-variant-killing-time-1",
    title: "Batman: Killing Time #1",
    issue: "#1",
    coverArtist: "Carlos D’Anda",
    releaseDate: "2022.03.01",
    iso: "2022-03-01",
    image: "/media/merch/comics/the-batman-variants/killing-time-1-danda.jpg",
    imageAlt:
      "Carlos D’Anda 为 Batman: Killing Time #1 绘制的电影变体封面：电影版蝙蝠侠骑在蝙蝠摩托上",
    variantType: "movie",
  },
  {
    id: "movie-variant-batgirls-4",
    title: "Batgirls #4",
    issue: "#4",
    coverArtist: "Jonboy Meyers",
    releaseDate: "2022.03.08",
    iso: "2022-03-08",
    image: "/media/merch/comics/the-batman-variants/batgirls-4-meyers.jpg",
    imageAlt:
      "Jonboy Meyers 为 Batgirls #4 绘制的电影变体封面：电影版蝙蝠侠与侧翻的蝙蝠摩托",
    variantType: "movie",
  },
  {
    id: "movie-variant-detective-1056",
    title: "Detective Comics #1056",
    issue: "#1056",
    coverArtist: "Puppeteer Lee",
    releaseDate: "2022.03.08",
    iso: "2022-03-08",
    image: "/media/merch/comics/the-batman-variants/detective-1056-puppeteer-lee.jpg",
    imageAlt:
      "Puppeteer Lee 为 Detective Comics #1056 绘制的电影变体封面：蝙蝠侠立在蝙蝠战车引擎盖上",
    variantType: "movie",
  },
  {
    id: "movie-variant-the-knight-3",
    title: "Batman: The Knight #3",
    issue: "#3",
    coverArtist: "Rafael Albuquerque",
    releaseDate: "2022.03.08",
    iso: "2022-03-08",
    image: "/media/merch/comics/the-batman-variants/the-knight-3-albuquerque.jpg",
    imageAlt:
      "Rafael Albuquerque 为 Batman: The Knight #3 绘制的电影变体封面：红黑对比的电影版蝙蝠侠近景",
    variantType: "movie",
  },
  {
    id: "movie-variant-catwoman-41",
    title: "Catwoman #41",
    issue: "#41",
    coverArtist: "Jenny Frison",
    releaseDate: "2022.03.15",
    iso: "2022-03-15",
    image: "/media/merch/comics/the-batman-variants/catwoman-41-frison.jpg",
    imageAlt:
      "Jenny Frison 为 Catwoman #41 绘制的电影变体封面：电影版猫女手持自行车链条",
    variantType: "movie",
  },
  {
    id: "movie-variant-justice-league-74",
    title: "Justice League #74",
    issue: "#74",
    coverArtist: "Ben Oliver",
    releaseDate: "2022.03.15",
    iso: "2022-03-15",
    image: "/media/merch/comics/the-batman-variants/justice-league-74-oliver.jpg",
    imageAlt:
      "Ben Oliver 为 Justice League #74 绘制的电影变体封面：电影版蝙蝠侠立于蝙蝠战车前",
    variantType: "movie",
  },
  {
    id: "movie-variant-nightwing-90",
    title: "Nightwing #90",
    issue: "#90",
    coverArtist: "Riccardo Federici",
    releaseDate: "2022.03.15",
    iso: "2022-03-15",
    image: "/media/merch/comics/the-batman-variants/nightwing-90-federici.jpg",
    imageAlt:
      "Riccardo Federici 为 Nightwing #90 绘制的电影变体封面：电影版蝙蝠侠、谜语人面具与蝙蝠战车",
    variantType: "movie",
  },
  {
    id: "movie-variant-harley-13",
    title: "Harley Quinn #13",
    issue: "#13",
    coverArtist: "Simone Bianchi",
    releaseDate: "2022.03.22",
    iso: "2022-03-22",
    image: "/media/merch/comics/the-batman-variants/harley-quinn-13-bianchi.jpg",
    imageAlt:
      "Simone Bianchi 为 Harley Quinn #13 绘制的电影变体封面：蝙蝠侠、猫女、谜语人与企鹅人拼贴成蝙蝠徽，压在哥谭天际线上",
    variantType: "movie",
  },
];

export const MERCH: MerchGroup[] = [
  {
    id: "figures",
    kicker: "01",
    title: "可动人偶",
    titleEn: "Action Figures",
    intro:
      "收录官方授权的 1/6 收藏级可动、1/12 日系与美系小比例可动、1/9 中档量产与 7 寸零售可动，注重头雕还原、战衣剪裁与把玩配件。涵盖 7 寸至 12 寸高可动精品。",
    items: [
      {
        id: "inart-action",
        name: "INART Action 1/12 蝙蝠侠可动人偶",
        nameEn: "The Batman Action Figure (Hg M0006)",
        maker: "INART Action",
        year: "2026",
        spec: "约 1/12 比例 · 全高约 16.2 cm · 预订，预计 2026 年第四季出货",
        image: "/media/merch/inart-action.jpg",
        imageAlt: "INART Action 1/12 电影版蝙蝠侠可动人偶官方产品图，戴头套全身站姿",
        body: "INART 小比例线 INART Action 推出的华纳授权电影版蝙蝠侠。三款头雕（戴面罩平静、戴面罩愤怒、露脸布鲁斯），可替换胸甲，十三只手型，铁丝布料披风。配件含空头套、抓钩发射器开合两态、黏弹枪、肾上腺素、手电筒、紫外灯、笔记本电脑与两款蝙蝠镖。含地台约 15×15×16.9 cm。",
        sourceUrl: "https://global.inart.studio/products/the-batman-batman-action-figure",
        sourceLabel: "INART 官方产品页",
        sourceTier: "official",
        verifiedAt: "2026.09.08",
      },
      {
        id: "lpzz",
        name: "良品制造 1/12 蝙蝠侠可动人偶",
        nameEn: "The Batman (2022) 1/12 Scale (DC007)",
        maker: "良品制造 · U-P-Finegures / LPZZ",
        year: "2026",
        spec: "1/12 比例 · 编号 DC007 · 预订，预计 2026 年第四季出货",
        image: "/media/merch/lpzz.jpg",
        imageAlt: "良品制造 1/12 电影版蝙蝠侠可动人偶，露脸头雕与战术配件",
        body: "良品制造（U-P-Finegures，亦称 LPZZ）1/12 比例电影造型。露脸布鲁斯头雕、空头套、十二只手型。配件含三款蝙蝠镖、撬具、手铐、手持电脑、抓钩枪两把、抓钩、肾上腺素、手电筒、紫外灯、信号棒与黏弹枪，另附支架与地台。战衣按第一部多层战术甲还原。图为开发样板，成品以出货为准。",
        sourceUrl: "https://onesixthoutfitters.com/lpzz-dc007-1-12-scale-the-batman-2022-batman-figure/",
        sourceLabel: "经销商产品页",
        verifiedAt: "2026.09.08",
      },
      {
        id: "mafex",
        name: "MAFEX No.188 电影版蝙蝠侠",
        nameEn: "MAFEX No.188 THE BATMAN",
        maker: "Medicom Toy · 株式会社メディコム・トイ",
        year: "2023",
        spec: "全高约 160 mm · 布制可动披风 · 头部零件 4 种",
        image: "/media/merch/mafex.jpg",
        imageAlt: "MAFEX No.188 电影版蝙蝠侠可动人偶，举起抓钩发射器的官方产品图",
        body: "Medicom Toy マフェックス线推出的华纳授权电影造型。全高约 160 毫米，头部原型岛崎恭一、本体 PERFECT-STUDIO。附头部零件 4 种、内置铁丝的布制披风、剧中武器零件与可动支架，可摆出电影动作场面。2023 年 10 月日本发售，后有再版。与 INART Action、良品制造同属 1/12 左右收藏线。",
        sourceUrl: "https://www.1999.co.jp/10905264",
        sourceLabel: "Hobby Search 产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "shf",
        name: "S.H.Figuarts 蝙蝠侠「世界最高的侦探」",
        nameEn: "S.H.Figuarts Batman “The World's Greatest Detective”",
        maker: "BANDAI SPIRITS · 魂ウェブ / TAMASHII NATIONS STORE",
        year: "2024",
        spec: "全高约 160 mm · 魂ストア限定 · 布制披风",
        image: "/media/merch/shf.jpg",
        imageAlt: "S.H.Figuarts 魂ストア限定电影版蝙蝠侠，布披风与战术甲官方产品图",
        body: "2024 年 11 月 15 日发售的 TAMASHII NATIONS STORE 限定版，比早期店售 SHF 更贴近剧中配色。PVC／ABS／布制，全高约 160 毫米。套装含本体、可替换胸甲、左右各 5 种手型、左右抓钩发射器与 Bat Knife；披风内置铁丝，可做出被风掀起的姿态。",
        sourceUrl: "https://tamashiiweb.com/item/15022/",
        sourceLabel: "魂ウェブ官方产品页",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "mezco",
        name: "Mezco One:12 Collective 电影版蝙蝠侠",
        nameEn: "One:12 Collective The Batman",
        maker: "Mezco Toyz",
        year: "2022",
        spec: "约 17 cm · 30 处以上可动 · 4 款头雕",
        image: "/media/merch/mezco.jpg",
        imageAlt: "Mezco One:12 Collective 电影版蝙蝠侠全身站姿与布披风官方产品图",
        body: "Mezco 软服路线的 1/12 集体系列。约 17 厘米，超过 30 处关节，四款头雕含罗伯特·帕丁森露脸布鲁斯。战衣含铁丝披风、可拆翼装、护臂、工具腰带与大腿袋。配件含黏弹发射器、蝙蝠镖、手铐、紫外灯、收放两态抓钩、肾上腺素、烟雾弹等，是与 MAFEX、SHF 硬塑路线对照的代表性电影授权款。",
        sourceUrl: "https://www.mezcotoyz.com/one-12-collective-the-batman",
        sourceLabel: "Mezco Toyz 官方产品页",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "dah117",
        name: "Beast Kingdom DAH-117 电影版蝙蝠侠",
        nameEn: "Dynamic 8ction Heroes DAH-117 Batman (The Batman)",
        maker: "Beast Kingdom · 野獸國",
        year: "2025",
        spec: "1/9 比例 · 全高约 21 cm · 约 22 处可动",
        image: "/media/merch/dah117.jpg",
        imageAlt: "Beast Kingdom DAH-117 电影版蝙蝠侠可动人偶官方宣传图",
        body: "台湾野獸國 Dynamic 8ction Heroes 中档量产线。全高约 21 厘米、约 22 处关节，布制披风，头雕按帕丁森面容塑造。配件含三组替换手型、蝙蝠镖，以及收起／展开两态抓钩发射器。日本地区 2025 年 2 月发售，包装纪念蝙蝠侠八十五周年。补上 2022 高端线之外的中档授权可动。",
        sourceUrl: "https://beast-kingdom.us/dah-117-batman-the-batman.html",
        sourceLabel: "Beast Kingdom 官方产品页",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "inart",
        name: "INART 1/6 蝙蝠侠珍藏人偶",
        nameEn: "The Batman 1/6 Collectible Figure",
        maker: "INART · Queen Studios",
        year: "2023",
        spec: "1/6 比例 · 常规版 / 植发豪华版",
        image: "/media/merch/inart.jpg",
        imageAlt: "INART 1/6 蝙蝠侠全身官方产品展示图",
        body: "Queen Studios 旗下高端可动厂牌 INART 出品。配备独立可动眼球系统与多款替换表情，豪华版特别附带手工植发头雕。战衣严格按照电影多层结构剪裁制作，细致还原防弹护甲与布料质感。",
        sourceUrl: "https://queenstudios.shop/products/batman-1-6-collectible-figure",
        sourceLabel: "Queen Studios / INART 产品页",
        sourceTier: "official",
        verifiedAt: "2026.08.24",
      },
      {
        id: "hottoys",
        name: "Hot Toys 蝙蝠侠与蝙蝠信号灯套装",
        nameEn: "Batman and Bat-Signal Set",
        maker: "Hot Toys",
        year: "2022",
        spec: "1/6 比例 · MMS641 豪华套装",
        image: "/media/merch/hottoys.jpg",
        imageAlt: "Hot Toys 1/6 蝙蝠侠站在点亮的蝙蝠信号灯旁",
        body: "Hot Toys 推出的 1/6 比例人偶套装。配备全新开发的面罩头雕与可替换下半脸造型，豪华版特别附带可通电发光的 1/6 蝙蝠信号灯地台，以及抓钩枪、战术飞镖等武器配件。",
      },
      {
        id: "mcfarlane-batman",
        name: "麦克法兰 7 寸战衣版蝙蝠侠",
        nameEn: "Batman (The Batman) DC Multiverse",
        maker: "McFarlane Toys",
        year: "2022",
        spec: "7 寸比例 · 约 22 处可动",
        image: "/media/merch/mcfarlane-batman.jpg",
        imageAlt: "McFarlane 7 寸电影战衣版蝙蝠侠可动人偶",
        body: "DC Multiverse 电影第一波零售可动。7 寸比例、Ultra Articulation 约 22 处关节，按第一部战术甲与头套还原。与未戴面罩布鲁斯、谜语人、企鹅人、猫女同属 2022 年电影量产阵容。",
      },
      {
        id: "mcfarlane-bruce",
        name: "麦克法兰 7 寸未戴面罩布鲁斯·韦恩",
        nameEn: "Bruce Wayne Unmasked (The Batman)",
        maker: "McFarlane Toys",
        year: "2022",
        spec: "7 寸比例可动人偶",
        image: "/media/merch/mcfarlane-bruce.jpg",
        imageAlt: "McFarlane 7 寸未戴面罩布鲁斯人偶包装与配件",
        body: "DC Multiverse 第二波推出的便装／头套掀起造型。还原帕丁森版布鲁斯的眼妆与战术甲，约 22 处可动，附蝙蝠镖与地台。官方产品页标注为 Batman Unmasked (The Batman)。",
        sourceUrl: "https://mcfarlane.com/toys/batman-unmasked-batman/",
        sourceLabel: "McFarlane Toys 官方产品页",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "mcfarlane-riddler",
        name: "麦克法兰 7 寸谜语人",
        nameEn: "The Riddler – The Batman (Movie)",
        maker: "McFarlane Toys",
        year: "2022",
        spec: "7 寸比例 · 约 22 处可动 · 附破冰锥",
        image: "/media/merch/mcfarlane-riddler.jpg",
        imageAlt: "McFarlane 电影版谜语人冬装造型官方产品图",
        body: "按保罗·达诺在电影中的战斗服与雨衣造型制作。7 寸、约 22 处可动，配件为破冰锥（ice picker）与地台，附角色收藏卡。与雕像区的 1/6 树脂谜语人是同一角色的不同产品线。",
        sourceUrl: "https://mcfarlane.com/toys/riddler-the-batman-movie/",
        sourceLabel: "McFarlane Toys 官方产品页",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "mcfarlane-penguin",
        name: "麦克法兰 7 寸企鹅人",
        nameEn: "The Penguin (The Batman)",
        maker: "McFarlane Toys",
        year: "2022",
        spec: "7 寸比例 · 约 22 处可动",
        image: "/media/merch/mcfarlane-penguin.jpg",
        imageAlt: "McFarlane 7 寸电影版企鹅人可动人偶，科林·法瑞尔造型",
        body: "按科林·法瑞尔在冰山俱乐部时期的企鹅人还原。7 寸、约 22 处可动，附替换手型与地台，以及正面摄影、背面角色小传的收藏卡。官方产品页将他写作 Oswald Cobblepot，Gotham 夜场老板。",
        sourceUrl: "https://mcfarlane.com/toys/the-penguin/",
        sourceLabel: "McFarlane Toys 官方产品页",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "mcfarlane-catwoman",
        name: "麦克法兰 7 寸猫女（含未戴面罩版）",
        nameEn: "Catwoman / Catwoman Unmasked (The Batman)",
        maker: "McFarlane Toys",
        year: "2022",
        spec: "7 寸比例 · 约 22 处可动 · 戴面罩版与 Unmasked 版",
        image: "/media/merch/mcfarlane-catwoman.jpg",
        imageAlt: "McFarlane 7 寸电影版猫女未戴面罩可动人偶官方产品图",
        body: "麦克法兰推出的电影版猫女 7 寸可动人偶，涵盖戴面罩潜行战衣款与佐伊·克罗维兹露脸（Unmasked）双版本，均具备约 22 处可动关节，附带皮鞭武器与专属收藏角色卡。",
        sourceUrl: "https://www.bigbadtoystore.com/product/batman-dc-multiverse-catwoman-unmasked-action-figure-100268",
        sourceLabel: "BigBadToyStore 产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "funko",
        name: "Funko Pop! 电影全套乙烯玩偶",
        nameEn: "Pop! Movies · The Batman Series",
        maker: "Funko",
        year: "2022",
        spec: "乙烯公仔 · 包含常规款与 Rides 战车款",
        image: "/media/merch/funko.jpg",
        imageAlt: "Funko 官方公布的《新蝙蝠侠》全套 Pop! 玩偶",
        body: "Funko 官方授权系列，以经典 Q 版大头造型重塑了蝙蝠侠、猫女、企鹅人、谜语人以及驾驶蝙蝠战车的 Pop! Rides 系列，是流传广泛的流行文化收藏品。",
      },
    ],
  },
  {
    id: "props",
    kicker: "02",
    title: "电影道具复刻",
    titleEn: "Prop Replicas",
    intro:
      "基于华纳兄弟制片团队的原始数字模型与道具原件扫描数据打造的金属道具复刻，含 1:1 限量件与同系列缩比陈列版。",
    items: [
      {
        id: "fe-batarang",
        name: "Factory Entertainment 1:1 金属蝙蝠飞镖",
        nameEn: "The Batman Batarang Limited Edition Prop Replica",
        maker: "Factory Entertainment · 华纳官方授权",
        year: "2022",
        spec: "1:1 比例 · 实心压铸金属 · 钢琴烤漆亚克力展示盒",
        image: "/media/merch/fe-batarang.jpg",
        imageAlt: "Factory Entertainment 1:1 蝙蝠飞镖金属复刻道具与展示盒",
        body: "根据《新蝙蝠侠》制片组提供的原始数字资产打造。全尺寸纯金属铸造，表面施以手工战损与做旧效果，还原大银幕质感；附带专属编号金属铭牌与展示盒。",
        sourceUrl: "https://factoryent.com/products/the-batman-batarang-limited-edition-prop-replica",
        sourceLabel: "Factory Entertainment 产品页",
        sourceTier: "official",
        verifiedAt: "2026.08.24",
      },
      {
        id: "fe-batarang-scaled",
        name: "Factory Entertainment 缩比金属蝙蝠飞镖",
        nameEn: "The Batman Batarang Scaled Prop Replica",
        maker: "Factory Entertainment · 华纳官方授权",
        year: "2022",
        spec: "全长约 7 英寸 · 实心金属 · 附展示架",
        image: "/media/merch/fe-batarang-scaled.jpg",
        imageAlt: "Factory Entertainment 7 英寸缩比金属蝙蝠飞镖与展示架",
        body: "Factory Entertainment 推出的 7 英寸缩比金属飞镖道具复刻。全长约 18 厘米，采用实心金属合金精密铸造，配有专属陈列支架与收藏级包装盒，兼具精致质感与轻巧体量。",
        sourceUrl: "https://factoryent.com/products/the-batman-batarang-scaled-prop-replica",
        sourceLabel: "Factory Entertainment 产品页",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "paragon-glyph",
        name: "Paragon FX 1:1 胸甲可拆卸金属蝙蝠徽标",
        nameEn: "The Batman 2022 Bat Glyph 1:1 Metal Prop Replica",
        maker: "Paragon FX Group · 华纳官方授权",
        year: "2022",
        spec: "1:1 全尺寸 · 纯金属实心铸造 · 全球限量 750 件",
        image: "/media/merch/paragon-glyph.jpg",
        imageAlt: "Paragon FX 1:1 金属蝙蝠徽标双面与展开形态",
        body: "由 Paragon 依据电影道具原件 STL 文件 1:1 打造。全金属实心结构，忠实还原了胸甲徽记表面的细微机械纹理，并可按电影设定拆卸展开为双刃折叠战术刀。",
        sourceUrl: "https://paragonfxgroup.com/products/thebatman2022",
        sourceLabel: "Paragon FX 产品页",
        sourceTier: "official",
        verifiedAt: "2026.08.24",
      },
      {
        id: "fe-grapnel",
        name: "Factory Entertainment 1:1 战术抓钩发射器",
        nameEn: "The Batman Grapple Launcher 1:1 Life-Size Prop Replica",
        maker: "Factory Entertainment · 华纳官方授权",
        year: "2022",
        spec: "1:1 比例 · 全金属铸造 · 全球限量 1500 件",
        image: "/media/merch/fe-grapnel.jpg",
        imageAlt: "Factory Entertainment 1:1 战术抓钩枪实物展示",
        body: "全尺寸 1:1 电影实体道具复刻，尺寸约 10×21×5 厘米。采用实心合金精密压铸，细致呈现了钢缆线轴、握把机械制动结构与战损涂装，配有展示盒与独立编号收藏证书。",
        sourceUrl: "https://factoryent.com/products/the-batman-grapple-launcher-limited-edition-prop-replica",
        sourceLabel: "Factory Entertainment 产品页",
        sourceTier: "official",
        verifiedAt: "2026.08.24",
      },
    ],
  },
  {
    id: "statues",
    kicker: "03",
    title: "高端雕像",
    titleEn: "Statues",
    intro:
      "收录 1:1 等身硅胶胸像、博物馆级宝丽石全身像，以及 1/10、1/6 与 12 寸零售雕像，覆盖高端巨物到电影宣传视觉实体化。",
    items: [
      {
        id: "infinity-bust",
        name: "Infinity Studio 1:1 蝙蝠侠等身胸像",
        nameEn: "The Batman Life-Size Bust",
        maker: "Infinity Studio · 开天工作室 × Penguin Toys",
        year: "2022",
        spec: "1:1 等身 · 高约 93 cm · 全球限量 500 尊",
        image: "/media/merch/infinity-bust.jpg",
        imageAlt: "Infinity Studio 《新蝙蝠侠》1:1 等身胸像，滴水兽地台",
        body: "由开天工作室（Infinity Studio）与 Penguin Toys 联合打造。采用铂金硅胶头雕与医用级硅胶皮肤，战衣使用真皮与定制织物。全高约 93 厘米，地台按电影视觉做成哥谭滴水兽建筑，滴水兽可磁吸拆卸单独展示。全球限量 500 尊。",
        sourceUrl: "https://www.sideshow.com/collectibles/dc-comics-batman-infinity-studio-infinity-studio-910677",
        sourceLabel: "Sideshow 产品页",
        sourceTier: "official",
        verifiedAt: "2026.08.24",
      },
      {
        id: "p1s",
        name: "Prime 1 Studio 1/3 博物馆级电影版蝙蝠侠",
        nameEn: "Museum Masterline × Blitzway",
        maker: "Prime 1 Studio × Blitzway",
        year: "2023",
        spec: "1/3 比例 · 高约 79 cm · 高级宝丽石树脂",
        image: "/media/merch/p1s.jpg",
        imageAlt: "Prime 1 Studio 与 Blitzway 合作的 1/3 蝙蝠侠全身雕像",
        body: "由 Prime 1 Studio 与 Blitzway 联手打造。全高约 79 厘米，细致还原了皮革纹理、硬质防弹板与金属磨损细节，准确再现帕丁森在电影中的冷峻神态。",
      },
      {
        id: "p1s-sae",
        name: "Prime 1 Studio 特殊艺术限定版雕像",
        nameEn: "Special Art Edition Deluxe",
        maker: "Prime 1 Studio",
        year: "2022",
        spec: "1/3 比例 · 高约 88 cm · 限量发行",
        image: "/media/merch/p1s-sae.jpg",
        imageAlt: "Prime 1 Studio 特殊艺术版红雨灯光效果全身雕像",
        body: "以传奇漫画家吉姆·李（Jim Lee）为 DC FanDome 创作的概念插画为灵感，结合电影实拍装甲细节，地台融合了哥谭标志性滴水兽雕塑与红雨氛围灯效。",
      },
      {
        id: "iron-studios",
        name: "Iron Studios Art Scale 1/10 电影版蝙蝠侠",
        nameEn: "The Batman Art Scale 1/10",
        maker: "Iron Studios",
        year: "2022",
        spec: "1/10 比例 · 高约 26 cm · 宝丽石手绘",
        image: "/media/merch/iron-studios.jpg",
        imageAlt: "Iron Studios 1/10 电影版蝙蝠侠雕像，战术甲与哥谭建筑地台",
        body: "按 2022 年电影战术甲制作的 Art Scale 1/10。Sideshow 公布全高约 10.2 英寸（约 26 厘米），宝丽石手绘，地台做成哥谭混凝土建筑并带蝙蝠徽。Prime 1 / Infinity 是万元级巨物，这一档把中小比例雕像补进档案。",
        sourceUrl: "https://www.sideshow.com/collectibles/dc-comics-the-batman-iron-studios-910601",
        sourceLabel: "Sideshow 产品页",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "mcfarlane-gold",
        name: "麦克法兰 12 寸 Gold Label 摆件雕像",
        nameEn: "The Batman 12″ Posed Statue (Gold Label)",
        maker: "McFarlane Toys · DC Multiverse",
        year: "2022",
        spec: "12 寸摆件 · 红黑 Jim Lee 海报配色 · 滴水兽地台",
        image: "/media/merch/mcfarlane-gold.jpg",
        imageAlt: "McFarlane Gold Label 12 寸电影版蝙蝠侠雕像，红黑配色与滴水兽地台",
        body: "按吉姆·李为电影绘制的红黑宣传海报配色，而不是写实战衣涂装。12 寸摆件（非可动），附滴水兽地台、风格化背景板，以及正反面收藏卡。接近「电影宣传视觉实体化」，体量低于 Prime 1，更适合作为档案向展品。",
        sourceUrl: "https://mcfarlane.com/toys/batman-12-posed-statue-gold-label/",
        sourceLabel: "McFarlane Toys 官方产品页",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "mcfarlane-riddler-statue",
        name: "麦克法兰 DC Direct 1/6 谜语人树脂像",
        nameEn: "The Riddler 1:6 Resin Statue (The Batman)",
        maker: "McFarlane Toys · DC Direct",
        year: "2022",
        spec: "1/6 树脂雕像 · 电影 Logo 地台",
        image: "/media/merch/mcfarlane-riddler-statue.jpg",
        imageAlt: "McFarlane DC Direct 1/6 电影版谜语人树脂雕像与包装",
        body: "按电影谜语人服装制作的 1/6 树脂像，电影 Logo 直接作为底座。雕像区此前几乎全是蝙蝠侠，这一尊把达诺版谜语人补进陈列。与 7 寸可动是同一造型的不同产品，DC Direct 系列包装。",
        sourceUrl: "https://mcfarlane.com/toys/riddler-16-resin-statue-batman/",
        sourceLabel: "McFarlane Toys 官方产品页",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
    ],
  },
  {
    id: "vehicles",
    kicker: "04",
    title: "车模与遥控载具",
    titleEn: "Vehicles",
    intro:
      "涵盖合金车模、遥控车、1/6 收藏级战车与蝙蝠摩托，重现美式改装肌肉车底盘、外露涡轮引擎与电影另一台关键载具。",
    items: [
      {
        id: "hotwheels-rc",
        name: "Hot Wheels R/C 1:10 电影蝙蝠战车",
        nameEn: "The Batman The Original Batmobile (HCD19)",
        maker: "Hot Wheels R/C · 美泰（Mattel）",
        year: "2022",
        spec: "1:10 比例遥控车 · 后驱 · 车灯与尾喷可发光",
        image: "/media/merch/hotwheels-rc.jpg",
        imageAlt: "Hot Wheels R/C 与《新蝙蝠侠》联名 1:10 遥控战车及手柄",
        body: "美泰风火轮推出的全功能遥控电影战车（货号 HCD19）。1:10 比例，手枪式遥控手柄，后驱带悬挂系统，最高时速约 16 公里；前大灯与尾喷口可通电发光，驾驶舱可放入约 6 寸人偶。",
        sourceUrl: "https://creations.mattel.com/products/hot-wheels-rc-the-batman-the-original-batmobile-hcd19",
        sourceLabel: "Mattel Creations 产品页 HCD19",
        sourceTier: "official",
        verifiedAt: "2026.08.24",
      },
      {
        id: "jazzinc-clean",
        name: "Jazzinc 1/6 电影蝙蝠战车（普通版）",
        nameEn: "1/6 Batmobile from The Batman (2022) — Clean Version",
        maker: "Jazzinc Dioramas",
        year: "2022",
        spec: "1/6 比例 · 约 905 × 431 × 247 mm · 约 14 kg",
        image: "/media/merch/jazzinc-clean.jpg",
        imageAlt: "Jazzinc Dioramas 1/6 电影蝙蝠战车普通版侧前方",
        body: "荷兰 Jazzinc 依据电影实车图纸打造的 1/6 收藏级战车，适配 Hot Toys、INART 等 12 寸人偶。全车包含钢架结构与上千个零件，V8 引擎、仪表台与轮胎花纹按比例精准还原，配备灯光地台、车灯照明、排气烟雾与引擎音效系统。",
        sourceUrl: "https://jazzincdioramas.com/vehicles/16-scale-batmobile-from-the-batman-2022-clean-version",
        sourceLabel: "Jazzinc 普通版产品页",
        sourceTier: "official",
        verifiedAt: "2026.08.24",
      },
      {
        id: "jazzinc-weathered",
        name: "Jazzinc 1/6 电影蝙蝠战车（战损版）",
        nameEn: "1/6 Batmobile from The Batman (2022) — Weathered Version",
        maker: "Jazzinc Dioramas",
        year: "2022",
        spec: "1/6 比例 · 战损涂装 · 电子声光烟雾功能",
        image: "/media/merch/jazzinc-weathered.jpg",
        imageAlt: "Jazzinc Dioramas 1/6 电影蝙蝠战车战损版，泥污与擦痕涂装",
        body: "与普通版同比例及同电子功能配置（含灯光、烟雾、音效与遥控），涂装重点还原企鹅人追逐战后的重度战损状态：车身布满泥泞溅痕、撞击刮痕与积尘。",
        sourceUrl: "https://jazzincdioramas.com/vehicles/batmobile2022weathered",
        sourceLabel: "Jazzinc 战损版产品页",
        sourceTier: "official",
        verifiedAt: "2026.08.24",
      },
      {
        id: "hottoys-batcycle",
        name: "Hot Toys 1/6 蝙蝠摩托",
        nameEn: "Batcycle Sixth Scale Vehicle (MMS642)",
        maker: "Hot Toys",
        year: "2023",
        spec: "1/6 比例 · 全长约 42 cm · 适配 MMS641 蝙蝠侠",
        image: "/media/merch/hottoys-batcycle.jpg",
        imageAlt: "Hot Toys 1/6 电影版蝙蝠摩托，蝙蝠侠骑乘官方宣传图",
        body: "Movie Masterpiece MMS642，2023 年发售。全长约 42×19×19 厘米，还原上整流罩、带后视镜的车把、座下引擎与排气管、轮胎花纹。头灯与尾灯可 LED 发光，车把可左右转动，橡胶轮胎可转，附两款展示地台。蝙蝠侠人偶另售，专门配 1/6 Batman；补上 Jazzinc 战车之外的另一台电影载具。",
        sourceUrl: "https://www.sideshow.com/collectibles/dc-comics-batcycle-hot-toys-910637",
        sourceLabel: "Sideshow 产品页",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "hotwheels",
        name: "风火轮 1:50 电影蝙蝠战车合金车模",
        nameEn: "Hot Wheels 1:50 Batman Series Batmobile",
        maker: "Hot Wheels · 美泰（Mattel）",
        year: "2022",
        spec: "1:50 比例合金车模",
        image: "/media/merch/hotwheels.jpg",
        imageAlt: "风火轮 1:50 蝙蝠战车合金模型细节",
        body: "美泰风火轮推出的中比例合金收藏车模。车身采用全金属压铸工艺，细致刻画了车头冲撞保险杠、外露后置引擎与双排气管细节。",
      },
      {
        id: "jada-32",
        name: "Jada 1:32 合金蝙蝠战车",
        nameEn: "Jada Toys 1:32 Die-Cast Batmobile",
        maker: "Jada Toys · Hollywood Rides",
        year: "2022",
        spec: "1:32 比例合金模型",
        image: "/media/merch/jada-box.jpg",
        imageAlt: "Jada 1:32 合金战车包装盒与车身展示",
        body: "采用开门设计与真实橡胶轮胎，包装印有电影红黑标志性视觉，是大众市场最受欢迎的桌上展示车模之一。",
      },
      {
        id: "jada-18",
        name: "Jada 1:18 大比例合金战车带人偶",
        nameEn: "Jada Toys 1:18 Batmobile with Figure",
        maker: "Jada Toys",
        year: "2022",
        spec: "1:18 比例 · 车灯可亮 · 附金属蝙蝠侠人偶",
        image: "/media/merch/jada-18.jpg",
        imageAlt: "Jada 1:18 战车车灯点亮状态与金属人偶",
        body: "大比例合金战车模型，车头大灯与尾部引擎支持 LED 通电发光，座舱内部精细还原了仪表台与防滚架，随盒附赠同比例压铸金属蝙蝠侠人偶。",
      },
    ],
  },
  {
    id: "lego",
    kicker: "05",
    title: "乐高套组",
    titleEn: "LEGO Sets",
    intro:
      "收录乐高在 2022 年电影上映前后推出的超级英雄（DC Super Heroes）与机械组（Technic）套组，以及 2026 年 DC 蝙蝠侠二十周年传奇蝙蝠车系列。",
    items: [
      {
        id: "lego-76181",
        name: "乐高 76181 蝙蝠战车：企鹅人追逐战",
        nameEn: "Batmobile: The Penguin Chase",
        maker: "LEGO · 乐高 DC 超级英雄系列",
        year: "2022",
        spec: "392 颗粒 · 附 2 枚迷你人仔",
        image: "/media/merch/lego-76181.jpg",
        imageAlt: "乐高 76181 蝙蝠战车与企鹅人人仔包装盒",
        body: "迷你人仔比例的电影版战车，还原美式肌肉车底盘、外露后置引擎与后扰流板。附带蝙蝠侠与企鹅人两枚人仔，重现冰山俱乐部外的公路追逐场景。",
      },
      {
        id: "lego-76179",
        name: "乐高 76179 蝙蝠侠与瑟琳娜摩托追逐",
        nameEn: "Batman & Selina Kyle Motorcycle Pursuit",
        maker: "LEGO · 乐高 DC 超级英雄系列",
        year: "2022",
        spec: "149 颗粒 · 附 2 枚迷你人仔与双摩托",
        image: "/media/merch/lego-76179.jpg",
        imageAlt: "乐高 76179 蝙蝠侠与猫女双机车套组",
        body: "双车场景套组，包含蝙蝠侠与瑟琳娜·凯尔两枚人仔及各自专属机车，对应影片中的雨夜巡行，可停放于 76183 蝙蝠洞内。",
      },
      {
        id: "lego-76183",
        name: "乐高 76183 蝙蝠洞：谜语人对决",
        nameEn: "Batcave: The Riddler Face-off",
        maker: "LEGO · 乐高 DC 超级英雄系列",
        year: "2022",
        spec: "581 颗粒 · 附 6 枚迷你人仔",
        image: "/media/merch/lego-76183.jpg",
        imageAlt: "乐高 76183 蝙蝠洞地下站台场景与六枚人仔",
        body: "该系列最大的场景套组。主体为韦恩塔地底废弃火车站改建的蝙蝠洞，可停放 76181 战车与 76179 摩托。包含蝙蝠侠、瑟琳娜、谜语人、流浪者布鲁斯、阿尔弗雷德与戈登共六枚人仔。",
      },
      {
        id: "lego-30455",
        name: "乐高 30455 蝙蝠战车（微型拼砌包）",
        nameEn: "Batmobile Polybag",
        maker: "LEGO · 乐高 DC 超级英雄系列",
        year: "2022",
        spec: "68 颗粒 · 拼砌袋装",
        image: "/media/merch/lego-30455.jpg",
        imageAlt: "乐高 30455 微型袋装战车",
        body: "电影宣传期间推出的微型拼砌包战车，共 68 个零件，适合作为小比例桌面摆件或快速拼搭体验。",
      },
      {
        id: "lego-42127",
        name: "乐高机械组 42127 电影版蝙蝠战车",
        nameEn: "THE BATMAN - BATMOBILE (Technic)",
        maker: "LEGO · 乐高机械组 Technic",
        year: "2022",
        spec: "1360 颗粒 · 发光积木 · 差速器与独立悬挂",
        image: "/media/merch/lego-42127.jpg",
        imageAlt: "乐高机械组 42127 大比例战车与发光效果",
        body: "机械组（Technic）大比例电影战车，由 1360 个零件构成。配备可动 V8 引擎活塞、后轮差速器、前轮转向与双发光积木（黄色前灯与红色后引擎喷火）。",
      },
      {
        id: "lego-76332",
        name: "乐高 76332 电影版蝙蝠战车",
        nameEn: "The Batman Batmobile (20th Anniversary)",
        maker: "LEGO · 乐高 DC 系列",
        year: "2026",
        spec: "经典复刻系列 · 附纪念金币与专属铭牌",
        image: "/media/merch/lego-76332.jpg",
        imageAlt: "乐高 76332 2022 电影版战车",
        body: "乐高 DC 蝙蝠侠二十周年「传奇蝙蝠车」系列中的 2022 电影版。车顶可拆卸，驾驶舱可放入佩戴布质披风的蝙蝠侠人仔，附带专属展示铭牌与纪念金币。",
      },
    ],
  },
  {
    id: "print",
    kicker: "06",
    title: "出版与漫画",
    titleEn: "Books & Comics",
    intro:
      "收录官方艺术设定集、前传小说、保罗·达诺编剧的衍生漫画，以及 2022 年公映同期由 DC 推出的电影变体封面、院线赠刊与灵感原著套书。",
    items: [
      {
        id: "artbook",
        name: "《新蝙蝠侠》官方艺术设定集",
        nameEn: "The Art of The Batman",
        maker: "Abrams Books · 詹姆斯·菲尔德 著",
        year: "2022",
        spec: "精装大开本 · 全彩印刷",
        image: "/media/merch/artbook.jpg",
        imageAlt: "《The Art of The Batman》精装设定集封面",
        body: "导演马特·里夫斯亲笔作序。全书收录数百张前期概念设计图、分镜头脚本、服装道具分解图与主创专访，详细记录了新哥谭视觉构建的全过程。",
      },
      {
        id: "novel",
        name: "官方前传小说《蝙蝠侠之前》",
        nameEn: "Before the Batman: An Original Movie Novel",
        maker: "Random House · 大卫·卢曼 著",
        year: "2022",
        spec: "平装单行本 · 附彩插海报",
        image: "/media/merch/novel.jpg",
        imageAlt: "前传小说 Before the Batman 官方封面",
        body: "官方授权前传衍生读物，重点讲述布鲁斯·韦恩早年改装肌肉战车、接受体能训练，以及爱德华·纳什顿在孤儿院萌生仇恨的起源故事。",
      },
      {
        id: "riddler-book",
        name: "官方前传漫画《谜语人元年》",
        nameEn: "The Riddler: Year One",
        maker: "DC Black Label · 保罗·达诺 编剧",
        year: "2022–2023",
        spec: "6 期限定漫画单行本",
        image: "/media/merch/riddler-book.jpg",
        imageAlt: "《The Riddler: Year One》漫画封面",
        body: "由电影谜语人饰演者保罗·达诺亲自编剧、DC Black Label 出版的成人向限定漫画，以司法会计视角展现了「新生」基金贪腐黑幕与谜语人的黑化历程。",
      },
      {
        id: "the-batman-movie-variant-covers",
        name: "DC《The Batman》2022 电影变体封面系列",
        nameEn: "The Batman Movie Variant Cover Collection",
        maker: "DC Comics",
        year: "2022",
        spec: "9 期电影灵感变体封面 · 2022 年 3 月发行",
        image: "/media/merch/comics/the-batman-variants/batman-121-bermejo.jpg",
        imageAlt: "Lee Bermejo 为 Batman #121 绘制的《新蝙蝠侠》电影变体封面，作为九期系列代表图",
        body: "DC 于 2022 年 2 月 3 日公布一套配合华纳《新蝙蝠侠》上映的三月变体封面，官方名单共九期，画师为 Lee Bermejo、Carlos D’Anda、Jonboy Meyers、Puppeteer Lee、Rafael Albuquerque、Jenny Frison、Ben Oliver、Riccardo Federici、Simone Bianchi。发售窗口为 2022 年 3 月 1 日至 22 日。其中画师 Simone Bianchi 为《Harley Quinn #13》绘制的经典构图，同期亦被选作北美首映活动独家赠刊的封面视觉。",
        sourceUrl:
          "https://www.dc.com/blog/2022/02/03/march-variant-covers-featuring-art-inspired-by-warner-bros-pictures-the-batman-available-for-pre-order-now",
        sourceLabel: "DC 官方 · 2022.02.03 电影变体封面公告",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
        covers: THE_BATMAN_MOVIE_VARIANTS,
      },
      {
        id: "imax-long-halloween-1",
        name: "IMAX Fan First Premiere《The Long Halloween #1》限定变体版",
        nameEn: "Batman: The Long Halloween #1 — The Batman IMAX Fan First Premiere Exclusive",
        maker: "DC Comics · IMAX · Warner Bros.",
        year: "2022",
        spec: "2022.03.01 · IMAX 提前场一人一册 · 送完即止",
        image: "/media/merch/comics/the-batman-variants/long-halloween-imax.jpg",
        imageAlt:
          "Simone Bianchi 为 IMAX Fan First Premiere《Batman: The Long Halloween #1》Special Edition 绘制的封面：与 Harley Quinn #13 电影变体共用同一构图，蝙蝠侠、猫女、谜语人与企鹅人拼贴成蝙蝠徽",
        body: "2022 年 3 月 1 日 IMAX Fan First Premiere 提前场向持票观众发放的实体赠刊，内容为 Jeph Loeb / Tim Sale《Batman: The Long Halloween》第一期，每张票一册、送完即止。封面由西莫内·比安基（Simone Bianchi）绘制。画师本人于 2022 年 2 月 9 日发文确认，这张构图同时是 Harley Quinn #13 电影变体封面；院线赠刊加上 Special Edition 与 IMAX Fan First Premiere 刊头。该刊仅在 IMAX 提前场发放。",
        sourceUrl: "https://x.com/SBianchiArt/status/1491418935144886275",
        sourceLabel: "Simone Bianchi · IMAX 赠刊封面确认",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "the-batman-box-set",
        name: "《The Batman》电影灵感漫画盒装套书",
        nameEn: "The Batman Box Set",
        maker: "DC Comics · Jim Lee 外盒艺术",
        year: "2022",
        spec: "3 册平装套书 · Jim Lee 外盒艺术 · ISBN 978-1-77951-429-5",
        image: "/media/merch/comics/the-batman-variants/the-batman-box-set.jpg",
        imageAlt: "《The Batman》电影灵感漫画盒装套书，Jim Lee 绘制的红黑蝙蝠侠外盒",
        body: "DC 为配合电影上映推出的三册平装套装，外盒艺术由 Jim Lee 绘制，ISBN 978-1-77951-429-5，收录导演马特·里夫斯公开提到的主要漫画灵感来源：《Batman: Year One》《Batman: The Long Halloween》《Batman: Ego and Other Tails》。DC Connect / DC Spotlight 征订标注 ON SALE 3/1/22、定价 63 美元；漫画店 Diamond 渠道约 3 月下旬上架，图书渠道多见 3 月 29 日。三册平装套装属电影灵感再版，并非变体封面。",
        sourceUrl:
          "https://comicbook.com/movies/news/the-batman-box-set-dc-comics-inspired-matt-reeves-movie-2022/",
        sourceLabel: "ComicBook · DC Connect 征订",
        sourceTier: "press",
        verifiedAt: "2026.09.14",
      },
    ],
  },
  {
    id: "media",
    kicker: "07",
    title: "影音与原声",
    titleEn: "Home Video & Soundtrack",
    intro:
      "包含 4K UHD 超高清蓝光光碟、标准蓝光碟片，以及迈克尔·吉亚奇诺创作的原声大碟与限量黑胶唱片。",
    items: [
      {
        id: "uhd",
        name: "《新蝙蝠侠》4K Ultra HD 收藏版",
        nameEn: "The Batman 4K Ultra HD + Blu-ray",
        maker: "Warner Bros. Home Entertainment",
        year: "2022",
        spec: "4K UHD + 蓝光双碟 · 杜比视界 / 杜比全景声",
        image: "/media/merch/uhd.jpg",
        imageAlt: "《新蝙蝠侠》4K Ultra HD 官方包装封面",
        body: "搭载原生 4K 超高清画质、杜比视界（Dolby Vision）HDR 及杜比全景声音轨，准确还原摄影师格雷格·弗雷泽（Greig Fraser）标志性的高反差光影与雨夜质感，附带两小时幕后花絮。",
      },
      {
        id: "bluray",
        name: "《新蝙蝠侠》蓝光标准版",
        nameEn: "The Batman Blu-ray Edition",
        maker: "Warner Bros. Home Entertainment",
        year: "2022",
        spec: "1080P 全高清蓝光碟",
        image: "/media/merch/bluray.jpg",
        imageAlt: "《新蝙蝠侠》蓝光标准版封面",
        body: "面向大众影迷的标准蓝光光盘，收录电影正片、主创访谈以及阿卡姆疯人院删减片段等收录内容。",
      },
      {
        id: "ost",
        name: "Mondo 电影原声 3XLP",
        nameEn: "The Batman Original Motion Picture Soundtrack 3XLP",
        maker: "Mondo × WaterTower Music · 迈克尔·吉亚奇诺 作曲",
        year: "2022",
        spec: "3 张 180g 黑胶 · 近两小时配乐 · Henry Abrams 封面",
        image: "/media/merch/ost.jpg",
        imageAlt: "Mondo 发行的《新蝙蝠侠》原声 3XLP，Henry Abrams 绘制封面",
        body: "奥斯卡获奖作曲家迈克尔·吉亚奇诺操刀，Mondo 与 WaterTower Music 合作推出三碟 180 克黑胶，近两小时配乐，三折封套，封面由 Henry Abrams 新绘。店限还有 Mondo 独家彩胶，同时有纯黑胶版本。数字流媒体与双 CD 仍是同一份配乐的其他载体；厚重四音符铜管与 Tiffin Boys 合唱的谜语人主题，是这一代蝙蝠侠最容易辨认的声音。",
        sourceUrl: "https://mondoshop.com/products/the-batman-original-motion-picture-soundtrack-3xlp",
        sourceLabel: "Mondo 官方产品页",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
    ],
  },
  {
    id: "posters",
    kicker: "08",
    title: "院线限定与观影特典",
    titleEn: "Theatrical Exclusives & Cinema Premiums",
    intro:
      "收录 2022 年公映档与 2024 年重映档由 IMAX、Dolby、ScreenX、4DX 与全球合作院线官方发售与发行的实体收藏特典，涵盖限定海报、漫画书、三面胶片、Film Mark、徽章、Original Ticket、艺术纪念卡与专属观影物料。",
    items: [
      {
        id: "poster-imax-horiz",
        name: "IMAX × Bill Sienkiewicz 横版专属海报",
        nameEn: "The Batman IMAX Exclusive Horizontal Banner by Bill Sienkiewicz",
        maker: "IMAX · Bill Sienkiewicz · Warner Bros.",
        year: "2022",
        spec: "IMAX 官方专属视觉 · 红黑拼贴横幅",
        image: "/media/merch/theatrical/thebatman-imax-sienkiewicz.jpg",
        imageAlt: "Bill Sienkiewicz 绘制的《新蝙蝠侠》IMAX 横版专属海报，红黑拼贴横幅中可见蝙蝠侠、谜语人、猫女与企鹅人",
        body: "由知名艺术家比尔·辛凯维奇（Bill Sienkiewicz）为 IMAX 绘制的经典横版专属视觉。画面以极具视觉张力的红色蝙蝠轮廓为基底，蝙蝠侠居中，谜语人、猫女、企鹅人、戈登与阿尔弗雷德等主要角色分列两侧，呈现粗粝而深沉的新黑色水墨拼贴风格。",
        sourceUrl: "https://www.ign.com/articles/how-the-batman-poster-was-made-bill-sienkiewicz",
        sourceLabel: "IGN · Sienkiewicz IMAX 海报访谈",
        sourceTier: "press",
        verifiedAt: "2026.09.14",
      },
      {
        id: "poster-dolby",
        name: "Dolby Cinema《新蝙蝠侠》专属院线海报",
        nameEn: "The Batman Dolby Cinema Exclusive Poster",
        maker: "Dolby Cinema · Warner Bros.",
        year: "2022",
        spec: "2022.02.10 售票同步公布 · Dolby Cinema 专属视觉",
        image: "/media/merch/theatrical/thebatman-dolby-2022.jpg",
        imageAlt: "Dolby Cinema《新蝙蝠侠》专属海报：蝙蝠侠立在雨夜中，身后蝙蝠信号灯，左右 Dolby D 形外框，底部写 Discover It At Dolby Cinema",
        body: "杜比影院与华纳在 2022 年 2 月预售开启时联合公布的专属海报。画面中蝙蝠侠背对镜头伫立于阴冷雨夜，身后探照灯刺破云霄点亮蝙蝠信号，两侧巧妙融入杜比标志性的「D」形边框构图，并附有「Discover It At Dolby Cinema」专属标语。",
        sourceUrl: "https://www.dolby.com/experience/the-batman/",
        sourceLabel: "Dolby · The Batman 体验页",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "screenx-2022-a",
        name: "ScreenX《新蝙蝠侠》专属海报",
        nameEn: "The Batman ScreenX Exclusive Poster",
        maker: "ScreenX · CJ 4DPLEX · Warner Bros.",
        year: "2022",
        spec: "270° 全景厅专属视觉 · Batman / Catwoman / 载具构图",
        image: "/media/merch/theatrical/thebatman-screenx-2022-a.jpg",
        imageAlt: "ScreenX《新蝙蝠侠》专属海报：蝙蝠侠与猫女对立，前方是摩托车，后方是蝙蝠战车与哥谭天际线，ScreenX 标志嵌进城市剪影",
        body: "CJ 4DPLEX 官方发布的 ScreenX 格式专属海报。画面呈现蝙蝠侠与猫女在暮色哥谭天际线前的经典对峙，猫女机车与蝙蝠战车遥相呼应，顶端印有「Unmask The Truth」解谜标语，标志着本片成为首部以 ScreenX 270 度三面全景制式公映的蝙蝠侠电影。",
        sourceUrl: "https://www.prnewswire.com/news-releases/the-batman-debuts-in-the-visually-immersive-270-degree-panoramic-screenx-theaters-301496149.html",
        sourceLabel: "CJ 4DPLEX 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "4dx-2022",
        name: "4DX《新蝙蝠侠》专属海报",
        nameEn: "The Batman 4DX Exclusive Poster",
        maker: "4DX · CJ 4DPLEX · Warner Bros.",
        year: "2022",
        spec: "4DX 厅专属视觉 · Batman / Catwoman / 载具 · FEEL IT IN 4DX",
        image: "/media/merch/theatrical/thebatman-4dx-2022.jpg",
        imageAlt: "4DX《新蝙蝠侠》专属海报：蝙蝠侠与猫女对立，前方是摩托车，后方是蝙蝠战车，暮色背景，底部写 FEEL IT IN 4DX",
        body: "全球 4DX 影厅专属宣发海报。画面聚焦于暮色暗影中蝙蝠侠与猫女的载具对峙，底部醒目标注「FEEL IT IN 4DX」动感影厅标识，生动传递雨夜机车轰鸣与战车追逐的沉浸式体感观影体验。",
        sourceUrl: "https://ameblo.jp/uzakiron/entry-12732418740.html",
        sourceLabel: "日本观众 2022.03 4DX 实体海报实拍",
        sourceTier: "archive",
        verifiedAt: "2026.09.14",
      },
      {
        id: "imax-fan-first",
        name: "IMAX Fan First Premiere 首映活动海报",
        nameEn: "DC Presents The Batman Fan First Premiere Poster Art",
        maker: "IMAX · Warner Bros. · DC",
        year: "2022",
        spec: "2022.03.01 · IMAX 提前场 · 活动宣传视觉",
        image: "/media/merch/theatrical/thebatman-imax-fan-first.jpg",
        imageAlt: "IMAX Fan First Premiere 活动视觉，橙红背景中的蝙蝠侠与蝙蝠战车，标注 3 月 1 日 IMAX 提前场",
        body: "DC Presents The Batman Fan First Premieres Exclusively in IMAX，2022 年 3 月 1 日在美国超过一百座城市的 IMAX 厅提前放映。官方活动视觉采用橙红背景中的蝙蝠侠与蝙蝠战车构图，并标注 Fan First Premieres、Exclusively in IMAX 与 March 1。官方确认每张票附赠的实体是《Batman: The Long Halloween #1》独家封面漫画（一人一份，送完即止），赠刊见出版栏。",
        sourceUrl: "https://comicbook.com/movies/news/how-to-get-tickets-the-batman-early-access-screening-batman-fan-first-premieres-imax/",
        sourceLabel: "ComicBook · Fan First Premiere 购票说明",
        sourceTier: "press",
        verifiedAt: "2026.09.14",
      },
      {
        id: "jp-preview-imax",
        name: "日本 3 月 10 日前夜特别上映 IMAX 原创艺术海报",
        nameEn: "Japan IMAX Preview Screening Original Art Poster",
        maker: "DC Japan · IMAX · Warner Bros. Japan · United Cinemas",
        year: "2022",
        spec: "2022.03.10 · 横 27 inch × 纵 13.9 inch · IMAX 前夜特别上映先着特典",
        image: "/media/merch/theatrical/thebatman-jp-preview-imax.jpg",
        imageAlt: "日本 3 月 10 日 IMAX 前夜特别上映横版原创艺术海报：红黑拼贴横幅，蝙蝠侠、谜语人、猫女与企鹅人分列",
        body: "日本华纳于 2022 年 3 月 10 日前夜特别上映场次向 IMAX 观影者独家派发的「原创艺术海报（オリジナルアートポスター）」。规格为约 27×13.9 英寸超宽横幅，采用红黑对撞的角色水墨拼贴视觉，为日本公映前夜入场的限量特典。",
        sourceUrl: "https://x.com/dc_jp/status/1499293647158018051",
        sourceLabel: "DC 日本官方 · 前夜特别上映公告",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "jp-imax-a3",
        name: "日本 IMAX Exclusive Visual A3 特典海报",
        nameEn: "Japan IMAX Exclusive Visual A3 Mini Poster",
        maker: "IMAX · Warner Bros. Japan",
        year: "2022",
        spec: "2022.03.11 起 · A3 · 日本 IMAX 观众先着特典",
        image: "/media/merch/theatrical/thebatman-jp-imax-a3.jpg",
        imageAlt: "日本 IMAX Exclusive Visual A3 特典海报：黑与血红双色，失焦的蝙蝠侠头套侧脸，底部 IMAX 标志",
        body: "日本各大院线自 2022 年 3 月 11 日公映日起面向 IMAX 观众发放的限定 A3 特典海报。画面聚焦于黑与鲜血般猩红交融的微晕侧影，带有强烈的胶片颗粒与雨夜失焦感，极富视觉冲击力。",
        sourceUrl: "https://x.com/IMAX_JAPAN/status/1499655892530253824",
        sourceLabel: "IMAX 日本官方 · A3 迷你海报公告",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "jp-4dx-a3",
        name: "日本 4DX A3 入场特典海报",
        nameEn: "Japan 4DX A3 Admission Poster",
        maker: "4DX · Warner Bros. Japan",
        year: "2022",
        spec: "2022.03.11 起 · A3 · 日本 4DX 观众先着 · 一次观影一张",
        image: "/media/merch/theatrical/thebatman-4dx-2022.jpg",
        imageAlt: "日本 4DX A3 入场特典海报实物：蝙蝠侠与猫女对立，载具置于暮色哥谭前，底部 FEEL IT IN 4DX",
        body: "日本各大院线 4DX 影厅自 2022 年 3 月 11 日公映起随票赠送的 A3 实体海报。画面采用双雄载具对峙的经典构图，选用特制厚磅纸张印刷，为日本首周热门观影特典。",
        sourceUrl: "https://www.entanow.com/thebatman-toku/",
        sourceLabel: "エンタNOW · 日本入场特典汇总",
        sourceTier: "press",
        verifiedAt: "2026.09.14",
      },
      {
        id: "jp-screenx-a3",
        name: "日本 ScreenX A3 入场特典海报",
        nameEn: "Japan ScreenX A3 Admission Poster",
        maker: "ScreenX · Warner Bros. Japan",
        year: "2022",
        spec: "2022.03.11 起 · A3 · 日本 ScreenX 观众先着",
        image: "/media/merch/theatrical/thebatman-screenx-2022-a.jpg",
        imageAlt: "日本 ScreenX A3 入场特典海报：蝙蝠侠与猫女对立，摩托车与蝙蝠战车置于哥谭天际线前，ScreenX 标志嵌进城市剪影",
        body: "日本 ScreenX 厅公映首周限定 A3 特典海报。版式特别针对三面全景银幕进行调整，与 4DX 特典遥相呼应，细腻呈现暮色哥谭中侦探与飞贼的宿命交汇。",
        sourceUrl: "https://www.entanow.com/thebatman-toku/",
        sourceLabel: "エンタNOW · 日本入场特典汇总",
        sourceTier: "press",
        verifiedAt: "2026.09.14",
      },
      {
        id: "megabox-dolby-a3",
        name: "Megabox 韩国 Dolby Cinema A3 海报",
        nameEn: "Megabox Korea Dolby Cinema A3 Poster",
        maker: "Megabox · Dolby Cinema",
        year: "2022",
        spec: "2022.02.28 公布 · 韩国 Dolby Cinema 独家 artwork 的 A3 实体",
        image: "/media/merch/theatrical/thebatman-dolby-2022.jpg",
        imageAlt: "Megabox 韩国 Dolby Cinema A3 海报：蝙蝠侠立在雨夜蝙蝠信号灯前，左右 Dolby D 形外框",
        body: "韩国 Megabox 影城在公映期为杜比影院观众发放的独家 A3 特典海报。海报采用全球 Dolby 专属视觉，实物施加了标题局部滴胶（环氧树脂）、杜比标志全息银箔与蝙蝠侠轮廓微浮雕等重工后加工工艺，极具收藏质感。",
        sourceUrl: "https://www.newsis.com/view/NISX20220228_0001776438",
        sourceLabel: "Newsis · Megabox Dolby Cinema 独家海报",
        sourceTier: "press",
        verifiedAt: "2026.09.14",
      },
      {
        id: "cgv-imax-week2",
        name: "CGV 韩国 IMAX 限定收藏海报",
        nameEn: "CGV Korea IMAX Limited Poster",
        maker: "CGV · IMAX",
        year: "2022",
        spec: "2022.03 · 韩国 CGV 院线 · IMAX 入场特典 · A3",
        image: "/media/merch/theatrical/thebatman-cgv-imax-week2.jpg",
        imageAlt: "CGV 韩国 IMAX LIMITED POSTER 实物，画面是 Bill Sienkiewicz 横向拼贴并带 IMAX 标志",
        body: "韩国连锁院线 CGV 为《新蝙蝠侠》IMAX 场次发行的限定实体海报。采用比尔·辛凯维奇绘制的横向水墨拼贴视觉，配以韩版专属排版与厚质哑光特种纸印刷，为韩国公映期间的高人气影迷特典。",
        verifiedAt: "2026.09.14",
      },
      {
        id: "cgv-golden-ticket",
        name: "CGV《新蝙蝠侠》Golden Ticket No.5",
        nameEn: "CGV Golden Ticket No.5 — The Batman",
        maker: "CGV",
        year: "2022",
        spec: "No.5 · 2022.03.01 · 金条盒 / 磁贴 / 特制票 / 2D 观影券",
        image: "/media/merch/cinema/cgv-golden-ticket.jpg",
        imageAlt: "CGV《더 배트맨》Golden Ticket No.5 宣传图：金条造型收藏票、特制票与磁贴",
        body: "CGV 电影收藏票线的第五号，对应韩国 2022 年 3 月 1 日公映的《더 배트맨》。套装是金条造型包装，内含磁贴、一张电影主题特制票，以及一张 CGV 普通厅 2D 观影券（券码另以短信发送）。CGV 在 2 月 17 日 Kakao 购物直播「무비오픈런」首卖，当时标价 1 万 3 千韩元。",
        verifiedAt: "2026.09.14",
      },
      {
        id: "lotte-art-card",
        name: "Lotte Cinema《新蝙蝠侠》Signature Art Card",
        nameEn: "Lotte Cinema Signature Art Card — The Batman",
        maker: "Lotte Cinema",
        year: "2022",
        spec: "2022.03.01 公映同期 · 信封 + 艺术卡",
        image: "/media/merch/cinema/lotte-art-card.jpg",
        imageAlt: "乐天影城《新蝙蝠侠》Signature Art Card 的谜语人式信封特典，2022 年 3 月 1 日观影当日实拍",
        body: "韩国乐天影院（Lotte Cinema）标志性的 Signature Art Card 专属收藏卡。于 2022 年 3 月 1 日韩国公映首日限量派发，包含一张双面精印的重磅艺术纪念卡，并配备精心定制的仿谜语人绿色信封外包装。",
        verifiedAt: "2026.09.14",
      },
      {
        id: "cgv-screenx-dc-comic-book",
        name: "CGV ScreenX《新蝙蝠侠》DC 漫画书特典",
        nameEn: "CGV ScreenX DC Comic Book — The Batman",
        maker: "CGV · ScreenX · Warner Bros. Korea",
        year: "2022",
        spec: "ScreenX 第 2 周 · 先着特典",
        image: "/media/merch/cinema/cgv-screenx-dc-comic-book.jpg",
        imageAlt: "CGV ScreenX《新蝙蝠侠》DC 漫画书特典实物，封面为电影版蝙蝠侠与哥谭角色群像",
        body: "韩国 CGV 影城为 ScreenX 场次第二周观众发放的官方授权 DC 漫画书特典。全本原版漫画装帧，封面印有 ScreenX 专属烫金印鉴，专为体验多面投影巨幕的观影者定制。",
        sourceUrl: "https://www.xportsnews.com/article/1540275",
        sourceLabel: "Xports News · CGV ScreenX 周次特典；藏家实物：Extmovie",
        sourceTier: "press",
        verifiedAt: "2026.09.15",
      },
      {
        id: "cgv-screenx-three-panel-film",
        name: "CGV ScreenX《新蝙蝠侠》三面胶片",
        nameEn: "CGV ScreenX 3-Panel Film — The Batman",
        maker: "CGV · ScreenX · Warner Bros. Korea",
        year: "2022",
        spec: "2022.03.16 起 · ScreenX · 先着特典",
        image: "/media/merch/cinema/cgv-screenx-three-panel-film.jpg",
        imageAlt: "CGV ScreenX《新蝙蝠侠》三面胶片特典实物，三张胶片折叠收在黑色 ScreenX 卡套中",
        body: "韩国 CGV 影城 ScreenX 第三周限定观影特典。三折叠式纯黑卡纸封套内嵌三联透光电影胶片，呼应 ScreenX 270 度三面环绕的独特银幕格局，极富光影质感。",
        sourceUrl: "https://www.xportsnews.com/article/1540275",
        sourceLabel: "Xports News · CGV ScreenX 周次特典；藏家实物：Extmovie",
        sourceTier: "press",
        verifiedAt: "2026.09.15",
      },
      {
        id: "cgv-film-mark-no52",
        name: "CGV《新蝙蝠侠》Film Mark No.52",
        nameEn: "CGV Film Mark No.52 — The Batman",
        maker: "CGV · Warner Bros. Korea",
        year: "2022",
        spec: "No.52 · 2022.03.01 · 2 种",
        image: "/media/merch/cinema/cgv-film-mark-no52.jpg",
        imageAlt: "CGV Film Mark No.52《新蝙蝠侠》两种特典实物，黑红胶片边框中印有不同电影画面",
        body: "韩国 CGV 经典胶片书签（Film Mark）系列第 52 号。一套包含两款不同画面的胶片卡，每张以真实电影胶片比例呈现四格经典场景截帧，并配有专属保护封套。",
        sourceUrl: "https://m.namu.moe/w/%ED%95%84%EB%A6%84%EB%A7%88%ED%81%AC",
        sourceLabel: "Namu Film Mark · No.52 资料记录",
        sourceTier: "archive",
        verifiedAt: "2026.09.15",
      },
      {
        id: "lotte-pin-badge",
        name: "Lotte Cinema《新蝙蝠侠》Pin Badge",
        nameEn: "Lotte Cinema Pin Badge — The Batman",
        maker: "Lotte Cinema · SUPERPLEX G",
        year: "2022",
        spec: "2022.03.01 公映周 · SUPERPLEX G · 先着特典",
        image: "/media/merch/cinema/lotte-pin-badge.webp",
        imageAlt: "Lotte Cinema《新蝙蝠侠》Pin Badge 实物，黑红 The Batman 标识徽章装在透明袋中",
        body: "韩国乐天影院 SUPERPLEX G 旗舰巨幕影厅发行的专属金属徽章特典。徽章立体雕刻电影版蝙蝠胸甲徽标，采用黑色哑光烤漆与金属拉丝工艺，随专属主题卡纸背板封装发放。",
        sourceUrl: "https://www.ajunews.com/view/20220224104754086",
        sourceLabel: "Aju News · Lotte SUPERPLEX G 特典报道",
        sourceTier: "press",
        verifiedAt: "2026.09.15",
      },
      {
        id: "megabox-original-ticket-no48",
        name: "Megabox《新蝙蝠侠》Original Ticket No.48",
        nameEn: "Megabox Original Ticket No.48 — The Batman",
        maker: "Megabox",
        year: "2022",
        spec: "No.48 · 2022.03.01 · 2 种",
        image: "/media/merch/cinema/megabox-original-ticket-no48.jpg",
        imageAlt: "Megabox Original Ticket No.48《新蝙蝠侠》两种收藏票实物，一张红色 Batman 票与一张黑色蝙蝠标志票",
        body: "韩国 Megabox 院线最具代表性的 Original Ticket 电影票根系列第 48 号。包含红底蝙蝠侠肖像款与黑底蝙蝠徽影两款造型，票面融合局部凹凸浮雕、烫银与透明光油工艺，为极具美感的高人气纸质特典。",
        sourceUrl: "https://juto.tistory.com/473",
        sourceLabel: "Juto · Megabox Original Ticket No.48 实物与官方规则记录",
        sourceTier: "archive",
        verifiedAt: "2026.09.15",
      },
      {
        id: "china-cinema-toy-cup",
        name: "中国大陆影院《新蝙蝠侠》玩偶杯",
        nameEn: "The Batman Cinema Character Cup — China",
        maker: "中国大陆院线",
        year: "2022",
        spec: "电影主题杯身 · 蝙蝠侠 / 猫女 / 蝙蝠 / 蝙蝠车杯盖造型",
        image: "/media/merch/cinema/thebatman-china-toy-cup.webp",
        imageAlt: "中国大陆影院售卖的《新蝙蝠侠》玩偶杯，黑红电影主题杯身配蝙蝠侠、猫女、蝙蝠和蝙蝠车杯盖",
        body: "2022 年 3 月中国大陆各大影院卖品部同期推出的电影主题饮料杯。杯身印有红黑主视觉海报，杯盖上配备立体造型公仔，包含战服蝙蝠侠、猫女、蝙蝠徽与蝙蝠战车等多款主题配件。",
        sourceUrl: "https://www.batcavecn.com/?p=17514",
        sourceLabel: "Batman 小站 · 大陆院线周边汇总",
        sourceTier: "archive",
        verifiedAt: "2026.09.15",
      },
      {
        id: "china-cinema-limited-bundle",
        name: "中国大陆影院限量周边套装",
        nameEn: "The Batman Cinema Limited Merch Bundle — China",
        maker: "中国大陆院线 · IMAX",
        year: "2022",
        spec: "海报 + 电脑包 + 健身手套 + 雨伞 + 拼图 · 首映观影礼 / IMAX 积分商城兑换",
        image: "/media/merch/cinema/thebatman-china-cinema-limited-bundle.webp",
        imageAlt: "《新蝙蝠侠》中国大陆影院限量周边套装合照，包含海报、电脑包、健身手套、雨伞和拼图",
        body: "中国大陆院线于公映期推出的官方限定观影周边礼品套组。成套包含宣发海报、主题笔记本电脑包、战术机能手套、反光折叠伞与定制艺术拼图等实用收藏物料。",
        sourceUrl: "https://www.batcavecn.com/?p=17514",
        sourceLabel: "Batman 小站 · 大陆院线周边汇总",
        sourceTier: "archive",
        verifiedAt: "2026.09.15",
      },
      {
        id: "china-red-2022",
        name: "中国大陆《新蝙蝠侠》定档红海报",
        nameEn: "China The Batman Dated Red Theatrical Poster",
        maker: "Warner Bros. China · DC",
        year: "2022",
        spec: "2022.02.24 定档公布 · 3 月 18 日中国大陆公映",
        image: "/media/merch/theatrical/thebatman-china-red.jpg",
        imageAlt: "中国大陆《新蝙蝠侠》定档海报：红色雨夜中的蝙蝠侠侧脸，中文标题与 3 月 18 日上映日期",
        body: "华纳兄弟官方于 2022 年 2 月公布的中国大陆公映定档主视觉海报。深红雨夜中微露面罩侧脸，凝重的工业雾气与手写体公映日期交织，标志着影片正式定档 3 月 18 日登陆全国各大院线。",
        sourceUrl: "https://m.mp.oeeee.com/a/BAAFRD000020220224654887.html",
        sourceLabel: "南都娱乐 · 中国大陆定档",
        sourceTier: "press",
        verifiedAt: "2026.09.14",
      },
      {
        id: "china-cast-2022",
        name: "中国大陆「暗夜群像」独家海报",
        nameEn: "China Exclusive Night Ensemble Theatrical Poster",
        maker: "Warner Bros. China · DC",
        year: "2022",
        spec: "2022.03.09 公布 · 中国独家电影海报 · 3 月 18 日公映",
        image: "/media/merch/theatrical/thebatman-china-cast.jpg",
        imageAlt: "中国大陆「暗夜群像」海报：蝙蝠侠居中，猫女与企鹅人分立，暴雨与火焰中的哥谭",
        body: "华纳兄弟发布的「暗夜群像」中国大陆独家公映海报。蝙蝠侠凝神居中，猫女与企鹅人分立两侧，背景烈焰吞噬哥谭地标，官方标语配文「哥谭群像，正义与邪恶较量，光明与黑暗对抗」，极富戏剧张力。",
        sourceUrl: "https://www.gamersky.com/news/202203/1465836.shtml",
        sourceLabel: "游民星空 · 中国定制版海报",
        sourceTier: "press",
        verifiedAt: "2026.09.14",
      },
      {
        id: "china-batman-riddler-2022",
        name: "中国大陆蝙蝠侠与谜语人对置海报",
        nameEn: "China Theatrical Batman vs Riddler Poster",
        maker: "Warner Bros. China · DC",
        year: "2022",
        spec: "2022 中国大陆公映视觉 · Batman / Riddler 对置",
        image: "/media/merch/theatrical/thebatman-china-batman-riddler.jpg",
        imageAlt: "中国大陆公映海报：左侧蝙蝠侠、右侧谜语人对置，中间是燃烧的哥谭与问号剪影",
        body: "中国大陆公映主视觉海报之一。画面采用蝙蝠侠与谜语人双雄对置构图，中央为火光冲天的哥谭天际线与巨大血红问号涂鸦，直观展现正义义警与高智商罪犯之间的致命博弈。",
        sourceUrl: "https://www.impawards.com/2022/batman_ver31.html",
        sourceLabel: "IMP Awards · Batman poster #31",
        sourceTier: "press",
        verifiedAt: "2026.09.14",
      },
      {
        id: "penguin-sneak-peek-2024",
        name: "《新蝙蝠侠》×《企鹅人》2024 重映限定 Mini Poster",
        nameEn: "The Batman & The Penguin Sneak Peek Exclusive Mini-Poster",
        maker: "Warner Bros. · Dolby Cinema · AMC Theatres",
        year: "2024",
        spec: "2024.08.28 一夜重映 · exclusive new art mini-poster · 送完即止",
        image: "/media/merch/theatrical/thebatman-rerelease-2024.jpg",
        imageAlt: "2024 年《新蝙蝠侠》重映活动海报：红底黑色蝙蝠侠侧脸，标题 THE BATMAN，BACK IN THEATERS 8/28，上方写 Includes an exclusive sneak peek at The Penguin",
        body: "华纳与 Dolby、AMC 院线在 2024 年 8 月 28 日举办《新蝙蝠侠》单日重映活动时发放的限定迷你海报。活动特邀影迷提前点映 HBO 衍生剧《企鹅人》独家先导片段，海报采用重映专属艺术设计。",
        sourceUrl: "https://x.com/warnerbros/status/1821244921904558385",
        sourceLabel: "Warner Bros. 官方 · 2024.08.07 重映公告",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
    ],
  },

  {
    id: "prints",
    kicker: "09",
    title: "官方授权艺术印刷",
    titleEn: "Official Art Prints",
    intro:
      "收录 Mondo、Sideshow、Bottleneck Gallery 等授权艺术画廊与厂牌正式推出的《新蝙蝠侠》限量丝网版画与收藏级石版画，完整记录版号、印制规格与版画工艺。",
    items: [
      {
        id: "poster-mondo",
        name: "Mondo × Francesco Francavilla 限时版丝网海报",
        nameEn: "The Batman by Francesco Francavilla (Mondo Timed Edition)",
        maker: "Mondo · Francesco Francavilla 绘 · Lady Lazarus 印",
        year: "2022",
        spec: "24×36 英寸 · 手工丝网 · Timed Edition（3/3–3/6）",
        image: "/media/merch/poster-mondo.jpg",
        imageAlt: "Mondo 限时版丝网海报，红黑主色调，雨夜中喷射尾焰的蝙蝠战车",
        body: "Mondo 为电影发行的第一张授权丝网。弗朗切斯科·弗兰卡维拉绘制，Lady Lazarus 印刷，24×36 英寸。常规版是 Timed Edition：2022 年 3 月 3 日 11:00 CT 至 3 月 6 日 23:59 CT，印量由该时段销量决定。红黑两色勾出雨夜战车尾焰与义警剪影。",
        sourceUrl: "https://mondoshop.com/blogs/news/the-batman-by-francesco-francavilla-on-sale-info",
        sourceLabel: "Mondo 官方发售说明",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "poster-mondo-var",
        name: "Mondo × Francesco Francavilla 变体版丝网海报",
        nameEn: "The Batman Variant Screenprint by Francesco Francavilla",
        maker: "Mondo · Francesco Francavilla 绘 · Lady Lazarus 印",
        year: "2022",
        spec: "24×36 英寸 · 手工丝网 · 限量 325 张",
        image: "/media/merch/poster-mondo-var.jpg",
        imageAlt: "Mondo 变体版丝网海报，红雨中的蝙蝠侠头套特写",
        body: "Mondo 与常规版同日推出的限量变体丝网版画。全球限量印制 325 张，规格为 24×36 英寸，由知名印刷工坊 Lady Lazarus 采用手工丝网工艺打造，画面聚焦于暴雨中红光映照的头套侧影特写。",
        sourceUrl: "https://mondoshop.com/blogs/news/the-batman-by-francesco-francavilla-on-sale-info",
        sourceLabel: "Mondo 官方发售说明",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "sam-green-bottleneck",
        name: "Sam Green × Bottleneck Gallery《新蝙蝠侠》艺术海报",
        nameEn: "The Batman by Sam Green",
        maker: "Sam Green · Bottleneck Gallery",
        year: "2023",
        spec: "24×36 英寸 · Giclée · 手编号 · 常规版 175 张",
        image: "/media/merch/theatrical/thebatman-sam-green-bottleneck.jpg",
        imageAlt: "Sam Green 为 Bottleneck Gallery 绘制的《新蝙蝠侠》艺术海报，侦探板风格拼贴雨夜哥谭与角色",
        body: "Bottleneck Gallery 于 2023 年 3 月 7 日发售。Sam Green 把电影场面做成谜语人式侦探板：雨夜哥谭、战车、猫女、企鹅人与剪报钉在同一张 24×36 英寸 Giclée 上。常规版手编号 175 张；另有变体版 100 张。",
        sourceUrl: "https://bottleneckgallery.com/blogs/news/new-batman-prints-by-dayne-henry-sam-green-mike-mcgee-on-sale-info",
        sourceLabel: "Bottleneck Gallery 发售说明",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "poster-wall",
        name: "「揭开真相」经典公映海报挂画",
        nameEn: "Unmask the Truth 24×36 Poster",
        maker: "Trends International",
        year: "2022",
        spec: "24×36 英寸零售挂画",
        image: "/media/merch/poster-wall.jpg",
        imageAlt: "装裱在画框中的「揭开真相」官方海报，红字问号覆盖蝙蝠侠面庞",
        body: "公映期间进入零售渠道的官方主视觉：红字问号与密电符号涂鸦盖在蝙蝠侠面庞上，对应全片侦探解谜。Trends International 发行的 24×36 英寸零售海报。",
      },
      {
        id: "poster-rays",
        name: "「破晓微光」官方艺术挂画",
        nameEn: "Rays of Light Art Print",
        maker: "Trends International / Pyramid",
        year: "2022",
        spec: "24×36 英寸胶印挂画",
        image: "/media/merch/poster-rays.jpg",
        imageAlt: "蝙蝠侠伫立于一束垂直顶光之下的零售艺术挂画",
        body: "零售艺术印刷。蝙蝠侠立在一束垂直顶光里，红黑渐变背景。",
      },
    ],
  },
  {
    id: "fashion",
    kicker: "10",
    title: "时装、首饰与配饰",
    titleEn: "Fashion, Jewelry & Accessories",
    intro:
      "以 2022 年 3 月华纳消费品与 DC 官方公开发布的时装胶囊为核心线索，收录电影公映同期的高级时装胶囊、工装夹克、机能运动服饰、限量腕表及战术配饰皮具。",
    items: [
      {
        id: "lanvin-batman",
        name: "LANVIN ×《新蝙蝠侠》奢侈时装胶囊系列",
        nameEn: "LANVIN SS2022 × The Batman Capsule",
        maker: "LANVIN · Saks Fifth Avenue",
        year: "2022",
        spec: "2021 巴黎时装周发布 · 2022.03 于 Saks 发售",
        image: "/media/merch/fashion/lanvin-batman.jpg",
        imageAlt: "LANVIN 2022 春夏《新蝙蝠侠》胶囊：深色成衣、蝙蝠战车轮廓手袋与金属网眼裙装",
        body: "华纳 2022 年 1 月 10 日新闻稿把 LANVIN 列为电影奢侈时装合作方，也是蝙蝠侠形象首次交给该屋做完整胶囊。布鲁诺·西勒尔（Bruno Sialelli）2021 秋巴黎时装周发布的 2022 春夏系列，把深蓝、紫色与装饰艺术线条叠进成衣、金属网眼裙、双面泰迪外套，以及按蝙蝠战车轮廓做的 Curbs 鞋与 minaudière 手拿包。Saks 实体店 3 月 2 日起售，saks.com 3 月 15 日上线，涵盖高级成衣、金属网眼裙与战车轮廓包袋，呈现哥谭暗黑美学。",
        sourceUrl: "https://www.dc.com/blog/2022/01/10/warner-media-global-brands-and-experiences-to-launch-robust-batman-film-product-collection",
        sourceLabel: "DC / WarnerMedia 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "carhartt-batman",
        name: "Carhartt ×《新蝙蝠侠》联名工装系列",
        nameEn: "Carhartt x The Batman Collection",
        maker: "Carhartt · Warner Bros. Consumer Products · DC",
        year: "2022",
        spec: "2022.04.06 发售 · 外套 / 帽衫 / T 恤 / 帽 / 烫贴",
        image: "/media/merch/fashion/carhartt-batman.jpg",
        imageAlt: "Carhartt × The Batman 工装胶囊：编号 chore coat、帽衫与 I AM THE SHADOWS 标语",
        body: "Carhartt 官方新闻稿写明，这是该品牌与 DC 的首次合作，2022 年 4 月 6 日在 carhartt-x-thebatman 专页开售。系列含帽、帽衫、T 恤、夹克与熨烫贴章；代表性单品是带生产编号、胸袋反光蝙蝠徽的 chore coat，肩部加弹、肘部打褶，对应电影战衣的机能剪裁。定价约 24.99–129.99 美元。胸袋点缀反光电影蝙蝠徽标，兼具美式硬派工装剪裁与电影战术机能质感。",
        sourceUrl: "https://www.carhartt.com/inspired-by-the-batman",
        sourceLabel: "Carhartt 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "puma-batman",
        name: "PUMA × The Batman 运动鞋服胶囊",
        nameEn: "PUMA x The Batman Collection",
        maker: "PUMA · 彪马",
        year: "2022",
        spec: "2022.02.26 发售 · 服饰 + Suede / RS-X / Mayze / Fierce 2 / Court Rider / Ultra / Future Z",
        image: "/media/merch/puma-batman.jpg",
        imageAlt: "PUMA × The Batman 胶囊：黑红 Suede、RS-X 与印有电影图形的服装",
        body: "PUMA 官方新闻稿确认，电影训练与潮流胶囊于 2022 年 2 月 26 日上线，成人与儿童尺码。服饰含连帽衫、T 恤、T7 套装、短裤、紧身裤与帽；鞋款后继上架 Suede、瑟琳娜主题 Fierce 2、黑红 RS-X、红色 formstrip 的 Mayze，以及蝙蝠侠／猫女 Court Rider，另有 Ultra 与 Future Z 足球靴。全线五十余个 SKU，通体采用电影标志性的暗黑与血红对比配色，呼应夜巡战术风格。",
        sourceUrl: "https://about.puma.com/en/newsroom/news/batman-steps-spotlight-when-limited-edition-collection-puma-warner-bros-consumer",
        sourceLabel: "PUMA 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "eleven-batman",
        name: "EleVen by Venus Williams ×《新蝙蝠侠》运动服饰系列",
        nameEn: "EleVen by Venus Williams x The Batman",
        maker: "EleVen by Venus Williams",
        year: "2022",
        spec: "女装运动服饰 · Saks / Tennis Warehouse / Zalando",
        image: "/media/merch/fashion/eleven-batman.jpg",
        imageAlt: "EleVen by Venus Williams × The Batman 运动服饰：黑红紧身衣与蝙蝠剪影图案",
        body: "华纳 2022 年 1 月新闻稿把维纳斯·威廉姆斯的 EleVen 列为电影运动服饰合作方。系列按哥谭夜雨与霓虹来做：黑白单色加一点红，暴露拉链、绑带气眼，以及带铆钉、网眼与湿感印花的猫女指向单品。Saks、Tennis Warehouse 与欧洲 Zalando 有售。",
        sourceUrl: "https://www.dc.com/blog/2022/01/10/warner-media-global-brands-and-experiences-to-launch-robust-batman-film-product-collection",
        sourceLabel: "DC / WarnerMedia 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "tomboyx-batman",
        name: "TomboyX ×《新蝙蝠侠》服饰系列",
        nameEn: "TomboyX x The Batman Collection",
        maker: "TomboyX",
        year: "2022",
        spec: "T 恤与内衣 · 2022 电影授权",
        image: "/media/merch/fashion/tomboyx-batman.jpg",
        imageAlt: "TomboyX × The Batman 内裤与短裤，印有电影版蝙蝠徽与 Vengeance 字样",
        body: "TomboyX 与华纳官方联名推出的无性别居家服饰系列。采用微莫代尔亲肤面料，涵盖印有电影版蝙蝠徽标与「Vengeance」标语的棉质 T 恤、居家服与打底单品。",
        sourceUrl: "https://www.dc.com/blog/2022/01/10/warner-media-global-brands-and-experiences-to-launch-robust-batman-film-product-collection",
        sourceLabel: "DC / WarnerMedia 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "fossil-batman",
        name: "Fossil × The Batman 胶囊腕表",
        nameEn: "Fossil x The Batman Capsule Watches",
        maker: "Fossil",
        year: "2022",
        spec: "2022.02.28 · 蝙蝠侠自动机械表 + 谜语人石英表（限量 1595）",
        image: "/media/merch/fossil-batman.jpg",
        imageAlt: "Fossil 蝙蝠侠自动机械表、四条快拆表带与抽屉式收纳盒",
        body: "Fossil 胶囊 2022 年 2 月 28 日上线。蝙蝠侠自动机械表（LE1142SET）42 毫米黑离子电镀钢壳，半镂空表盘饰蝙蝠徽，透底可见红色自动陀，随附四条快拆表带与抽屉式收纳盒。同系列谜语人石英表用棋盘纹表带，六点位问号小盘可转，官方限量 1595 枚、定价 160 美元。",
        sourceUrl: "https://www.fossilgroup.com/fossil-launches-the-batman-capsule-collection/",
        sourceLabel: "Fossil Group 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "fossil-jewelry",
        name: "Fossil × The Batman 限量首饰",
        nameEn: "Fossil x The Batman Jewelry (Dog Tag / Bracelet / Ring)",
        maker: "Fossil",
        year: "2022",
        spec: "各限量 1000 · 狗牌项链 / 熔岩珠手链 / 火漆戒指",
        image: "/media/merch/fashion/fossil-jewelry.jpg",
        imageAlt: "Fossil × The Batman 狗牌开瓶器项链、熔岩珠手链与火漆蝙蝠徽戒指",
        body: "Fossil 官方新闻稿把三件首饰写成「白天是首饰、夜里有第二功能」。离子电镀哑光黑钢狗牌项链可当开瓶器，定价 75 美元；熔岩珠手链可吸附精油，55 美元；哑光黑钢火漆戒指随附蜡棒，可盖出蝙蝠徽火漆，45 美元。三件各限量 1000。",
        sourceUrl: "https://www.fossilgroup.com/fossil-launches-the-batman-capsule-collection/",
        sourceLabel: "Fossil Group 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "fossil-leather",
        name: "Fossil × The Batman 皮具系列",
        nameEn: "Fossil x The Batman Leather Goods",
        maker: "Fossil",
        year: "2022",
        spec: "背包 / 腰包 / 对折钱包 / 卡包",
        image: "/media/merch/fashion/fossil-leather.jpg",
        imageAlt: "Fossil × The Batman 黑色皮革背包、腰包与钱包，饰有电影版蝙蝠徽",
        body: "同一胶囊的皮具线。Fossil 官方名单含 The Batman Backpack、Waistpack、Zipper Card Case、2-in-1 Bifold Wallet 与 Card Case，按电影战衣的哑光黑与装甲剪裁来做。采用哑光黑皮革搭配战术护甲剪裁，细致呼应电影战甲设计语言。",
        sourceUrl: "https://www.fossilgroup.com/fossil-launches-the-batman-capsule-collection/",
        sourceLabel: "Fossil Group 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "mobyfox-batman",
        name: "MobyFox ×《新蝙蝠侠》智能腕表表带",
        nameEn: "MobyFox x The Batman Watch Bands",
        maker: "MobyFox",
        year: "2022",
        spec: "Apple Watch 等 22 mm 针扣 · Shadow Armor / Red Justice",
        image: "/media/merch/fashion/mobyfox-batman.jpg",
        imageAlt: "MobyFox Shadow Armor 3D 表带，按 2022 电影战甲模压的硅胶 Apple Watch 表带",
        body: "华纳合作名单里的 MobyFox，在电影上映同期推出智能表带。确认过的电影款是按新战甲做的 Shadow Armor 3D 硅胶带，以及红色 Red Justice；官方拆箱还带一条 Night of Noir 压纹皮表带。盒内两套表耳，可配 Apple Watch 各代与 22 毫米针扣表，另用二维码解锁主题表盘。",
        sourceUrl: "https://www.dc.com/blog/2022/01/10/warner-media-global-brands-and-experiences-to-launch-robust-batman-film-product-collection",
        sourceLabel: "DC / WarnerMedia 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "kross-studio",
        name: "Kross Studio × The Batman 陀飞轮收藏套装",
        nameEn: "The Batman Tourbillon Collector Set",
        maker: "Kross Studio · 瑞士高级独立制表",
        year: "2022",
        spec: "45mm 钛金属 DLC 黑化 · 中央陀飞轮 · 限量 10 套",
        image: "/media/merch/kross-studio.jpg",
        imageAlt: "Kross Studio 陀飞轮腕表与信号灯表盒雕塑",
        body: "瑞士独立制表品牌 Kross Studio 与华纳联合推出的高级制表套装。腕表采用 45 毫米 5 级钛金属 DLC 黑化表壳，中央陀飞轮框架巧妙融入蝙蝠徽格栅设计，搭载 KS 7'000 手动上链机芯，具备 5 天动力储存；随表附带全尺寸可通电发光的蝙蝠信号灯铝合金表盒雕塑。",
        sourceUrl: "https://kross-studio.com/the-batman-collector-set",
        sourceLabel: "Kross Studio 产品页",
        sourceTier: "official",
        verifiedAt: "2026.08.24",
      },
      {
        id: "police-batman",
        name: "Police × The Batman 四款限量腕表",
        nameEn: "Police x The Batman Limited Edition Watches",
        maker: "Police Lifestyle",
        year: "2022",
        spec: "四款合计全球 10,000 枚 · The Batman / Vengeance / Gotham City / Catwoman",
        image: "/media/merch/police-batman.jpg",
        imageAlt: "Police 联名四款电影腕表实物：蝙蝠侠、Vengeance、哥谭与猫女",
        body: "意大利 Police 为电影做的四款限量表，全球合计一万枚，2022 年 2 月发售，售价约 199–399 欧元。四款是 The Batman（分体表壳对应双重身份）、Vengeance Edition（三时区）、Gotham City Edition（表盘可亮起蝙蝠徽）与 Catwoman Edition（黑石表圈）。每只表附蝙蝠徽表盒，内含仿谜语人绿信封与鉴证卡。四款同属 2022 年电影胶囊。",
        verifiedAt: "2026.09.14",
      },
    ],
  },
  {
    id: "lifestyle",
    kicker: "11",
    title: "生活方式与奇特联名",
    titleEn: "Lifestyle & Novelty Collaborations",
    intro:
      "收录《新蝙蝠侠》公映同期推出的官方授权生活方式与跨界限定衍生品，涵盖高定香氛美妆、冷制个护香皂、欧洲限定压纹饼干、庄园复刻酒具与联名人体工学电竞椅等实体收藏。",
    items: [
      {
        id: "house-of-sillage",
        name: "House of Sillage ×《新蝙蝠侠》奢华香氛与美妆系列",
        nameEn: "House of Sillage x The Batman Collection",
        maker: "House of Sillage",
        year: "2022",
        spec: "Hero / Vengeance 香水 · 领结口红匣 · 香氛蜡烛",
        image: "/media/merch/lifestyle/house-of-sillage.jpg",
        imageAlt: "House of Sillage 2022 年《新蝙蝠侠》香氛与美妆：Hero、Vengeance 香水瓶、领结口红匣与蜡烛",
        body: "高定香水品牌 House of Sillage 在 2022 年 3 月电影公映同期推出的官方限定美妆系列，涵盖「The Batman Hero」香水（镶嵌施华洛世奇水晶蝙蝠徽与手工抛光法国玻璃）、「The Batman Vengeance」乌木香水、蝴蝶结造型口红套及香氛蜡烛，完美呼应电影深沉浓烈的黑红视觉风格。",
        sourceUrl: "https://www.dc.com/blog/2022/01/10/warner-media-global-brands-and-experiences-to-launch-robust-batman-film-product-collection",
        sourceLabel: "DC / WarnerMedia 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "emilie-heathe",
        name: "Emilie Heathe ×《新蝙蝠侠》限定美甲系列",
        nameEn: "Emilie Heathe x The Batman Nail Collection",
        maker: "Emilie Heathe",
        year: "2022",
        spec: "三色指甲油 + Knight Out 美甲工具套",
        image: "/media/merch/lifestyle/emilie-heathe.jpg",
        imageAlt: "Emilie Heathe × The Batman 三色指甲油与蝙蝠装饰美甲工具",
        body: "华纳新闻稿写明 2022 年 2 月 15 日在 emilieheathe.com 上线。三支角色色是 The Dark Night、Vengeance 与 Madness；另有 Knight Out 工具套，含贴纸、蝙蝠装饰水晶锉刀与夹。",
        sourceUrl: "https://www.dc.com/blog/2022/01/10/warner-media-global-brands-and-experiences-to-launch-robust-batman-film-product-collection",
        sourceLabel: "DC / WarnerMedia 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "dr-squatch",
        name: "Dr. Squatch ×《新蝙蝠侠》Batman / Riddler 限定香皂",
        nameEn: "Dr. Squatch Batman Bricc & Riddler Enigma",
        maker: "Dr. Squatch",
        year: "2022",
        spec: "两块套装 · 2022.03.04 · 约 20 美元",
        image: "/media/merch/lifestyle/dr-squatch.jpg",
        imageAlt: "Dr. Squatch 电影限定香皂：The Batman Bricc 与 The Riddler Enigma 包装",
        body: "男士个护品牌 Dr. Squatch 在电影公映档推出的限定天然冷制香皂套装，包含采用活性炭与浮石配方的黑红包装「The Batman Bricc」，以及绿色问号封套的「The Riddler Enigma」，设计深度融入哥谭黑暗侦探基调。",
        sourceUrl: "https://www.dc.com/blog/2022/01/10/warner-media-global-brands-and-experiences-to-launch-robust-batman-film-product-collection",
        sourceLabel: "DC / WarnerMedia 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "oreo-batman",
        name: "OREO ×《新蝙蝠侠》电影限定包装与蝙蝠压纹饼干",
        nameEn: "OREO x The Batman Limited Edition",
        maker: "OREO · Mondelēz Europe",
        year: "2022",
        spec: "欧洲限定 · 首次角色压纹 · 包装含蝙蝠洞解谜二维码",
        image: "/media/merch/lifestyle/oreo-batman.jpg",
        imageAlt: "欧洲发行的 OREO × The Batman 限定包装，饼干压有蝙蝠徽而非经典 Oreo 字样",
        body: "亿滋在欧洲多个国家推出的《新蝙蝠侠》电影限定联名版奥利奥。特制饼干表面浮雕冲压了罗伯特·帕丁森版蝙蝠侠的侧影面罩图案，包装附带专属二维码可联动开启线上虚拟蝙蝠洞解谜互动。",
        sourceUrl: "https://www.dc.com/blog/2022/01/10/warner-media-global-brands-and-experiences-to-launch-robust-batman-film-product-collection",
        sourceLabel: "DC / WarnerMedia 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "wayne-glassware",
        name: "Wayne Monogram《新蝙蝠侠》酒具系列",
        nameEn: "THE BATMAN Wayne Monogram Glassware",
        maker: "DC Shop",
        year: "2022",
        spec: "两套礼物盒 · 相思木高杯套 / 橡木箱低杯套",
        image: "/media/merch/lifestyle/wayne-glassware.jpg",
        imageAlt: "DC Shop Wayne Monogram 酒具：相思木礼盒、韦恩字母 W 高杯与开瓶器",
        body: "华纳 DC 官方商店为电影公映推出的韦恩家族定制酒具，包含木盒威士忌醒酒器套装与高球杯套组。杯体与木盒均精致镌刻韦恩家族经典花体「W」暗纹，质感沉稳厚重。",
        sourceUrl: "https://shop.dc.com/products/the-batman-wayne-monogram-beverage-glass-gift-set",
        sourceLabel: "DC Shop 官方产品页",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "secretlab-batman",
        name: "Secretlab TITAN Evo 2022 电影联名电竞椅",
        nameEn: "Secretlab TITAN Evo 2022 The Batman Edition",
        maker: "Secretlab",
        year: "2022",
        spec: "TITAN Evo · S / R / XL · NEO Hybrid Leatherette · 磁吸蝙蝠徽",
        image: "/media/merch/secretlab-batman.jpg",
        imageAlt: "Secretlab TITAN Evo 2022《新蝙蝠侠》联名椅，靠背磁吸电影版蝙蝠徽",
        body: "Secretlab 为 2022 电影专门打造的 TITAN Evo 联名电竞椅，通体采用纯黑 NEO Hybrid 哑光人造皮革与打孔细节，椅背点缀暗红战术滚边，并首次创新配备了磁吸可拆卸的 2022 款战术蝙蝠徽标。",
        verifiedAt: "2026.09.14",
      },
    ],
  },
  {
    id: "toys",
    kicker: "12",
    title: "大众玩具与服装周边",
    titleEn: "Mass-Market Toys & Costumes",
    intro:
      "收录 Spin Master、Rubies 等品牌在 2022 年电影同期推出的量产级儿童玩具、声光遥控战车及官方授权 Cosplay 影视道具服装。",
    items: [
      {
        id: "spinmaster-figures",
        name: "Spin Master 4 寸电影可动人偶线",
        nameEn: "Spin Master 4-Inch The Batman Figures",
        maker: "Spin Master",
        year: "2022",
        spec: "约 10 cm · 蝙蝠侠 / 翼装蝙蝠侠 / 瑟琳娜 / 企鹅人",
        image: "/media/merch/toys/spinmaster-figures.jpg",
        imageAlt: "Spin Master 4 寸电影线：蝙蝠侠、翼装蝙蝠侠、瑟琳娜·凯尔与企鹅人及配件",
        body: "Spin Master 在电影上映期推出的 4 英寸入门级可动人偶系列，包含战甲版蝙蝠侠、翼装版、猫女瑟琳娜与企鹅人，每款角色均附带专属装备配件与破案揭秘线索卡。",
        sourceUrl: "https://www.dc.com/blog/2022/01/10/warner-media-global-brands-and-experiences-to-launch-robust-batman-film-product-collection",
        sourceLabel: "DC / WarnerMedia 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "spinmaster-12",
        name: "Spin Master 12 寸电影人偶线",
        nameEn: "Spin Master 12-Inch The Batman Figures",
        maker: "Spin Master",
        year: "2022",
        spec: "12 寸 · 蝙蝠侠 / 翼装蝙蝠侠 / 瑟琳娜",
        image: "/media/merch/toys/spinmaster-12.jpg",
        imageAlt: "Spin Master 12 寸电影人偶：蝙蝠侠、翼装蝙蝠侠与瑟琳娜·凯尔",
        body: "Spin Master 推出的 12 英寸大比例基础可动人偶，精准还原 2022 年大银幕中蝙蝠侠战甲胸徽与披风造型，具备扎实的关节结构，主打量产把玩与陈列展示。",
        sourceUrl: "https://www.dc.com/blog/2022/01/10/warner-media-global-brands-and-experiences-to-launch-robust-batman-film-product-collection",
        sourceLabel: "DC / WarnerMedia 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "spinmaster-batmobile",
        name: "Spin Master 4 寸声光蝙蝠战车",
        nameEn: "Spin Master 4-Inch Scale Batmobile",
        maker: "Spin Master",
        year: "2022",
        spec: "4 寸比例 · LED 与音效 · 附独家全黑 4 寸蝙蝠侠",
        image: "/media/merch/toys/spinmaster-batmobile.jpg",
        imageAlt: "Spin Master 4 寸电影蝙蝠战车玩具，可开门，附 4 寸蝙蝠侠人偶",
        body: "华纳新闻稿写明的 4 寸比例战车，定价约 32.99 美元。车灯、底盘可亮，带音效，车门可开，可放入 4 寸人偶；套装含一款全黑战衣的独家 4 寸蝙蝠侠。货架级声光玩具战车，比例与电子结构均不同于美泰 Hot Wheels 1:10 遥控车与 Jazzinc 1/6 收藏车模。",
        sourceUrl: "https://www.dc.com/blog/2022/01/10/warner-media-global-brands-and-experiences-to-launch-robust-batman-film-product-collection",
        sourceLabel: "DC / WarnerMedia 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "spinmaster-turbo-boost",
        name: "Spin Master Turbo Boost 遥控蝙蝠战车",
        nameEn: "Spin Master Turbo Boost Batmobile RC",
        maker: "Spin Master",
        year: "2022",
        spec: "遥控车 · 可翘头 · 约 48.99 美元",
        image: "/media/merch/toys/spinmaster-turbo-boost.jpg",
        imageAlt: "Spin Master Turbo Boost 电影蝙蝠战车遥控玩具与手柄",
        body: "华纳新闻稿单独列出的 Turbo Boost 遥控战车，定价约 48.99 美元，强调加速与翘头。造型按 2022 年肌肉车蝙蝠战车，电子结构独立于美泰 Hot Wheels R/C 1:10（HCD19）。",
        sourceUrl: "https://www.dc.com/blog/2022/01/10/warner-media-global-brands-and-experiences-to-launch-robust-batman-film-product-collection",
        sourceLabel: "DC / WarnerMedia 官方新闻稿",
        sourceTier: "official",
        verifiedAt: "2026.09.14",
      },
      {
        id: "rubies-batman",
        name: "Rubies《新蝙蝠侠》官方 Batman 服装",
        nameEn: "Rubies The Batman Costume",
        maker: "Rubies",
        year: "2022",
        spec: "成人 Deluxe / 儿童款 · 2022 电影头套",
        image: "/media/merch/toys/rubies-batman.jpg",
        imageAlt: "Rubies 官方《新蝙蝠侠》成人服装，电影版头套与战术披风",
        body: "华纳合作名单里的 Rubies 负责成人与儿童服装。确认实物的是按 2022 年电影头套与战术披风做的 Batman 装，成人 Deluxe 与儿童款同属这一季授权。",
        verifiedAt: "2026.09.14",
      },
      {
        id: "rubies-catwoman",
        name: "Rubies《新蝙蝠侠》官方 Catwoman 服装",
        nameEn: "Rubies The Batman Catwoman Costume",
        maker: "Rubies",
        year: "2022",
        spec: "电影版猫女装 · 护目镜头套",
        image: "/media/merch/toys/rubies-catwoman.jpg",
        imageAlt: "Rubies 官方《新蝙蝠侠》Catwoman 服装，护目镜头套与紫色内衬",
        body: "同一季 Rubies 电影授权里的猫女装，头套按佐伊·克罗维兹版护目镜。成人与儿童都有授权服装。",
        verifiedAt: "2026.09.14",
      },
    ],
  },
  {
    id: "miniatures",
    kicker: "13",
    title: "桌游与战棋",
    titleEn: "Tabletop Miniatures",
    intro:
      "收录西班牙模型厂牌 Knight Models 获华纳官方授权、基于马特·里夫斯《新蝙蝠侠》电影宇宙打造的「蝙蝠侠微缩模型战棋」（Batman Miniature Game，简称 BMG）全系产品。涵盖 2022 年 35mm 实体双人入门对战盒、单兵与载具扩展包，以及 2026 年通过 Gotham Lord 发行的官方数字 3D 打印模型（STL）与衍生剧《企鹅人》专属扩展。",
    items: [
      {
        id: "km-bmg-starter",
        name: "Knight Models《新蝙蝠侠》双人入门盒",
        nameEn: "Batman Miniature Game: The Batman Two-Player Starter Box",
        maker: "Knight Models",
        year: "2022",
        spec: "BMG019 · 35 mm 热塑性塑料 · 17 件人仔 · 2022.05.27 发售",
        image: "/media/merch/knight-models/the-batman-starter.jpg",
        imageAlt: "Knight Models《新蝙蝠侠》双人入门盒官方涂装群像：电影版蝙蝠侠、猫女、企鹅人、戈登、法尔科内与 GCPD、黑帮打手",
        body: "Knight Models 为 2022 年电影特别开模打造的 BMG 第三版双人对战入门盒（货号 BMG019）。全套包含 17 尊 35mm 比例高精度热塑性塑料白模人仔：正义阵营由蝙蝠侠、猫女、吉姆·戈登及哥谭警局警员组成，反派阵营则由企鹅人、卡迈恩·法尔科内及其黑帮暴徒坐镇。盒内配备完整核心规则书、61 张卡牌（战术/遭遇/任务目标）、地形指示物、特制测量尺与骰子；早期预购玩家另附赠布鲁斯·韦恩便服流浪者（The Drifter）限定特典人仔。",
        sourceUrl: "https://comicbook.com/gaming/news/batman-matt-reeves-miniatures-game/",
        sourceLabel: "ComicBook · Knight Models 电影入门盒",
        sourceTier: "press",
        verifiedAt: "2026.09.15",
      },
      {
        id: "km-riddler-followers",
        name: "Knight Models 电影版谜语人追随者",
        nameEn: "Batman Miniature Game: The Riddler Followers (The Batman)",
        maker: "Knight Models",
        year: "2022",
        spec: "35DC332 · 35 mm 热塑性塑料 · 3 件人仔 · 30 mm 底座",
        image: "/media/merch/knight-models/the-batman-riddler-followers.jpg",
        imageAlt: "Knight Models 电影版谜语人三名追随者官方涂装：护目镜、脏污面具与军绿雨衣",
        body: "2022 年 8 月推出的反派小队扩展包（货号 35DC332）。忠实还原电影高潮戏中效忠于谜语人的极端暴徒追随者：三人均身着军绿连帽雨衣与战术背心，分别佩戴滑雪护目镜、重度污渍皮面罩与战术防尘面具，手持猎枪与重型撬棍，适配 30mm 战棋标准底座。",
        sourceUrl: "https://www.beastsofwar.com/news/knight-models-10-years-batman-anniversary-minis/",
        sourceLabel: "OnTableTop · Knight Models 电影版谜语人追随者",
        sourceTier: "press",
        verifiedAt: "2026.09.15",
      },
      {
        id: "km-riddler",
        name: "Knight Models 电影版谜语人",
        nameEn: "Batman Miniature Game: The Riddler (The Batman)",
        maker: "Knight Models",
        year: "2022",
        spec: "35DC333 · 35 mm 热塑性塑料 · 1 件人仔 · 40 mm 底座",
        image: "/media/merch/knight-models/the-batman-riddler.jpg",
        imageAlt: "Knight Models 电影版谜语人官方涂装：军绿雨衣、战术背心、条纹袖套，手持炸药与笔记本",
        body: "电影版谜语人独立领袖扩展（货号 35DC333）。模型生动再现保罗·达诺在片中的压迫感形象：军绿作战雨衣外罩多功能胸挂背心，手部带有绝缘胶带缠裹与红白条纹袖套，左手紧握密电记事本，右手持引爆遥控器，配有专属 40mm 战棋底座。",
        sourceUrl: "https://www.beastsofwar.com/news/knight-models-10-years-batman-anniversary-minis/",
        sourceLabel: "OnTableTop · Knight Models 电影版谜语人",
        sourceTier: "press",
        verifiedAt: "2026.09.15",
      },
      {
        id: "km-batman-on-bike",
        name: "Knight Models《新蝙蝠侠》Batman On Bike",
        nameEn: "Batman Miniature Game: Batman On Bike",
        maker: "Knight Models",
        year: "2022",
        spec: "35DC358 · 35 mm 热塑性塑料 · Batman + Batcycle · 椭圆底座",
        image: "/media/merch/knight-models/the-batman-on-bike.jpg",
        imageAlt: "Knight Models《新蝙蝠侠》Batman On Bike 官方涂装：帕丁森战甲蝙蝠侠骑乘电影蝙蝠摩托",
        body: "Knight Models 推出的电影重型载具战棋单品（货号 35DC358）。模型将罗伯特·帕丁森版战甲蝙蝠侠与电影改装版蝙蝠摩托（Batcycle）融为一体，刻画了义警在雨夜街头风驰电掣、低伏压弯的动感瞬间，配备专属大号椭圆战棋底座。",
        sourceUrl: "https://www.ontabletop.com/knight-models/batmans-rogues-gallery-knight-models-this-month/",
        sourceLabel: "OnTableTop · Knight Models Batman On Bike",
        sourceTier: "press",
        verifiedAt: "2026.09.15",
      },
      {
        id: "km-batman-stl-2026",
        name: "Knight Models 电影版蝙蝠侠 2026 数字 STL",
        nameEn: "Batman Miniature Game: Batman – The Batman (Digital STL)",
        maker: "Knight Models",
        year: "2026",
        spec: "Digital STL · Gotham Lord 2026.07 · 32–35 mm · 树脂打印",
        image: "/media/merch/knight-models/the-batman-stl-2026.jpg",
        imageAlt: "Knight Models 2026 数字 STL：电影版战术战甲蝙蝠侠官方涂装展示",
        body: "Knight Models 官方 3D 打印数字工坊（MyMiniFactory Gotham Lord 部落）于 2026 年 7 月发行的官方数字 STL 雕模。按 32–35mm 桌面战棋标准比例制作，数字版提供预加支撑与原始无支撑两种高精度 STL 文件，专供玩家通过光固化树脂打印自行涂装。",
        sourceUrl: "https://miniset.net/sets/km-mmf841290",
        sourceLabel: "Miniset · Knight Models Gotham Lord STL",
        sourceTier: "archive",
        verifiedAt: "2026.09.15",
      },
      {
        id: "km-catwoman-stl-2026",
        name: "Knight Models 电影版猫女 2026 数字 STL",
        nameEn: "Batman Miniature Game: Catwoman – The Batman (Digital STL)",
        maker: "Knight Models",
        year: "2026",
        spec: "Digital STL · Gotham Lord 2026.07 · 32–35 mm · 树脂打印",
        image: "/media/merch/knight-models/the-batman-catwoman-stl-2026.jpg",
        imageAlt: "Knight Models 2026 数字 STL：电影版猫女官方涂装展示",
        body: "官方 2026 年数字再发行的猫女 3D 打印模型。忠实重现佐伊·克罗维兹在电影中的利落短发、猫耳滑雪面罩与皮质紧身作战服轮廓，手握皮鞭处于伺机突袭姿态，为高精度光固化打印提供完善支撑切片。",
        sourceUrl: "https://miniset.net/sets/km-mmf841291",
        sourceLabel: "Miniset · Knight Models Gotham Lord STL",
        sourceTier: "archive",
        verifiedAt: "2026.09.15",
      },
      {
        id: "km-gordon-stl-2026",
        name: "Knight Models 电影版戈登 2026 数字 STL",
        nameEn: "Batman Miniature Game: Lt. Gordon – The Batman (Digital STL)",
        maker: "Knight Models",
        year: "2026",
        spec: "Digital STL · Gotham Lord 2026.07 · 32–35 mm · 树脂打印",
        image: "/media/merch/knight-models/the-batman-gordon-stl-2026.jpg",
        imageAlt: "Knight Models 2026 数字 STL：电影版吉姆·戈登官方涂装展示",
        body: "杰弗里·怀特版吉姆·戈登副中尉的官方 3D 打印数字模型。模型还原了戈登身穿侦探经典防雨风衣、佩戴标志性框架眼镜并在暴雨夜持枪戒备的正义刑警姿态，细节丰富锐利。",
        sourceUrl: "https://miniset.net/sets/km-mmf841293",
        sourceLabel: "Miniset · Knight Models Gotham Lord STL",
        sourceTier: "archive",
        verifiedAt: "2026.09.15",
      },
      {
        id: "km-drifter-stl-2026",
        name: "Knight Models「Drifter」布鲁斯 2026 数字 STL",
        nameEn: "Batman Miniature Game: Bruce Wayne – The Drifter (Digital STL)",
        maker: "Knight Models",
        year: "2026",
        spec: "Digital STL · Gotham Lord 2026.07 · 32–35 mm · 树脂打印",
        image: "/media/merch/knight-models/the-batman-drifter-stl-2026.jpg",
        imageAlt: "Knight Models 2026 数字 STL：电影版 Drifter 布鲁斯·韦恩官方涂装展示",
        body: "曾作为 2022 年实体入门盒首发限定预购特典的「流浪者」便服布鲁斯·韦恩，于 2026 年首次以官方数字 STL 形式解禁发行。模型还原了布鲁斯身穿厚重工装夹克、头戴兜帽、背负战术双肩包融入哥谭街头的便服潜行形象。",
        sourceUrl: "https://www.myminifactory.com/object/3d-print-bruce-wayne-the-drifter-batman-miniature-game-836154",
        sourceLabel: "MyMiniFactory · Knight Models Drifter STL",
        sourceTier: "official",
        verifiedAt: "2026.09.15",
      },
      {
        id: "km-batman-on-bike-stl-2026",
        name: "Knight Models Batman On Bike 2026 数字 STL",
        nameEn: "Batman Miniature Game: Batman On Bike – The Batman (Digital STL)",
        maker: "Knight Models",
        year: "2026",
        spec: "Digital STL · Gotham Lord 2026.07 · 32–35 mm · 树脂打印",
        image: "/media/merch/knight-models/the-batman-on-bike-stl-2026.jpg",
        imageAlt: "Knight Models 2026 数字 STL：电影版 Batman On Bike 官方涂装展示",
        body: "2026 年官方数字发布的重载机车战棋模型。完整继承了 2022 年实体版 35DC358 的精湛雕模，高精度重现美式复古改装机车外露引擎细节与蝙蝠侠披风随风飘拂的动态，提供树脂打印专用支撑切片。",
        sourceUrl: "https://miniset.net/sets/km-mmf836162",
        sourceLabel: "Miniset · Knight Models Gotham Lord STL",
        sourceTier: "archive",
        verifiedAt: "2026.09.15",
      },
      {
        id: "km-riddler-stl-2026",
        name: "Knight Models 电影版谜语人 2026 数字 STL",
        nameEn: "Batman Miniature Game: The Riddler – The Batman (Digital STL)",
        maker: "Knight Models",
        year: "2026",
        spec: "Digital STL · Gotham Lord 2026.07 · 32–35 mm · 树脂打印",
        image: "/media/merch/knight-models/the-batman-riddler-stl-2026.jpg",
        imageAlt: "Knight Models 2026 数字 STL：电影版谜语人官方涂装展示",
        body: "保罗·达诺版谜语人的官方数字 3D 打印切片模型。完美复刻战术雨衣绑带与密电笔记本细节，支持桌面战棋玩家以光固化树脂打印出分毫毕现的微缩模型。",
        sourceUrl: "https://www.myminifactory.com/object/3d-print-the-riddler-the-batman-batman-miniature-game-836153",
        sourceLabel: "MyMiniFactory · Knight Models 电影版谜语人 STL",
        sourceTier: "official",
        verifiedAt: "2026.09.15",
      },
      {
        id: "km-penguin-stl-2026",
        name: "Knight Models 电影版企鹅人 2026 数字 STL",
        nameEn: "Batman Miniature Game: The Penguin – The Batman (Digital STL)",
        maker: "Knight Models",
        year: "2026",
        spec: "Digital STL · Gotham Lord 2026.06 · 32–35 mm · 树脂打印",
        image: "/media/merch/knight-models/the-batman-penguin-stl-2026.jpg",
        imageAlt: "Knight Models 2026 数字 STL：电影版企鹅人官方涂装展示",
        body: "科林·法瑞尔版奥兹·科布的官方 3D 打印数字模型。精准还原冰山俱乐部时期奥兹身着条纹衬衫、暗纹皮西装夹克的经典微胖身躯与微跛站姿，手持短管猎枪，极富枭雄神韵。",
        sourceUrl: "https://www.myminifactory.com/object/3d-print-the-penguin-the-batman-836023",
        sourceLabel: "MyMiniFactory · Knight Models 电影版企鹅人 STL",
        sourceTier: "official",
        verifiedAt: "2026.09.15",
      },
      {
        id: "km-falcone-stl-2026",
        name: "Knight Models 电影版法尔科内 2026 数字 STL",
        nameEn: "Batman Miniature Game: Carmine Falcone – The Batman (Digital STL)",
        maker: "Knight Models",
        year: "2026",
        spec: "Digital STL · Gotham Lord 2026.06 · 32–35 mm · 树脂打印",
        image: "/media/merch/knight-models/the-batman-falcone-stl-2026.jpg",
        imageAlt: "Knight Models 2026 数字 STL：电影版卡迈恩·法尔科内官方涂装展示",
        body: "约翰·特托罗版黑道教父卡迈恩·法尔科内的官方数字模型。细致刻画了其标志性的墨镜、大衣与老派黑帮领袖沉稳阴鸷的神态，彰显掌控哥谭数十载的地下秩序操盘手威仪。",
        sourceUrl: "https://www.myminifactory.com/object/3d-print-carmine-falcone-the-batman-836011",
        sourceLabel: "MyMiniFactory · Knight Models 电影版法尔科内 STL",
        sourceTier: "official",
        verifiedAt: "2026.09.15",
      },
      {
        id: "km-sofia-falcone-stl-2026",
        name: "Knight Models《企鹅人》Sofia Falcone 2026 数字 STL",
        nameEn: "Batman Miniature Game: Sofia Falcone – The Penguin (Digital STL)",
        maker: "Knight Models",
        year: "2026",
        spec: "Digital STL · Gotham Lord 2026.06 · MMF Exclusive · 32–35 mm",
        image: "/media/merch/knight-models/the-penguin-sofia-falcone-stl-2026.jpg",
        imageAlt: "Knight Models《企鹅人》Sofia Falcone 官方 STL 宣传图：短发礼服、围巾、手枪与梳妆台场景底座",
        body: "Knight Models 紧扣 HBO 限定剧《企鹅人》推出的当月限定官方数字 STL。模型生动再现克里斯汀·米利欧缇（Cristin Milioti）饰演的索菲亚·法尔科内在阿卡姆出狱后的冷艳霸气形象：波浪短卷发、奢华剪裁礼服大衣搭配丝巾，右手持消音手枪，附带带有梳妆镜与地毯细节的专属室内微缩场景底座。",
        sourceUrl: "https://www.myminifactory.com/object/3d-print-sofia-falcone-the-penguin-mmf-exclusive-835971",
        sourceLabel: "MyMiniFactory · Knight Models Sofia Falcone STL",
        sourceTier: "official",
        verifiedAt: "2026.09.15",
      },
    ],
  },
];

export const MERCH_TEASERS = [MERCH[0].items[0], MERCH[1].items[0], MERCH[2].items[0]];
