export type MerchItem = {
  id: string;
  name: string;
  nameEn: string;
  maker: string;
  year: string;
  spec: string;
  image: string;
  imageAlt: string;
  body: string;
  sourceUrl?: string;
  sourceLabel?: string;
  verifiedAt?: string;
};

export type MerchGroup = {
  id: string;
  kicker: string;
  title: string;
  titleEn: string;
  intro: string;
  items: MerchItem[];
};

export const MERCH: MerchGroup[] = [
  {
    id: "figures",
    kicker: "01",
    title: "可动人偶",
    titleEn: "Action Figures",
    intro:
      "收录官方授权的 1/6 收藏级可动、1/12 日系与美系小比例可动、1/9 中档量产、7 寸零售可动及电影同期玩具，注重头雕还原、战衣剪裁与把玩配件。",
    items: [
      {
        id: "inart-action",
        name: "INART Action 1/12 蝙蝠侠可动人偶",
        nameEn: "The Batman Action Figure (Hg M0006)",
        maker: "INART Action",
        year: "2026",
        spec: "约 1/12 比例 · 全高约 16.2 cm · 预订，预计 2026 年第四季出货",
        image: "/media/merch/inart-action.jpg",
        imageAlt: "INART Action 1/12 电影版蝙蝠侠可动人偶官方产品图，戴头套全身站姿",
        body: "INART 小比例线 INART Action 推出的华纳授权电影版蝙蝠侠。三款头雕（戴面罩平静、戴面罩愤怒、露脸布鲁斯），可替换胸甲，十三只手型，铁丝布料披风。配件含空头套、抓钩发射器开合两态、黏弹枪、肾上腺素、手电筒、紫外灯、笔记本电脑与两款蝙蝠镖。含地台约 15×15×16.9 cm。",
        sourceUrl: "https://global.inart.studio/products/the-batman-batman-action-figure",
        sourceLabel: "INART 官方产品页",
        verifiedAt: "2026.09.08",
      },
      {
        id: "lpzz",
        name: "良品制造 1/12 蝙蝠侠可动人偶",
        nameEn: "The Batman (2022) 1/12 Scale (DC007)",
        maker: "良品制造 · U-P-Finegures / LPZZ",
        year: "2026",
        spec: "1/12 比例 · 编号 DC007 · 预订，预计 2026 年第四季出货",
        image: "/media/merch/lpzz.jpg",
        imageAlt: "良品制造 1/12 电影版蝙蝠侠可动人偶，露脸头雕与战术配件",
        body: "良品制造（U-P-Finegures，亦称 LPZZ）1/12 比例电影造型。露脸布鲁斯头雕、空头套、十二只手型。配件含三款蝙蝠镖、撬具、手铐、手持电脑、抓钩枪两把、抓钩、肾上腺素、手电筒、紫外灯、信号棒与黏弹枪，另附支架与地台。战衣按第一部多层战术甲还原。图为开发样板，成品以出货为准。",
        sourceUrl: "https://onesixthoutfitters.com/lpzz-dc007-1-12-scale-the-batman-2022-batman-figure/",
        sourceLabel: "经销商产品页",
        verifiedAt: "2026.09.08",
      },
      {
        id: "mafex",
        name: "MAFEX No.188 电影版蝙蝠侠",
        nameEn: "MAFEX No.188 THE BATMAN",
        maker: "Medicom Toy · 株式会社メディコム・トイ",
        year: "2023",
        spec: "全高约 160 mm · 布制可动披风 · 头部零件 4 种",
        image: "/media/merch/mafex.jpg",
        imageAlt: "MAFEX No.188 电影版蝙蝠侠可动人偶，举起抓钩发射器的官方产品图",
        body: "Medicom Toy マフェックス线推出的华纳授权电影造型。全高约 160 毫米，头部原型岛崎恭一、本体 PERFECT-STUDIO。附头部零件 4 种、内置铁丝的布制披风、剧中武器零件与可动支架，可摆出电影动作场面。2023 年 10 月日本发售，后有再版。与 INART Action、良品制造同属 1/12 左右收藏线。",
        sourceUrl: "https://www.1999.co.jp/10905264",
        sourceLabel: "Hobby Search 产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "shf",
        name: "S.H.Figuarts 蝙蝠侠「世界最高的侦探」",
        nameEn: "S.H.Figuarts Batman “The World's Greatest Detective”",
        maker: "BANDAI SPIRITS · 魂ウェブ / TAMASHII NATIONS STORE",
        year: "2024",
        spec: "全高约 160 mm · 魂ストア限定 · 布制披风",
        image: "/media/merch/shf.jpg",
        imageAlt: "S.H.Figuarts 魂ストア限定电影版蝙蝠侠，布披风与战术甲官方产品图",
        body: "2024 年 11 月 15 日发售的 TAMASHII NATIONS STORE 限定版，比早期店售 SHF 更贴近剧中配色。PVC／ABS／布制，全高约 160 毫米。套装含本体、可替换胸甲、左右各 5 种手型、左右抓钩发射器与 Bat Knife；披风内置铁丝，可做出被风掀起的姿态。",
        sourceUrl: "https://tamashiiweb.com/item/15022/",
        sourceLabel: "魂ウェブ官方产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "mezco",
        name: "Mezco One:12 Collective 电影版蝙蝠侠",
        nameEn: "One:12 Collective The Batman",
        maker: "Mezco Toyz",
        year: "2022",
        spec: "约 17 cm · 30 处以上可动 · 4 款头雕",
        image: "/media/merch/mezco.jpg",
        imageAlt: "Mezco One:12 Collective 电影版蝙蝠侠全身站姿与布披风官方产品图",
        body: "Mezco 软服路线的 1/12 集体系列。约 17 厘米，超过 30 处关节，四款头雕含罗伯特·帕丁森露脸布鲁斯。战衣含铁丝披风、可拆翼装、护臂、工具腰带与大腿袋。配件含黏弹发射器、蝙蝠镖、手铐、紫外灯、收放两态抓钩、肾上腺素、烟雾弹等，是与 MAFEX、SHF 硬塑路线对照的代表性电影授权款。",
        sourceUrl: "https://www.mezcotoyz.com/one-12-collective-the-batman",
        sourceLabel: "Mezco Toyz 官方产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "dah117",
        name: "Beast Kingdom DAH-117 电影版蝙蝠侠",
        nameEn: "Dynamic 8ction Heroes DAH-117 Batman (The Batman)",
        maker: "Beast Kingdom · 野獸國",
        year: "2025",
        spec: "1/9 比例 · 全高约 21 cm · 约 22 处可动",
        image: "/media/merch/dah117.jpg",
        imageAlt: "Beast Kingdom DAH-117 电影版蝙蝠侠可动人偶官方宣传图",
        body: "台湾野獸國 Dynamic 8ction Heroes 中档量产线。全高约 21 厘米、约 22 处关节，布制披风，头雕按帕丁森面容塑造。配件含三组替换手型、蝙蝠镖，以及收起／展开两态抓钩发射器。日本地区 2025 年 2 月发售，包装纪念蝙蝠侠八十五周年。补上 2022 高端线之外的中档授权可动。",
        sourceUrl: "https://beast-kingdom.us/dah-117-batman-the-batman.html",
        sourceLabel: "Beast Kingdom 官方产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "inart",
        name: "INART 1/6 蝙蝠侠珍藏人偶",
        nameEn: "The Batman 1/6 Collectible Figure",
        maker: "INART · Queen Studios",
        year: "2023",
        spec: "1/6 比例 · 常规版 / 植发豪华版",
        image: "/media/merch/inart.jpg",
        imageAlt: "INART 1/6 蝙蝠侠全身官方产品展示图",
        body: "Queen Studios 旗下高端可动厂牌 INART 出品。配备独立可动眼球系统与多款替换表情，豪华版特别附带手工植发头雕。战衣严格按照电影多层结构剪裁制作，细致还原防弹护甲与布料质感。",
        sourceUrl: "https://queenstudios.shop/products/batman-1-6-collectible-figure",
        sourceLabel: "Queen Studios / INART 产品页",
        verifiedAt: "2026.08.24",
      },
      {
        id: "hottoys",
        name: "Hot Toys 蝙蝠侠与蝙蝠信号灯套装",
        nameEn: "Batman and Bat-Signal Set",
        maker: "Hot Toys",
        year: "2022",
        spec: "1/6 比例 · MMS641 豪华套装",
        image: "/media/merch/hottoys.jpg",
        imageAlt: "Hot Toys 1/6 蝙蝠侠站在点亮的蝙蝠信号灯旁",
        body: "Hot Toys 推出的 1/6 比例人偶套装。配备全新开发的面罩头雕与可替换下半脸造型，豪华版特别附带可通电发光的 1/6 蝙蝠信号灯地台，以及抓钩枪、战术飞镖等武器配件。",
      },
      {
        id: "mcfarlane-batman",
        name: "麦克法兰 7 寸战衣版蝙蝠侠",
        nameEn: "Batman (The Batman) DC Multiverse",
        maker: "McFarlane Toys",
        year: "2022",
        spec: "7 寸比例 · 约 22 处可动",
        image: "/media/merch/mcfarlane-batman.jpg",
        imageAlt: "McFarlane 7 寸电影战衣版蝙蝠侠可动人偶",
        body: "DC Multiverse 电影第一波零售可动。7 寸比例、Ultra Articulation 约 22 处关节，按第一部战术甲与头套还原。与未戴面罩布鲁斯、谜语人、企鹅人、猫女同属 2022 年电影量产阵容。",
      },
      {
        id: "mcfarlane-bruce",
        name: "麦克法兰 7 寸未戴面罩布鲁斯·韦恩",
        nameEn: "Bruce Wayne Unmasked (The Batman)",
        maker: "McFarlane Toys",
        year: "2022",
        spec: "7 寸比例可动人偶",
        image: "/media/merch/mcfarlane-bruce.jpg",
        imageAlt: "McFarlane 7 寸未戴面罩布鲁斯人偶包装与配件",
        body: "DC Multiverse 第二波推出的便装／头套掀起造型。还原帕丁森版布鲁斯的眼妆与战术甲，约 22 处可动，附蝙蝠镖与地台。官方产品页标注为 Batman Unmasked (The Batman)。",
        sourceUrl: "https://mcfarlane.com/toys/batman-unmasked-batman/",
        sourceLabel: "McFarlane Toys 官方产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "mcfarlane-riddler",
        name: "麦克法兰 7 寸谜语人",
        nameEn: "The Riddler – The Batman (Movie)",
        maker: "McFarlane Toys",
        year: "2022",
        spec: "7 寸比例 · 约 22 处可动 · 附破冰锥",
        image: "/media/merch/mcfarlane-riddler.jpg",
        imageAlt: "McFarlane 电影版谜语人冬装造型官方产品图",
        body: "按保罗·达诺在电影中的战斗服与雨衣造型制作。7 寸、约 22 处可动，配件为破冰锥（ice picker）与地台，附角色收藏卡。与雕像区的 1/6 树脂谜语人是同一角色的不同产品线。",
        sourceUrl: "https://mcfarlane.com/toys/riddler-the-batman-movie/",
        sourceLabel: "McFarlane Toys 官方产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "mcfarlane-penguin",
        name: "麦克法兰 7 寸企鹅人",
        nameEn: "The Penguin (The Batman)",
        maker: "McFarlane Toys",
        year: "2022",
        spec: "7 寸比例 · 约 22 处可动",
        image: "/media/merch/mcfarlane-penguin.jpg",
        imageAlt: "McFarlane 7 寸电影版企鹅人可动人偶，科林·法瑞尔造型",
        body: "按科林·法瑞尔在冰山俱乐部时期的企鹅人还原。7 寸、约 22 处可动，附替换手型与地台，以及正面摄影、背面角色小传的收藏卡。官方产品页将他写作 Oswald Cobblepot，Gotham 夜场老板。",
        sourceUrl: "https://mcfarlane.com/toys/the-penguin/",
        sourceLabel: "McFarlane Toys 官方产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "mcfarlane-catwoman",
        name: "麦克法兰 7 寸猫女（含未戴面罩版）",
        nameEn: "Catwoman / Catwoman Unmasked (The Batman)",
        maker: "McFarlane Toys",
        year: "2022",
        spec: "7 寸比例 · 约 22 处可动 · 戴面罩版与 Unmasked 版",
        image: "/media/merch/mcfarlane-catwoman.jpg",
        imageAlt: "McFarlane 7 寸电影版猫女未戴面罩可动人偶官方产品图",
        body: "电影授权猫女有两个独立 7 寸 SKU：第一波为戴面罩战衣；第二波 Catwoman Unmasked 按佐伊·克罗维兹露脸造型，附鞭子与地台，约 22 处可动。两版均带收藏卡，不宜再收进一条「核心阵容」笼统条目。",
        sourceUrl: "https://www.bigbadtoystore.com/product/batman-dc-multiverse-catwoman-unmasked-action-figure-100268",
        sourceLabel: "BigBadToyStore 产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "funko",
        name: "Funko Pop! 电影全套乙烯玩偶",
        nameEn: "Pop! Movies · The Batman Series",
        maker: "Funko",
        year: "2022",
        spec: "乙烯公仔 · 包含常规款与 Rides 战车款",
        image: "/media/merch/funko.jpg",
        imageAlt: "Funko 官方公布的《新蝙蝠侠》全套 Pop! 玩偶",
        body: "Funko 官方授权系列，以经典 Q 版大头造型重塑了蝙蝠侠、猫女、企鹅人、谜语人以及驾驶蝙蝠战车的 Pop! Rides 系列，是流传广泛的流行文化收藏品。",
      },
      {
        id: "spin-master",
        name: "Spin Master 4 寸蝙蝠侠与蝙蝠战车",
        nameEn: "4 Inch Batman & Batmobile",
        maker: "Spin Master",
        year: "2022",
        spec: "蝙蝠侠全高约 10 cm · 11 处可动 · 战车带声光",
        image: "/media/merch/spin-master.jpg",
        imageAlt: "Spin Master 4 寸电影版蝙蝠侠与可开门蝙蝠战车玩具套装",
        body: "电影上映同期的大众市场玩具，不是高端收藏线，但属于正规华纳授权。蝙蝠侠约 10 厘米、11 处可动、布披风；战车车轮可转、车门可开，可放入人偶，并带前灯／后置引擎发光与多种音效。用来对照 2022 年普通货架上实际出过什么。",
      },
    ],
  },
  {
    id: "props",
    kicker: "02",
    title: "电影道具复刻",
    titleEn: "Prop Replicas",
    intro:
      "基于华纳兄弟制片团队的原始数字模型与道具原件扫描数据打造的金属道具复刻，含 1:1 限量件与同系列缩比陈列版。",
    items: [
      {
        id: "fe-batarang",
        name: "Factory Entertainment 1:1 金属蝙蝠飞镖",
        nameEn: "The Batman Batarang Limited Edition Prop Replica",
        maker: "Factory Entertainment · 华纳官方授权",
        year: "2022",
        spec: "1:1 比例 · 实心压铸金属 · 钢琴烤漆亚克力展示盒",
        image: "/media/merch/fe-batarang.jpg",
        imageAlt: "Factory Entertainment 1:1 蝙蝠飞镖金属复刻道具与展示盒",
        body: "根据《新蝙蝠侠》制片组提供的原始数字资产打造。全尺寸纯金属铸造，表面施以手工战损与做旧效果，还原大银幕质感；附带专属编号金属铭牌与展示盒。",
        sourceUrl: "https://factoryent.com/products/the-batman-batarang-limited-edition-prop-replica",
        sourceLabel: "Factory Entertainment 产品页",
        verifiedAt: "2026.08.24",
      },
      {
        id: "fe-batarang-scaled",
        name: "Factory Entertainment 缩比金属蝙蝠飞镖",
        nameEn: "The Batman Batarang Scaled Prop Replica",
        maker: "Factory Entertainment · 华纳官方授权",
        year: "2022",
        spec: "全长约 7 英寸 · 实心金属 · 附展示架",
        image: "/media/merch/fe-batarang-scaled.jpg",
        imageAlt: "Factory Entertainment 7 英寸缩比金属蝙蝠飞镖与展示架",
        body: "同一道具的入门档：7 英寸（约 18×11×0.5 厘米）实心金属铸造，收藏包装并附展示架。不是 1:1 复刻，价格与体量都低于限量全尺寸版，用来把「道具复刻」从 1:1 金属件补成完整谱系。货号 408894，官方产品页仍在线。",
        sourceUrl: "https://factoryent.com/products/the-batman-batarang-scaled-prop-replica",
        sourceLabel: "Factory Entertainment 产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "paragon-glyph",
        name: "Paragon FX 1:1 胸甲可拆卸金属蝙蝠徽标",
        nameEn: "The Batman 2022 Bat Glyph 1:1 Metal Prop Replica",
        maker: "Paragon FX Group · 华纳官方授权",
        year: "2022",
        spec: "1:1 全尺寸 · 纯金属实心铸造 · 全球限量 750 件",
        image: "/media/merch/paragon-glyph.jpg",
        imageAlt: "Paragon FX 1:1 金属蝙蝠徽标双面与展开形态",
        body: "由 Paragon 依据电影道具原件 STL 文件 1:1 打造。全金属实心结构，忠实还原了胸甲徽记表面的细微机械纹理，并可按电影设定拆卸展开为双刃折叠战术刀。",
        sourceUrl: "https://paragonfxgroup.com/products/thebatman2022",
        sourceLabel: "Paragon FX 产品页",
        verifiedAt: "2026.08.24",
      },
      {
        id: "fe-grapnel",
        name: "Factory Entertainment 1:1 战术抓钩发射器",
        nameEn: "The Batman Grapple Launcher 1:1 Life-Size Prop Replica",
        maker: "Factory Entertainment · 华纳官方授权",
        year: "2022",
        spec: "1:1 比例 · 全金属铸造 · 全球限量 1500 件",
        image: "/media/merch/fe-grapnel.jpg",
        imageAlt: "Factory Entertainment 1:1 战术抓钩枪实物展示",
        body: "全尺寸 1:1 电影实体道具复刻，尺寸约 10×21×5 厘米。采用实心合金精密压铸，细致呈现了钢缆线轴、握把机械制动结构与战损涂装，配有展示盒与独立编号收藏证书。",
        sourceUrl: "https://factoryent.com/products/the-batman-grapple-launcher-limited-edition-prop-replica",
        sourceLabel: "Factory Entertainment 产品页",
        verifiedAt: "2026.08.24",
      },
    ],
  },
  {
    id: "statues",
    kicker: "03",
    title: "高端雕像",
    titleEn: "Statues",
    intro:
      "收录 1:1 等身硅胶胸像、博物馆级宝丽石全身像，以及 1/10、1/6 与 12 寸零售雕像，覆盖高端巨物到电影宣传视觉实体化。",
    items: [
      {
        id: "infinity-bust",
        name: "Infinity Studio 1:1 蝙蝠侠等身胸像",
        nameEn: "The Batman Life-Size Bust",
        maker: "Infinity Studio · 开天工作室 × Penguin Toys",
        year: "2022",
        spec: "1:1 等身 · 高约 93 cm · 全球限量 500 尊",
        image: "/media/merch/infinity-bust.jpg",
        imageAlt: "Infinity Studio 《新蝙蝠侠》1:1 等身胸像，滴水兽地台",
        body: "由开天工作室（Infinity Studio）与 Penguin Toys 联合打造。采用铂金硅胶头雕与医用级硅胶皮肤，战衣使用真皮与定制织物。全高约 93 厘米，地台按电影视觉做成哥谭滴水兽建筑，滴水兽可磁吸拆卸单独展示。全球限量 500 尊。",
        sourceUrl: "https://www.sideshow.com/collectibles/dc-comics-batman-infinity-studio-infinity-studio-910677",
        sourceLabel: "Sideshow 产品页",
        verifiedAt: "2026.08.24",
      },
      {
        id: "p1s",
        name: "Prime 1 Studio 1/3 博物馆级电影版蝙蝠侠",
        nameEn: "Museum Masterline × Blitzway",
        maker: "Prime 1 Studio × Blitzway",
        year: "2023",
        spec: "1/3 比例 · 高约 79 cm · 高级宝丽石树脂",
        image: "/media/merch/p1s.jpg",
        imageAlt: "Prime 1 Studio 与 Blitzway 合作的 1/3 蝙蝠侠全身雕像",
        body: "由 Prime 1 Studio 与 Blitzway 联手打造。全高约 79 厘米，细致还原了皮革纹理、硬质防弹板与金属磨损细节，准确再现帕丁森在电影中的冷峻神态。",
      },
      {
        id: "p1s-sae",
        name: "Prime 1 Studio 特殊艺术限定版雕像",
        nameEn: "Special Art Edition Deluxe",
        maker: "Prime 1 Studio",
        year: "2022",
        spec: "1/3 比例 · 高约 88 cm · 限量发行",
        image: "/media/merch/p1s-sae.jpg",
        imageAlt: "Prime 1 Studio 特殊艺术版红雨灯光效果全身雕像",
        body: "以传奇漫画家吉姆·李（Jim Lee）为 DC FanDome 创作的概念插画为灵感，结合电影实拍装甲细节，地台融合了哥谭标志性滴水兽雕塑与红雨氛围灯效。",
      },
      {
        id: "iron-studios",
        name: "Iron Studios Art Scale 1/10 电影版蝙蝠侠",
        nameEn: "The Batman Art Scale 1/10",
        maker: "Iron Studios",
        year: "2022",
        spec: "1/10 比例 · 高约 26 cm · 宝丽石手绘",
        image: "/media/merch/iron-studios.jpg",
        imageAlt: "Iron Studios 1/10 电影版蝙蝠侠雕像，战术甲与哥谭建筑地台",
        body: "按 2022 年电影战术甲制作的 Art Scale 1/10。Sideshow 公布全高约 10.2 英寸（约 26 厘米），宝丽石手绘，地台做成哥谭混凝土建筑并带蝙蝠徽。Prime 1 / Infinity 是万元级巨物，这一档把中小比例雕像补进档案。",
        sourceUrl: "https://www.sideshow.com/collectibles/dc-comics-the-batman-iron-studios-910601",
        sourceLabel: "Sideshow 产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "mcfarlane-gold",
        name: "麦克法兰 12 寸 Gold Label 摆件雕像",
        nameEn: "The Batman 12″ Posed Statue (Gold Label)",
        maker: "McFarlane Toys · DC Multiverse",
        year: "2022",
        spec: "12 寸摆件 · 红黑 Jim Lee 海报配色 · 滴水兽地台",
        image: "/media/merch/mcfarlane-gold.jpg",
        imageAlt: "McFarlane Gold Label 12 寸电影版蝙蝠侠雕像，红黑配色与滴水兽地台",
        body: "按吉姆·李为电影绘制的红黑宣传海报配色，而不是写实战衣涂装。12 寸摆件（非可动），附滴水兽地台、风格化背景板，以及正反面收藏卡。接近「电影宣传视觉实体化」，体量低于 Prime 1，更适合作为档案向展品。",
        sourceUrl: "https://mcfarlane.com/toys/batman-12-posed-statue-gold-label/",
        sourceLabel: "McFarlane Toys 官方产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "mcfarlane-riddler-statue",
        name: "麦克法兰 DC Direct 1/6 谜语人树脂像",
        nameEn: "The Riddler 1:6 Resin Statue (The Batman)",
        maker: "McFarlane Toys · DC Direct",
        year: "2022",
        spec: "1/6 树脂雕像 · 电影 Logo 地台",
        image: "/media/merch/mcfarlane-riddler-statue.jpg",
        imageAlt: "McFarlane DC Direct 1/6 电影版谜语人树脂雕像与包装",
        body: "按电影谜语人服装制作的 1/6 树脂像，电影 Logo 直接作为底座。雕像区此前几乎全是蝙蝠侠，这一尊把达诺版谜语人补进陈列。与 7 寸可动是同一造型的不同产品，DC Direct 系列包装。",
        sourceUrl: "https://mcfarlane.com/toys/riddler-16-resin-statue-batman/",
        sourceLabel: "McFarlane Toys 官方产品页",
        verifiedAt: "2026.09.14",
      },
    ],
  },
  {
    id: "vehicles",
    kicker: "04",
    title: "车模与遥控载具",
    titleEn: "Vehicles",
    intro:
      "涵盖合金车模、遥控车、1/6 收藏级战车与蝙蝠摩托，重现美式改装肌肉车底盘、外露涡轮引擎与电影另一台关键载具。",
    items: [
      {
        id: "hotwheels-rc",
        name: "Hot Wheels R/C 1:10 电影蝙蝠战车",
        nameEn: "The Batman The Original Batmobile (HCD19)",
        maker: "Hot Wheels R/C · 美泰（Mattel）",
        year: "2022",
        spec: "1:10 比例遥控车 · 后驱 · 车灯与尾喷可发光",
        image: "/media/merch/hotwheels-rc.jpg",
        imageAlt: "Hot Wheels R/C 与《新蝙蝠侠》联名 1:10 遥控战车及手柄",
        body: "美泰风火轮推出的全功能遥控电影战车（货号 HCD19）。1:10 比例，手枪式遥控手柄，后驱带悬挂系统，最高时速约 16 公里；前大灯与尾喷口可通电发光，驾驶舱可放入约 6 寸人偶。",
        sourceUrl: "https://creations.mattel.com/products/hot-wheels-rc-the-batman-the-original-batmobile-hcd19",
        sourceLabel: "Mattel Creations 产品页 HCD19",
        verifiedAt: "2026.08.24",
      },
      {
        id: "jazzinc-clean",
        name: "Jazzinc 1/6 电影蝙蝠战车（普通版）",
        nameEn: "1/6 Batmobile from The Batman (2022) — Clean Version",
        maker: "Jazzinc Dioramas",
        year: "2022",
        spec: "1/6 比例 · 约 905 × 431 × 247 mm · 约 14 kg",
        image: "/media/merch/jazzinc-clean.jpg",
        imageAlt: "Jazzinc Dioramas 1/6 电影蝙蝠战车普通版侧前方",
        body: "荷兰 Jazzinc 依据电影实车图纸打造的 1/6 收藏级战车，适配 Hot Toys、INART 等 12 寸人偶。全车包含钢架结构与上千个零件，V8 引擎、仪表台与轮胎花纹按比例精准还原，配备灯光地台、车灯照明、排气烟雾与引擎音效系统。",
        sourceUrl: "https://jazzincdioramas.com/vehicles/16-scale-batmobile-from-the-batman-2022-clean-version",
        sourceLabel: "Jazzinc 普通版产品页",
        verifiedAt: "2026.08.24",
      },
      {
        id: "jazzinc-weathered",
        name: "Jazzinc 1/6 电影蝙蝠战车（战损版）",
        nameEn: "1/6 Batmobile from The Batman (2022) — Weathered Version",
        maker: "Jazzinc Dioramas",
        year: "2022",
        spec: "1/6 比例 · 战损涂装 · 电子声光烟雾功能",
        image: "/media/merch/jazzinc-weathered.jpg",
        imageAlt: "Jazzinc Dioramas 1/6 电影蝙蝠战车战损版，泥污与擦痕涂装",
        body: "与普通版同比例及同电子功能配置（含灯光、烟雾、音效与遥控），涂装重点还原企鹅人追逐战后的重度战损状态：车身布满泥泞溅痕、撞击刮痕与积尘。",
        sourceUrl: "https://jazzincdioramas.com/vehicles/batmobile2022weathered",
        sourceLabel: "Jazzinc 战损版产品页",
        verifiedAt: "2026.08.24",
      },
      {
        id: "hottoys-batcycle",
        name: "Hot Toys 1/6 蝙蝠摩托",
        nameEn: "Batcycle Sixth Scale Vehicle (MMS642)",
        maker: "Hot Toys",
        year: "2023",
        spec: "1/6 比例 · 全长约 42 cm · 适配 MMS641 蝙蝠侠",
        image: "/media/merch/hottoys-batcycle.jpg",
        imageAlt: "Hot Toys 1/6 电影版蝙蝠摩托，蝙蝠侠骑乘官方宣传图",
        body: "Movie Masterpiece MMS642，2023 年发售。全长约 42×19×19 厘米，还原上整流罩、带后视镜的车把、座下引擎与排气管、轮胎花纹。头灯与尾灯可 LED 发光，车把可左右转动，橡胶轮胎可转，附两款展示地台。蝙蝠侠人偶另售，专门配 1/6 Batman；补上 Jazzinc 战车之外的另一台电影载具。",
        sourceUrl: "https://www.sideshow.com/collectibles/dc-comics-batcycle-hot-toys-910637",
        sourceLabel: "Sideshow 产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "hotwheels",
        name: "风火轮 1:50 电影蝙蝠战车合金车模",
        nameEn: "Hot Wheels 1:50 Batman Series Batmobile",
        maker: "Hot Wheels · 美泰（Mattel）",
        year: "2022",
        spec: "1:50 比例合金车模",
        image: "/media/merch/hotwheels.jpg",
        imageAlt: "风火轮 1:50 蝙蝠战车合金模型细节",
        body: "美泰风火轮推出的中比例合金收藏车模。车身采用全金属压铸工艺，细致刻画了车头冲撞保险杠、外露后置引擎与双排气管细节。",
      },
      {
        id: "jada-32",
        name: "Jada 1:32 合金蝙蝠战车",
        nameEn: "Jada Toys 1:32 Die-Cast Batmobile",
        maker: "Jada Toys · Hollywood Rides",
        year: "2022",
        spec: "1:32 比例合金模型",
        image: "/media/merch/jada-box.jpg",
        imageAlt: "Jada 1:32 合金战车包装盒与车身展示",
        body: "采用开门设计与真实橡胶轮胎，包装印有电影红黑标志性视觉，是大众市场最受欢迎的桌上展示车模之一。",
      },
      {
        id: "jada-18",
        name: "Jada 1:18 大比例合金战车带人偶",
        nameEn: "Jada Toys 1:18 Batmobile with Figure",
        maker: "Jada Toys",
        year: "2022",
        spec: "1:18 比例 · 车灯可亮 · 附金属蝙蝠侠人偶",
        image: "/media/merch/jada-18.jpg",
        imageAlt: "Jada 1:18 战车车灯点亮状态与金属人偶",
        body: "大比例合金战车模型，车头大灯与尾部引擎支持 LED 通电发光，座舱内部精细还原了仪表台与防滚架，随盒附赠同比例压铸金属蝙蝠侠人偶。",
      },
    ],
  },
  {
    id: "lego",
    kicker: "05",
    title: "乐高套组",
    titleEn: "LEGO Sets",
    intro:
      "收录乐高在 2022 年电影上映前后推出的超级英雄（DC Super Heroes）与机械组（Technic）套组，以及 2026 年 DC 蝙蝠侠二十周年传奇蝙蝠车系列。",
    items: [
      {
        id: "lego-76181",
        name: "乐高 76181 蝙蝠战车：企鹅人追逐战",
        nameEn: "Batmobile: The Penguin Chase",
        maker: "LEGO · 乐高 DC 超级英雄系列",
        year: "2022",
        spec: "392 颗粒 · 附 2 枚迷你人仔",
        image: "/media/merch/lego-76181.jpg",
        imageAlt: "乐高 76181 蝙蝠战车与企鹅人人仔包装盒",
        body: "迷你人仔比例的电影版战车，还原美式肌肉车底盘、外露后置引擎与后扰流板。附带蝙蝠侠与企鹅人两枚人仔，重现冰山俱乐部外的公路追逐场景。",
      },
      {
        id: "lego-76179",
        name: "乐高 76179 蝙蝠侠与瑟琳娜摩托追逐",
        nameEn: "Batman & Selina Kyle Motorcycle Pursuit",
        maker: "LEGO · 乐高 DC 超级英雄系列",
        year: "2022",
        spec: "149 颗粒 · 附 2 枚迷你人仔与双摩托",
        image: "/media/merch/lego-76179.jpg",
        imageAlt: "乐高 76179 蝙蝠侠与猫女双机车套组",
        body: "双车场景套组，包含蝙蝠侠与瑟琳娜·凯尔两枚人仔及各自专属机车，对应影片中的雨夜巡行，可停放于 76183 蝙蝠洞内。",
      },
      {
        id: "lego-76183",
        name: "乐高 76183 蝙蝠洞：谜语人对决",
        nameEn: "Batcave: The Riddler Face-off",
        maker: "LEGO · 乐高 DC 超级英雄系列",
        year: "2022",
        spec: "581 颗粒 · 附 6 枚迷你人仔",
        image: "/media/merch/lego-76183.jpg",
        imageAlt: "乐高 76183 蝙蝠洞地下站台场景与六枚人仔",
        body: "该系列最大的场景套组。主体为韦恩塔地底废弃火车站改建的蝙蝠洞，可停放 76181 战车与 76179 摩托。包含蝙蝠侠、瑟琳娜、谜语人、流浪者布鲁斯、阿尔弗雷德与戈登共六枚人仔。",
      },
      {
        id: "lego-30455",
        name: "乐高 30455 蝙蝠战车（微型拼砌包）",
        nameEn: "Batmobile Polybag",
        maker: "LEGO · 乐高 DC 超级英雄系列",
        year: "2022",
        spec: "68 颗粒 · 拼砌袋装",
        image: "/media/merch/lego-30455.jpg",
        imageAlt: "乐高 30455 微型袋装战车",
        body: "电影宣传期间推出的微型拼砌包战车，共 68 个零件，适合作为小比例桌面摆件或快速拼搭体验。",
      },
      {
        id: "lego-42127",
        name: "乐高机械组 42127 电影版蝙蝠战车",
        nameEn: "THE BATMAN - BATMOBILE (Technic)",
        maker: "LEGO · 乐高机械组 Technic",
        year: "2022",
        spec: "1360 颗粒 · 发光积木 · 差速器与独立悬挂",
        image: "/media/merch/lego-42127.jpg",
        imageAlt: "乐高机械组 42127 大比例战车与发光效果",
        body: "机械组（Technic）大比例电影战车，由 1360 个零件构成。配备可动 V8 引擎活塞、后轮差速器、前轮转向与双发光积木（黄色前灯与红色后引擎喷火）。",
      },
      {
        id: "lego-76332",
        name: "乐高 76332 电影版蝙蝠战车",
        nameEn: "The Batman Batmobile (20th Anniversary)",
        maker: "LEGO · 乐高 DC 系列",
        year: "2026",
        spec: "经典复刻系列 · 附纪念金币与专属铭牌",
        image: "/media/merch/lego-76332.jpg",
        imageAlt: "乐高 76332 2022 电影版战车",
        body: "乐高 DC 蝙蝠侠二十周年「传奇蝙蝠车」系列中的 2022 电影版。车顶可拆卸，驾驶舱可放入佩戴布质披风的蝙蝠侠人仔，附带专属展示铭牌与纪念金币。",
      },
    ],
  },
  {
    id: "lifestyle",
    kicker: "06",
    title: "腕表、电竞与潮流跨界",
    titleEn: "Lifestyle & Collabs",
    intro:
      "收录华纳官方与瑞士高端独立制表、时尚腕表、专业电竞外设及运动品牌推出的跨界限定收藏品。",
    items: [
      {
        id: "kross-studio",
        name: "Kross Studio × The Batman 陀飞轮收藏套装",
        nameEn: "The Batman Tourbillon Collector Set",
        maker: "Kross Studio · 瑞士高级独立制表",
        year: "2022",
        spec: "45mm 钛金属 DLC 黑化 · 中央陀飞轮 · 限量 10 套",
        image: "/media/merch/kross-studio.jpg",
        imageAlt: "Kross Studio 陀飞轮腕表与信号灯表盒雕塑",
        body: "瑞士独立制表品牌 Kross Studio 与华纳联合推出的高级制表套装。腕表采用 45 毫米 5 级钛金属 DLC 黑化表壳，中央陀飞轮框架巧妙融入蝙蝠徽格栅设计，搭载 KS 7'000 手动上链机芯，具备 5 天动力储存；随表附带全尺寸可通电发光的蝙蝠信号灯铝合金表盒雕塑。",
        sourceUrl: "https://kross-studio.com/the-batman-collector-set",
        sourceLabel: "Kross Studio 产品页",
        verifiedAt: "2026.08.24",
      },
      {
        id: "police-batman",
        name: "Police × The Batman 联名限量腕表",
        nameEn: "Police x The Batman Limited Edition Watches",
        maker: "Police Lifestyle · 意大利时尚腕表",
        year: "2022",
        spec: "多款限量设计 · 多时区机芯 · 专属蝙蝠徽表盒",
        image: "/media/merch/police-batman.jpg",
        imageAlt: "Police 联名四款电影腕表实物展示",
        body: "意大利时尚腕表品牌 Police 推出的四款电影联名表款，分别对应蝙蝠侠、Vengeance、哥谭市与猫女主题。表壳采用棱角分明的装甲几何切面与红黑配色，配备多时区显示功能与蝙蝠徽造型表盒。",
      },
      {
        id: "fossil-batman",
        name: "Fossil × The Batman 胶囊自动机械表",
        nameEn: "Fossil x The Batman Capsule Collection Watch",
        maker: "Fossil · 限量自动机械表",
        year: "2022",
        spec: "42mm 黑电镀不锈钢 · 自动机械机芯 · 四条快拆表带",
        image: "/media/merch/fossil-batman.jpg",
        imageAlt: "Fossil 自动机械表与收纳盒及可替换表带",
        body: "Fossil 推出的限量版自动机械腕表（型号 LE1142SET）。42 毫米黑离子电镀不锈钢表壳，半镂空表盘饰有蝙蝠徽记，透底后盖可观赏红色自动陀；随附四条快拆战术表带及抽屉式陈列收纳盒。",
      },
      {
        id: "secretlab-batman",
        name: "Secretlab TITAN Evo 2022 联名电竞椅",
        nameEn: "Secretlab TITAN Evo 2022 The Batman Edition",
        maker: "Secretlab · 圣临电竞",
        year: "2022",
        spec: "TITAN Evo 旗舰人体工学 · 磁吸可拆卸蝙蝠徽",
        image: "/media/merch/secretlab-batman.jpg",
        imageAlt: "Secretlab TITAN Evo 2022 电影联名椅",
        body: "Secretlab 推出的 TITAN Evo 电影联名人体工学电竞椅。靠背磁吸附带有可拆卸的电影版蝙蝠徽金属件，椅身皮革采用战衣同款编织压纹与暗红滚边缝线。",
      },
      {
        id: "puma-batman",
        name: "PUMA × The Batman 运动鞋与机能服饰",
        nameEn: "PUMA x The Batman Collection",
        maker: "PUMA · 彪马",
        year: "2022",
        spec: "Suede / RS-X / Mayze 等联名鞋款及服饰",
        image: "/media/merch/puma-batman.jpg",
        imageAlt: "PUMA 联名 Suede Classic 等鞋款与服装",
        body: "PUMA 与电影联名推出的运动鞋服系列。涵盖 Suede Classic（后跟饰有蝙蝠群压纹）、RS-X 及 Mayze 等经典鞋型，整体设计采用电影标志性的黑红暗黑机能配色。",
      },
    ],
  },
  {
    id: "print",
    kicker: "07",
    title: "出版书籍",
    titleEn: "Books & Comics",
    intro:
      "收录官方艺术设定集、前传小说以及主演保罗·达诺亲笔编剧的衍生漫画，作为深入了解电影世界观与视觉设计的实体文献。",
    items: [
      {
        id: "artbook",
        name: "《新蝙蝠侠》官方艺术设定集",
        nameEn: "The Art of The Batman",
        maker: "Abrams Books · 詹姆斯·菲尔德 著",
        year: "2022",
        spec: "精装大开本 · 全彩印刷",
        image: "/media/merch/artbook.jpg",
        imageAlt: "《The Art of The Batman》精装设定集封面",
        body: "导演马特·里夫斯亲笔作序。全书收录数百张前期概念设计图、分镜头脚本、服装道具分解图与主创专访，详细记录了新哥谭视觉构建的全过程。",
      },
      {
        id: "novel",
        name: "官方前传小说《蝙蝠侠之前》",
        nameEn: "Before the Batman: An Original Movie Novel",
        maker: "Random House · 大卫·卢曼 著",
        year: "2022",
        spec: "平装单行本 · 附彩插海报",
        image: "/media/merch/novel.jpg",
        imageAlt: "前传小说 Before the Batman 官方封面",
        body: "官方授权前传衍生读物，重点讲述布鲁斯·韦恩早年改装肌肉战车、接受体能训练，以及爱德华·纳什顿在孤儿院萌生仇恨的起源故事。",
      },
      {
        id: "riddler-book",
        name: "官方前传漫画《谜语人元年》",
        nameEn: "The Riddler: Year One",
        maker: "DC Black Label · 保罗·达诺 编剧",
        year: "2022–2023",
        spec: "6 期限定漫画单行本",
        image: "/media/merch/riddler-book.jpg",
        imageAlt: "《The Riddler: Year One》漫画封面",
        body: "由电影谜语人饰演者保罗·达诺亲自编剧、DC Black Label 出版的成人向限定漫画，以司法会计视角展现了「新生」基金贪腐黑幕与谜语人的黑化历程。",
      },
    ],
  },
  {
    id: "media",
    kicker: "08",
    title: "影音与原声",
    titleEn: "Home Video & Soundtrack",
    intro:
      "包含 4K UHD 超高清蓝光光碟、标准蓝光碟片，以及迈克尔·吉亚奇诺创作的原声大碟与限量黑胶唱片。",
    items: [
      {
        id: "uhd",
        name: "《新蝙蝠侠》4K Ultra HD 收藏版",
        nameEn: "The Batman 4K Ultra HD + Blu-ray",
        maker: "Warner Bros. Home Entertainment",
        year: "2022",
        spec: "4K UHD + 蓝光双碟 · 杜比视界 / 杜比全景声",
        image: "/media/merch/uhd.jpg",
        imageAlt: "《新蝙蝠侠》4K Ultra HD 官方包装封面",
        body: "搭载原生 4K 超高清画质、杜比视界（Dolby Vision）HDR 及杜比全景声音轨，准确还原摄影师格雷格·弗雷泽（Greig Fraser）标志性的高反差光影与雨夜质感，附带两小时幕后花絮。",
      },
      {
        id: "bluray",
        name: "《新蝙蝠侠》蓝光标准版",
        nameEn: "The Batman Blu-ray Edition",
        maker: "Warner Bros. Home Entertainment",
        year: "2022",
        spec: "1080P 全高清蓝光碟",
        image: "/media/merch/bluray.jpg",
        imageAlt: "《新蝙蝠侠》蓝光标准版封面",
        body: "面向大众影迷的标准蓝光光盘，收录电影正片、主创访谈以及阿卡姆疯人院删减片段等收录内容。",
      },
      {
        id: "ost",
        name: "Mondo 电影原声 3XLP",
        nameEn: "The Batman Original Motion Picture Soundtrack 3XLP",
        maker: "Mondo × WaterTower Music · 迈克尔·吉亚奇诺 作曲",
        year: "2022",
        spec: "3 张 180g 黑胶 · 近两小时配乐 · Henry Abrams 封面",
        image: "/media/merch/ost.jpg",
        imageAlt: "Mondo 发行的《新蝙蝠侠》原声 3XLP，Henry Abrams 绘制封面",
        body: "奥斯卡获奖作曲家迈克尔·吉亚奇诺操刀，Mondo 与 WaterTower Music 合作推出三碟 180 克黑胶，近两小时配乐，三折封套，封面由 Henry Abrams 新绘。店限还有 Mondo 独家彩胶，同时有纯黑胶版本。数字流媒体与双 CD 仍是同一份配乐的其他载体；厚重四音符铜管与 Tiffin Boys 合唱的谜语人主题，是这一代蝙蝠侠最容易辨认的声音。",
        sourceUrl: "https://mondoshop.com/products/the-batman-original-motion-picture-soundtrack-3xlp",
        sourceLabel: "Mondo 官方产品页",
        verifiedAt: "2026.09.14",
      },
    ],
  },
  {
    id: "posters",
    kicker: "09",
    title: "院线限定与观影特典",
    titleEn: "Theatrical Exclusives",
    intro:
      "收录 2022 年公映与 2024 年重映期间，由 IMAX、Dolby Cinema、ScreenX、4DX 及各国院线发放的实体海报与观影特典。只收能核对出发行方或同期实物的版本，不把数字宣发图写成收藏海报。",
    items: [
      {
        id: "poster-imax",
        name: "IMAX × Bill Sienkiewicz《新蝙蝠侠》专属海报",
        nameEn: "The Batman IMAX Exclusive Art by Bill Sienkiewicz",
        maker: "IMAX · Bill Sienkiewicz · Warner Bros.",
        year: "2022",
        spec: "IMAX 官方专属视觉 · 拼贴三联画 · 日本另有 A3 迷你海报发放",
        image: "/media/merch/theatrical/thebatman-imax-sienkiewicz-vert.jpg",
        imageAlt: "Bill Sienkiewicz 绘制的《新蝙蝠侠》IMAX 专属海报，红黑拼贴中可见蝙蝠侠、谜语人、猫女与企鹅人",
        body: "2022 年 2 月由 IMAX 与华纳公布的正式专属视觉，作者为比尔·辛凯维奇（Bill Sienkiewicz）。红色蝙蝠轮廓里叠入谜语人、猫女、企鹅人、戈登与阿尔弗雷德，蝙蝠侠披风压住整幅构图。IGN 采访确认该三联画曾在部分 IMAX 开画场发放；日本 IMAX 官方则从 3 月 11 日起，向 IMAX 场次观众发放同一视觉的 A3「IMAXエクスクルーシブ・ビジュアル ミニポスター」，数量限定、一人一枚。后来的 Sideshow 收藏级石版画是同一原稿的另一条产品线，不并入本条。",
        sourceUrl: "https://www.ign.com/articles/how-the-batman-poster-was-made-bill-sienkiewicz",
        sourceLabel: "IGN · Sienkiewicz IMAX 海报访谈",
        verifiedAt: "2026.09.14",
      },
      {
        id: "poster-dolby",
        name: "Dolby Cinema《新蝙蝠侠》专属院线海报",
        nameEn: "The Batman Dolby Cinema Exclusive Poster",
        maker: "Dolby Cinema · Warner Bros.",
        year: "2022",
        spec: "2022.02.10 售票同步公布 · Dolby Cinema 专属视觉",
        image: "/media/merch/poster-dolby.jpg",
        imageAlt: "Dolby Cinema《新蝙蝠侠》专属海报，蝙蝠侠背对镜头立在蝙蝠信号灯前，两侧可见杜比 D 形外框",
        body: "杜比影院与华纳在 2022 年 2 月 10 日预售开启时发布的专属海报。蝙蝠侠背对镜头立在雨夜中，身后蝙蝠信号灯打亮夜空，左右被 Dolby 的「D」形外框切开。画面写有 Discover It At Dolby Cinema，对应杜比视界与全景声厅的宣传，而不是后来的收藏级艺术印刷。",
        sourceUrl: "https://comicbook.com/dc/news/the-batman-dolby-exclusive-poster-tickets-on-sale/",
        sourceLabel: "ComicBook · Dolby Cinema 专属海报",
        verifiedAt: "2026.09.14",
      },
      {
        id: "screenx-2022-a",
        name: "ScreenX《新蝙蝠侠》专属海报",
        nameEn: "The Batman ScreenX Exclusive Poster",
        maker: "ScreenX · CJ 4DPLEX · Warner Bros.",
        year: "2022",
        spec: "270° 全景厅专属视觉 · Batman / Catwoman / 载具构图",
        image: "/media/merch/theatrical/thebatman-screenx-2022.jpg",
        imageAlt: "ScreenX《新蝙蝠侠》专属海报，蝙蝠侠与猫女对立，前方是摩托车，后方是蝙蝠战车与哥谭天际线",
        body: "ScreenX 官方账号于 2022 年 2 月 10 日公布的 exclusive artwork。蝙蝠侠与猫女在暮色哥谭天际线前对望，猫女摩托在前、蝙蝠战车在后，ScreenX 标志嵌进城市剪影，上方是 Unmask The Truth。CJ 4DPLEX 新闻稿确认本片是第一部同时以 ScreenX 与 4DX 上映的蝙蝠侠电影。目前只核实到这一套正式构图；未见可独立成条的第二版 ScreenX artwork。",
        sourceUrl: "https://www.prnewswire.com/news-releases/the-batman-debuts-in-the-visually-immersive-270-degree-panoramic-screenx-theaters-301496149.html",
        sourceLabel: "CJ 4DPLEX 官方新闻稿",
        verifiedAt: "2026.09.14",
      },
      {
        id: "4dx-2022",
        name: "4DX《新蝙蝠侠》专属海报",
        nameEn: "The Batman 4DX Exclusive Poster",
        maker: "4DX · CJ 4DPLEX · Warner Bros.",
        year: "2022",
        spec: "4DX 厅专属视觉 · 蝙蝠侠展翅与蝙蝠战车",
        image: "/media/merch/theatrical/thebatman-4dx-2022.jpg",
        imageAlt: "4DX《新蝙蝠侠》专属海报，蝙蝠侠张开披风立于蝙蝠战车前，画面带 4DX 标志",
        body: "华纳兄弟墨西哥官方账号在 2022 年 2 月作为「póster exclusivo de 4DX」发布。蝙蝠侠张开披风立在雨夜街道，身后是肌肉车造型的蝙蝠战车，画面带 4DX 标志与仅在影院上映的字样。这是全球 4DX 宣传用的正式 artwork；日本 4DX 入场发放的 A3 实体是另一套雨夜全身构图，见下条，不重复。",
        sourceUrl: "https://x.com/WBPictures_Mx/status/1492302433455902721",
        sourceLabel: "Warner Bros. Pictures México",
        verifiedAt: "2026.09.14",
      },
      {
        id: "imax-fan-first",
        name: "IMAX Fan First Premiere 首映活动海报",
        nameEn: "DC Presents The Batman Fan First Premiere Poster Art",
        maker: "IMAX · Warner Bros. · DC",
        year: "2022",
        spec: "2022.03.01 · IMAX 提前场 · 活动宣传视觉",
        image: "/media/merch/theatrical/thebatman-imax-fan-first.jpg",
        imageAlt: "IMAX Fan First Premiere 活动视觉，雨夜屋顶上的蝙蝠侠剪影，标注 3 月 1 日 IMAX 提前场",
        body: "DC Presents The Batman Fan First Premieres Exclusively in IMAX，2022 年 3 月 1 日在美国超过一百座城市的 IMAX 厅提前放映。导演马特·里夫斯与 Fandango、IMAX 同步公布这张雨夜屋顶剪影的活动视觉。官方确认每张票附赠一张《Batman: The Long Halloween #1》独家封面漫画（一人一份，送完即止）。本条归档的是活动海报 artwork，不能写成所有观众都获赠实体海报。",
        sourceUrl: "https://comicbook.com/movies/news/how-to-get-tickets-the-batman-early-access-screening-batman-fan-first-premieres-imax/",
        sourceLabel: "ComicBook · Fan First Premiere 购票说明",
        verifiedAt: "2026.09.14",
      },
      {
        id: "jp-preview-imax",
        name: "日本 3 月 10 日前夜特别上映 IMAX 原创艺术海报",
        nameEn: "Japan IMAX Preview Screening Original Art Poster",
        maker: "DC Japan · IMAX · Warner Bros. Japan",
        year: "2022",
        spec: "2022.03.10 前夜特别上映 · IMAX 场次先着入场特典",
        image: "/media/merch/theatrical/thebatman-jp-preview-imax.jpg",
        imageAlt: "日本前夜特别上映 IMAX 原创艺术海报，蝙蝠侠头套特写与 Unmask the Truth 字样",
        body: "DC 日本官方宣布：3 月 10 日在全国 IMAX 与 Dolby Cinema 举行公开日前夜特别上映，两厅各有不同先着入场礼物。IMAX 场次发放这张原创艺术海报，画面是暴雨中的蝙蝠侠头套特写，上书 Unmask the Truth。官方原文写作「オリジナルアートポスター」，与 3 月 11 日起发放的 IMAX 迷你海报（Sienkiewicz 视觉）不是同一张。",
        sourceUrl: "https://x.com/dc_jp/status/1499293647158018051",
        sourceLabel: "DC 日本官方",
        verifiedAt: "2026.09.14",
      },
      {
        id: "jp-4dx-a3",
        name: "日本 4DX 入场特典海报",
        nameEn: "Japan 4DX Admission Gift Poster",
        maker: "4DX · Warner Bros. Japan",
        year: "2022",
        spec: "2022.03 日本 4DX 场次入场特典 · A3 级印刷",
        image: "/media/merch/theatrical/thebatman-jp-4dx-a3.jpg",
        imageAlt: "日本 4DX 入场特典海报实物，蝙蝠侠立在雨夜中，上方为 Unmask the Truth",
        body: "日本公映后，4DX 场次观众留下多份同期实物记录：入场获赠 A3 级海报，构图是雨夜中低头伫立的蝙蝠侠，顶部为 Unmask the Truth，与全球 4DX 展翅战车视觉、也与日本 IMAX 的 Sienkiewicz 迷你海报都不同。官方活动名称暂未找到完整存档，现根据实物与 2022 年 3 月观影记录归档。主图为同期观众实拍裁切，不是二手平台商品图。",
        verifiedAt: "2026.09.14",
      },
      {
        id: "cgv-imax-week2",
        name: "CGV 韩国 IMAX 第二周限定 A3 海报",
        nameEn: "CGV Korea IMAX Week 2 A3 Poster",
        maker: "CGV · IMAX",
        year: "2022",
        spec: "2022.03 · CGV IMAX 第二周观影特典 · A3",
        image: "/media/merch/theatrical/thebatman-cgv-imax-week2.jpg",
        imageAlt: "CGV 韩国 IMAX 第二周 A3 海报实物，蝙蝠侠头套特写，底部有 IMAX 标志",
        body: "韩国收藏记录显示，CGV 在《더 배트맨》上映第二周向 IMAX 场次观众发放 A3 海报。画面是暴雨中的蝙蝠侠头套特写，底部有 IMAX 标志，与第一周常见的全球 IMAX 拼贴视觉不同。官方原始活动页目前已失效，发放细节依据 2022 年 3 月同期影迷记录与实物照片整理。第一周、第三周、4DX 与 ScreenX 特典因缺少足够清晰的独立视觉，暂不入库。",
        verifiedAt: "2026.09.14",
      },
      {
        id: "lotte-week2-set",
        name: "Lotte Cinema 蝙蝠侠与猫女双海报套组",
        nameEn: "Lotte Cinema Batman & Catwoman Poster Set",
        maker: "Lotte Cinema",
        year: "2022",
        spec: "上映期间观影特典 · 蝙蝠侠 / 猫女单人 A3 成对发放",
        image: "/media/merch/theatrical/thebatman-lotte-week2-set.jpg",
        imageAlt: "乐天影城发放的蝙蝠侠与猫女 A3 单人海报实物并置，暮色哥谭天际线背景",
        body: "韩国收藏记录显示，乐天影城在上映期间发放蝙蝠侠、猫女各一张单人海报：两人分别立在暮色哥谭天际线前，构图接近角色介绍视觉，但是 A3 实体特典。同期转让记录常把两张作为一套，也提到第二周海报一并发放。官方活动页目前已失效，周次与正式活动名依据实物和 2022 年 3 月影迷记录整理，不把二手标题里的「Standing Poster」或「印刷签名版」写成官方名称。主图为同期观众实拍的一对实体，不是二手平台商品图。",
        verifiedAt: "2026.09.14",
      },
      {
        id: "penguin-sneak-peek-2024",
        name: "《新蝙蝠侠》×《企鹅人》2024 重映限定 Mini Poster",
        nameEn: "The Batman & The Penguin Sneak Peek Exclusive Mini-Poster",
        maker: "Warner Bros. · Dolby Cinema · AMC Theatres",
        year: "2024",
        spec: "2024.08.28 一夜重映 · 参与影院迷你海报 · 送完即止",
        image: "/media/merch/theatrical/thebatman-penguin-sneak-peek-2024.jpg",
        imageAlt: "2024 年《新蝙蝠侠》重映活动视觉，科林·法瑞尔饰演的企鹅人立在雨夜哥谭街头",
        body: "华纳、AMC 与 Dolby 把《新蝙蝠侠》带回大银幕，作为 8 月 28 日一夜场，并加映《企鹅人》制作特辑。美国约 100 块 Dolby Cinema at AMC 银幕，英国、法国、西班牙、沙特、瑞典与韩国等地的杜比厅也有参与。官方新闻稿写明观众可获 mini-poster featuring exclusive new art，送完即止；官方账号同步称为 special edition mini-poster。韩国若以 A3 发放、视觉与全球迷你海报相同，则不另建条目。本条主图用华纳活动主视觉归档，完整实体扫描仍待补。",
        sourceUrl: "https://www.ign.com/articles/the-batman-theaters-the-penuin-sneak-peek",
        sourceLabel: "IGN · 2024 重映与《企鹅人》加映",
        verifiedAt: "2026.09.14",
      },
    ],
  },
  {
    id: "prints",
    kicker: "10",
    title: "官方授权艺术印刷",
    titleEn: "Official Art Prints",
    intro:
      "收录 Mondo 丝网、Sideshow 收藏级石版，以及 Bottleneck、Trends 等授权渠道的零售艺术印刷。影院 IMAX 海报与后来的签名石版画分列，不把同一原稿写成两张院线特典。",
    items: [
      {
        id: "poster-mondo",
        name: "Mondo × Francesco Francavilla 限时版丝网海报",
        nameEn: "The Batman by Francesco Francavilla (Mondo Timed Edition)",
        maker: "Mondo · Francesco Francavilla 绘 · Lady Lazarus 印",
        year: "2022",
        spec: "24×36 英寸 · 手工丝网 · Timed Edition（3/3–3/6）",
        image: "/media/merch/poster-mondo.jpg",
        imageAlt: "Mondo 限时版丝网海报，红黑主色调，雨夜中喷射尾焰的蝙蝠战车",
        body: "Mondo 为电影发行的第一张授权丝网。弗朗切斯科·弗兰卡维拉绘制，Lady Lazarus 印刷，24×36 英寸。常规版是 Timed Edition：2022 年 3 月 3 日 11:00 CT 至 3 月 6 日 23:59 CT，印量由该时段销量决定。红黑两色勾出雨夜战车尾焰与义警剪影。",
        sourceUrl: "https://mondoshop.com/blogs/news/the-batman-by-francesco-francavilla-on-sale-info",
        sourceLabel: "Mondo 官方发售说明",
        verifiedAt: "2026.09.14",
      },
      {
        id: "poster-mondo-var",
        name: "Mondo × Francesco Francavilla 变体版丝网海报",
        nameEn: "The Batman Variant Screenprint by Francesco Francavilla",
        maker: "Mondo · Francesco Francavilla 绘 · Lady Lazarus 印",
        year: "2022",
        spec: "24×36 英寸 · 手工丝网 · 限量 325 张",
        image: "/media/merch/poster-mondo-var.jpg",
        imageAlt: "Mondo 变体版丝网海报，红雨中的蝙蝠侠头套特写",
        body: "与限时常规版同日开售的变体。Mondo 官方写明 Edition of 325，同样 24×36、Lady Lazarus 印刷。画面改成暴雨与红光里的头套特写。325 这个数字来自 Mondo 发售页，不是二手转述。",
        sourceUrl: "https://mondoshop.com/blogs/news/the-batman-by-francesco-francavilla-on-sale-info",
        sourceLabel: "Mondo 官方发售说明",
        verifiedAt: "2026.09.14",
      },
      {
        id: "sienkiewicz-fine-art",
        name: "Bill Sienkiewicz《Unmask the Truth》收藏级艺术印刷",
        nameEn: "Batman: Unmask the Truth Fine Art Lithograph",
        maker: "Sideshow Collectibles · Bill Sienkiewicz Art · DC",
        year: "2022",
        spec: "18×24 英寸石版 · 画面约 14×19 英寸 · 限量 150 · 艺术家手签",
        image: "/media/merch/theatrical/thebatman-sienkiewicz-lithograph.jpg",
        imageAlt: "Bill Sienkiewicz《Unmask the Truth》收藏级印刷，红黑拼贴中的蝙蝠侠与哥谭群像",
        body: "Sideshow 与 Bill Sienkiewicz Art 发行的 DC 授权石版画。构图来自他为 IMAX 绘制的电影群像，但本条是后来单独出售的收藏级印刷：18×24 英寸、限量 150、艺术家手签并附证书。不要把它和影院 IMAX 海报当成同一件产品。",
        sourceUrl: "https://www.sideshow.com/collectibles/dc-comics-batman-unmask-the-truth-bill-sienkiewicz-art-501966U",
        sourceLabel: "Sideshow 官方产品页",
        verifiedAt: "2026.09.14",
      },
      {
        id: "sam-green-bottleneck",
        name: "Sam Green × Bottleneck Gallery《新蝙蝠侠》艺术海报",
        nameEn: "The Batman by Sam Green",
        maker: "Sam Green · Bottleneck Gallery",
        year: "2023",
        spec: "24×36 英寸 · Giclée · 手编号 · 常规版 175 张",
        image: "/media/merch/theatrical/thebatman-sam-green-bottleneck.jpg",
        imageAlt: "Sam Green 为 Bottleneck Gallery 绘制的《新蝙蝠侠》艺术海报，侦探板风格拼贴雨夜哥谭与角色",
        body: "Bottleneck Gallery 于 2023 年 3 月 7 日发售。Sam Green 把电影场面做成谜语人式侦探板：雨夜哥谭、战车、猫女、企鹅人与剪报钉在同一张 24×36 英寸 Giclée 上。常规版手编号 175 张；另有变体版 100 张。这是画廊限量艺术印刷，不是院线特典。",
        sourceUrl: "https://bottleneckgallery.com/blogs/news/new-batman-prints-by-dayne-henry-sam-green-mike-mcgee-on-sale-info",
        sourceLabel: "Bottleneck Gallery 发售说明",
        verifiedAt: "2026.09.14",
      },
      {
        id: "poster-wall",
        name: "「揭开真相」经典公映海报挂画",
        nameEn: "Unmask the Truth 24×36 Poster",
        maker: "Trends International",
        year: "2022",
        spec: "24×36 英寸零售挂画",
        image: "/media/merch/poster-wall.jpg",
        imageAlt: "装裱在画框中的「揭开真相」官方海报，红字问号覆盖蝙蝠侠面庞",
        body: "公映期间进入零售渠道的官方主视觉：红字问号与密电符号涂鸦盖在蝙蝠侠面庞上，对应全片侦探解谜。这是 Trends International 一类的 24×36 英寸零售海报，不是影院发放特典。",
      },
      {
        id: "poster-rays",
        name: "「破晓微光」官方艺术挂画",
        nameEn: "Rays of Light Art Print",
        maker: "Trends International / Pyramid",
        year: "2022",
        spec: "24×36 英寸胶印挂画",
        image: "/media/merch/poster-rays.jpg",
        imageAlt: "蝙蝠侠伫立于一束垂直顶光之下的零售艺术挂画",
        body: "零售艺术印刷。蝙蝠侠立在一束垂直顶光里，红黑渐变背景。与院线 IMAX / Dolby 专属视觉不是同一条产品线，继续留在授权印刷栏。",
      },
    ],
  },
];

export const MERCH_TEASERS = [MERCH[0].items[0], MERCH[1].items[0], MERCH[2].items[0]];

