/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as CraftRouteImport } from './routes/craft'
import { Route as DossierRouteImport } from './routes/dossier'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GearRouteImport } from './routes/gear'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as RataaladaRouteImport } from './routes/rataalada'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as RootsRouteImport } from './routes/roots'
import { Route as TheoriesRouteImport } from './routes/theories'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as PlacesIndexRouteImport } from './routes/places.index'
import { Route as PlacesIdRouteImport } from './routes/places.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftRoute = CraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierRoute = DossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GearRoute = GearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const RataaladaRoute = RataaladaRouteImport.update({
  id: '/rataalada',
  path: '/rataalada',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const RootsRoute = RootsRouteImport.update({
  id: '/roots',
  path: '/roots',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoriesRoute = TheoriesRouteImport.update({
  id: '/theories',
  path: '/theories',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeopleRoute,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PeopleRoute,
} as any)
const PlacesIndexRoute = PlacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlacesRoute,
} as any)
const PlacesIdRoute = PlacesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlacesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/craft': typeof CraftRoute
  '/dossier': typeof DossierRoute
  '/gallery': typeof GalleryRoute
  '/gear': typeof GearRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/people': typeof PeopleRouteWithChildren
  '/places': typeof PlacesRouteWithChildren
  '/rataalada': typeof RataaladaRoute
  '/recap': typeof RecapRoute
  '/roots': typeof RootsRoute
  '/theories': typeof TheoriesRoute
  '/people/$id': typeof PeopleIdRoute
  '/places/$id': typeof PlacesIdRoute
  '/people/': typeof PeopleIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/craft': typeof CraftRoute
  '/dossier': typeof DossierRoute
  '/gallery': typeof GalleryRoute
  '/gear': typeof GearRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/rataalada': typeof RataaladaRoute
  '/recap': typeof RecapRoute
  '/roots': typeof RootsRoute
  '/theories': typeof TheoriesRoute
  '/people/$id': typeof PeopleIdRoute
  '/places/$id': typeof PlacesIdRoute
  '/people': typeof PeopleIndexRoute
  '/places': typeof PlacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/craft': typeof CraftRoute
  '/dossier': typeof DossierRoute
  '/gallery': typeof GalleryRoute
  '/gear': typeof GearRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/people': typeof PeopleRouteWithChildren
  '/places': typeof PlacesRouteWithChildren
  '/rataalada': typeof RataaladaRoute
  '/recap': typeof RecapRoute
  '/roots': typeof RootsRoute
  '/theories': typeof TheoriesRoute
  '/people/$id': typeof PeopleIdRoute
  '/places/$id': typeof PlacesIdRoute
  '/people/': typeof PeopleIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/craft'
    | '/dossier'
    | '/gallery'
    | '/gear'
    | '/login'
    | '/merch'
    | '/people'
    | '/places'
    | '/rataalada'
    | '/recap'
    | '/roots'
    | '/theories'
    | '/people/$id'
    | '/places/$id'
    | '/people/'
    | '/places/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/craft'
    | '/dossier'
    | '/gallery'
    | '/gear'
    | '/login'
    | '/merch'
    | '/rataalada'
    | '/recap'
    | '/roots'
    | '/theories'
    | '/people/$id'
    | '/places/$id'
    | '/people'
    | '/places'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/craft'
    | '/dossier'
    | '/gallery'
    | '/gear'
    | '/login'
    | '/merch'
    | '/people'
    | '/places'
    | '/rataalada'
    | '/recap'
    | '/roots'
    | '/theories'
    | '/people/$id'
    | '/places/$id'
    | '/people/'
    | '/places/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  CraftRoute: typeof CraftRoute
  DossierRoute: typeof DossierRoute
  GalleryRoute: typeof GalleryRoute
  GearRoute: typeof GearRoute
  LoginRoute: typeof LoginRoute
  MerchRoute: typeof MerchRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  PlacesRoute: typeof PlacesRouteWithChildren
  RataaladaRoute: typeof RataaladaRoute
  RecapRoute: typeof RecapRoute
  RootsRoute: typeof RootsRoute
  TheoriesRoute: typeof TheoriesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft': {
      id: '/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof CraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier': {
      id: '/dossier'
      path: '/dossier'
      fullPath: '/dossier'
      preLoaderRoute: typeof DossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear': {
      id: '/gear'
      path: '/gear'
      fullPath: '/gear'
      preLoaderRoute: typeof GearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rataalada': {
      id: '/rataalada'
      path: '/rataalada'
      fullPath: '/rataalada'
      preLoaderRoute: typeof RataaladaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roots': {
      id: '/roots'
      path: '/roots'
      fullPath: '/roots'
      preLoaderRoute: typeof RootsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theories': {
      id: '/theories'
      path: '/theories'
      fullPath: '/theories'
      preLoaderRoute: typeof TheoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/places/': {
      id: '/places/'
      path: '/'
      fullPath: '/places/'
      preLoaderRoute: typeof PlacesIndexRouteImport
      parentRoute: typeof PlacesRoute
    }
    '/places/$id': {
      id: '/places/$id'
      path: '/$id'
      fullPath: '/places/$id'
      preLoaderRoute: typeof PlacesIdRouteImport
      parentRoute: typeof PlacesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PeopleRouteChildren {
  PeopleIdRoute: typeof PeopleIdRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeopleIdRoute: PeopleIdRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

interface PlacesRouteChildren {
  PlacesIdRoute: typeof PlacesIdRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
}

const PlacesRouteChildren: PlacesRouteChildren = {
  PlacesIdRoute: PlacesIdRoute,
  PlacesIndexRoute: PlacesIndexRoute,
}

const PlacesRouteWithChildren =
  PlacesRoute._addFileChildren(PlacesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  CraftRoute: CraftRoute,
  DossierRoute: DossierRoute,
  GalleryRoute: GalleryRoute,
  GearRoute: GearRoute,
  LoginRoute: LoginRoute,
  MerchRoute: MerchRoute,
  PeopleRoute: PeopleRouteWithChildren,
  PlacesRoute: PlacesRouteWithChildren,
  RataaladaRoute: RataaladaRoute,
  RecapRoute: RecapRoute,
  RootsRoute: RootsRoute,
  TheoriesRoute: TheoriesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
